# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass, replace
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
    final,
)


class TaskKind:
    pass


@final
@dataclass(frozen=True)
class TaskCI(TaskKind):
    pass


@final
@dataclass(frozen=True)
class TaskThread(TaskKind):
    pass


@final
@dataclass(frozen=True)
class TaskSpec(TaskKind):
    pass


@final
@dataclass(frozen=True)
class TaskAsk(TaskKind):
    pass


@final
@dataclass(frozen=True)
class TaskDefer(TaskKind):
    pass


TaskKindT = TaskCI | TaskThread | TaskSpec | TaskAsk | TaskDefer


class TaskStatus:
    pass


@final
@dataclass(frozen=True)
class StatusPending(TaskStatus):
    pass


@final
@dataclass(frozen=True)
class StatusCompleted(TaskStatus):
    pass


@final
@dataclass(frozen=True)
class StatusBlocked(TaskStatus):
    pass


TaskStatusT = StatusPending | StatusCompleted | StatusBlocked


@final
@dataclass(frozen=True)
class TaskRow:
    title: str
    description: str
    kind: TaskKind
    status: TaskStatus
    source_comment: int | None


# ExecutionLease: singleton inductive, constructor was Build_ExecutionLease


def lease_task(e: ExecutionLease) -> int:
    lease_task0 = e
    return lease_task0


def task_executable(kind0: TaskKind) -> bool:
    match kind0:
        case TaskCI():
            return True
        case TaskThread():
            return True
        case TaskSpec():
            return True
        case TaskAsk():
            return False
        case TaskDefer():
            return False
        case __impossible:
            assert_never(__impossible)


def task_row_executable(row: TaskRow) -> bool:
    match row.status:
        case StatusPending():
            return task_executable(row.kind)
        case StatusCompleted():
            return False
        case StatusBlocked():
            return False
        case __impossible:
            assert_never(__impossible)


def find_comment_duplicate(
    comment: int,
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    for task in order:
        __option = rows.get(_rocq_positive_key(task))
        if __option is None:
            continue
        row = __option
        __option = row.source_comment
        if __option is None:
            continue
        existing = __option
        if existing == comment:
            return task
        continue
    return None


def row_has_pending_title(
    candidate_title: str,
    row: TaskRow,
) -> bool:
    match row.status:
        case StatusPending():
            return row.title == candidate_title
        case StatusCompleted():
            return False
        case StatusBlocked():
            return False
        case __impossible:
            assert_never(__impossible)


def task_has_pending_title(
    candidate_title: str,
    task: int,
    rows: dict[int, TaskRow],
) -> bool:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return False
    row = __option
    return row_has_pending_title(candidate_title, row)


def find_pending_title_duplicate(
    candidate_title: str,
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    for task in order:
        if task_has_pending_title(candidate_title, task, rows):
            return task
        continue
    return None


def enqueue_task(
    task: int,
    row: TaskRow,
    order: list[int],
    rows: dict[int, TaskRow],
) -> tuple[tuple[list[int], dict[int, TaskRow]], int]:
    __option = row.source_comment
    if __option is None:
        __option = find_pending_title_duplicate(row.title, order, rows)
        if __option is None:
            return (
                (
                    order + [task],
                    _rocq_map_add(
                        _rocq_positive_key(task),
                        row,
                        rows,
                    ),
                ),
                task,
            )
        existing = __option
        return (
            (
                order,
                rows,
            ),
            existing,
        )
    comment = __option
    __option = find_comment_duplicate(comment, order, rows)
    if __option is None:
        return (
            (
                order + [task],
                _rocq_map_add(
                    _rocq_positive_key(task),
                    row,
                    rows,
                ),
            ),
            task,
        )
    existing = __option
    return (
        (
            order,
            rows,
        ),
        existing,
    )


def pick_first_ci(
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    for task in order:
        __option = rows.get(_rocq_positive_key(task))
        if __option is None:
            continue
        row = __option
        if task_row_executable(row) and isinstance(row.kind, TaskCI):
            return task
        continue
    return None


def pick_first_non_ci(
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    for task in order:
        __option = rows.get(_rocq_positive_key(task))
        if __option is None:
            continue
        row = __option
        if task_row_executable(row) and not isinstance(row.kind, TaskCI):
            return task
        continue
    return None


def pick_next_task(
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    __option = pick_first_ci(order, rows)
    if __option is None:
        return pick_first_non_ci(order, rows)
    task = __option
    return task


def begin_task(
    task: int,
    lease: ExecutionLease | None,
    rows: dict[int, TaskRow],
) -> ExecutionLease | None:
    __option = lease
    if __option is None:
        __option = rows.get(_rocq_positive_key(task))
        if __option is None:
            return None
        row = __option
        if task_row_executable(row):
            return task
        return None
    e = __option
    return None


def clear_matching_lease(
    task: int,
    lease: ExecutionLease | None,
) -> ExecutionLease | None:
    __option = lease
    if __option is None:
        return None
    active = __option
    if lease_task(active) == task:
        return None
    return lease


def complete_task(
    task: int,
    lease: ExecutionLease | None,
    rows: dict[int, TaskRow],
) -> tuple[ExecutionLease | None, dict[int, TaskRow]]:
    lease_ = clear_matching_lease(task, lease)
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return (
            lease_,
            rows,
        )
    row = __option
    row_ = replace(
        row,
        status=StatusCompleted(),
    )
    return (
        lease_,
        _rocq_map_add(
            _rocq_positive_key(task),
            row_,
            rows,
        ),
    )


# Python ExtractionDiagnostic [PYEX003]: Type alias declaration is not emitted Remediation: Use a concrete inductive/record or add an extraction remapping for the type.


class CIConclusion:
    pass


@final
@dataclass(frozen=True)
class CIConclusionFailure(CIConclusion):
    pass


@final
@dataclass(frozen=True)
class CIConclusionTimedOut(CIConclusion):
    pass


CIConclusionT = CIConclusionFailure | CIConclusionTimedOut


@final
@dataclass(frozen=True)
class CIFailureSnapshot:
    ci_run: int
    ci_check_name: str
    ci_conclusion: CIConclusion

    def task_title(self) -> str:
        snapshot = self
        return snapshot.ci_check_name

    def task_row(self) -> TaskRow:
        snapshot = self
        return TaskRow(
            title=snapshot.task_title(),
            description="",
            kind=TaskCI(),
            status=StatusPending(),
            source_comment=None,
        )

    def update_latest(
        self,
        row: CIRow,
    ) -> CIRow:
        snapshot = self
        return replace(
            row,
            ci_snapshot=snapshot,
            ci_phase=CIFailing(),
        )

    def new_live_row(
        self,
        task: int,
    ) -> CIRow:
        snapshot = self
        return CIRow(
            ci_snapshot=snapshot,
            ci_phase=CIFailing(),
            ci_task=task,
            ci_attempts=0,
        )


class CIPhase:
    pass


@final
@dataclass(frozen=True)
class CINoFailure(CIPhase):
    pass


@final
@dataclass(frozen=True)
class CIFailing(CIPhase):
    pass


@final
@dataclass(frozen=True)
class CIFixing(CIPhase):
    pass


@final
@dataclass(frozen=True)
class CIGivenUp(CIPhase):
    pass


@final
@dataclass(frozen=True)
class CIResolved(CIPhase):
    pass


CIPhaseT = CINoFailure | CIFailing | CIFixing | CIGivenUp | CIResolved


@final
@dataclass(frozen=True)
class CIRow:
    ci_snapshot: CIFailureSnapshot | None
    ci_phase: CIPhase
    ci_task: int | None
    ci_attempts: int

    def live_task(self) -> int | None:
        row = self
        match row.ci_phase:
            case CINoFailure():
                return None
            case CIFailing():
                __option = row.ci_task
                if __option is None:
                    return None
                task = __option
                return task
            case CIFixing():
                __option = row.ci_task
                if __option is None:
                    return None
                task = __option
                return task
            case CIGivenUp():
                return None
            case CIResolved():
                return None
            case __impossible:
                assert_never(__impossible)


# Python ExtractionDiagnostic [PYEX003]: Type alias declaration is not emitted Remediation: Use a concrete inductive/record or add an extraction remapping for the type.


ci_max_attempts: int = 3


def record_ci_failure(
    check: requiredCheck,
    snapshot: CIFailureSnapshot,
    new_task: int,
    ci_store: cIStore,
    task_order: list[int],
    task_rows: dict[int, TaskRow],
) -> tuple[tuple[tuple[cIStore, list[int]], dict[int, TaskRow]], int]:
    __option = ci_store.get(_rocq_positive_key(check))
    if __option is None:
        row = snapshot.new_live_row(new_task)
        __pair = enqueue_task(new_task, snapshot.task_row(), task_order, task_rows)
        p = __pair[0]
        created_task = __pair[1]
        __pair = p
        task_order_ = __pair[0]
        task_rows_ = __pair[1]
        return (
            (
                (
                    _rocq_map_add(
                        _rocq_positive_key(check),
                        row,
                        ci_store,
                    ),
                    task_order_,
                ),
                task_rows_,
            ),
            created_task,
        )
    row = __option
    __option = row.live_task()
    if __option is None:
        row_ = snapshot.new_live_row(new_task)
        __pair = enqueue_task(new_task, snapshot.task_row(), task_order, task_rows)
        p = __pair[0]
        created_task = __pair[1]
        __pair = p
        task_order_ = __pair[0]
        task_rows_ = __pair[1]
        return (
            (
                (
                    _rocq_map_add(
                        _rocq_positive_key(check),
                        row_,
                        ci_store,
                    ),
                    task_order_,
                ),
                task_rows_,
            ),
            created_task,
        )
    existing_task = __option
    row_ = snapshot.update_latest(row)
    return (
        (
            (
                _rocq_map_add(
                    _rocq_positive_key(check),
                    row_,
                    ci_store,
                ),
                task_order,
            ),
            task_rows,
        ),
        existing_task,
    )


def start_ci_fix(
    check: requiredCheck,
    ci_store: cIStore,
    task_rows: dict[int, TaskRow],
    lease: ExecutionLease | None,
) -> tuple[cIStore, ExecutionLease | None]:
    __option = ci_store.get(_rocq_positive_key(check))
    if __option is None:
        return (
            ci_store,
            lease,
        )
    row = __option
    __option = row.live_task()
    if __option is None:
        return (
            ci_store,
            lease,
        )
    task = __option
    __option = begin_task(task, lease, task_rows)
    if __option is None:
        return (
            ci_store,
            lease,
        )
    lease_ = __option
    row_ = replace(
        row,
        ci_phase=CIFixing(),
        ci_task=task,
    )
    return (
        _rocq_map_add(
            _rocq_positive_key(check),
            row_,
            ci_store,
        ),
        lease_,
    )


def ci_attempt_can_retry(attempts: int) -> bool:
    return attempts < ci_max_attempts


def record_ci_attempt_failed(
    check: requiredCheck,
    ci_store: cIStore,
) -> cIStore:
    __option = ci_store.get(_rocq_positive_key(check))
    if __option is None:
        return ci_store
    row = __option
    match row.ci_phase:
        case CINoFailure():
            return ci_store
        case CIFailing():
            return ci_store
        case CIFixing():
            __option = row.ci_task
            if __option is None:
                return ci_store
            task = __option
            attempts_ = row.ci_attempts + 1
            if ci_attempt_can_retry(attempts_):
                row_ = replace(
                    row,
                    ci_phase=CIFailing(),
                    ci_task=task,
                    ci_attempts=attempts_,
                )
                return _rocq_map_add(
                    _rocq_positive_key(check),
                    row_,
                    ci_store,
                )
            row_ = replace(
                row,
                ci_phase=CIGivenUp(),
                ci_task=None,
                ci_attempts=attempts_,
            )
            return _rocq_map_add(
                _rocq_positive_key(check),
                row_,
                ci_store,
            )
        case CIGivenUp():
            return ci_store
        case CIResolved():
            return ci_store
        case __impossible:
            assert_never(__impossible)


def complete_ci_task_if_present(
    task: int | None,
    task_rows: dict[int, TaskRow],
    lease: ExecutionLease | None,
) -> tuple[ExecutionLease | None, dict[int, TaskRow]]:
    __option = task
    if __option is None:
        return (
            lease,
            task_rows,
        )
    task_id = __option
    return complete_task(
        task_id,
        lease,
        task_rows,
    )


def record_ci_resolved(
    check: requiredCheck,
    ci_store: cIStore,
    task_rows: dict[int, TaskRow],
    lease: ExecutionLease | None,
) -> tuple[tuple[cIStore, dict[int, TaskRow]], ExecutionLease | None]:
    __option = ci_store.get(_rocq_positive_key(check))
    if __option is None:
        return (
            (
                ci_store,
                task_rows,
            ),
            lease,
        )
    row = __option
    __pair = complete_ci_task_if_present(row.ci_task, task_rows, lease)
    lease_ = __pair[0]
    task_rows_ = __pair[1]
    row_ = replace(
        row,
        ci_phase=CIResolved(),
        ci_task=None,
        ci_attempts=0,
    )
    return (
        (
            _rocq_map_add(
                _rocq_positive_key(check),
                row_,
                ci_store,
            ),
            task_rows_,
        ),
        lease_,
    )
