# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
)

_A = TypeVar("_A")


# option: remapped to Python primitive


class State:
    pass


@dataclass(frozen=True)
class Idle(State):
    pass


@dataclass(frozen=True)
class Sending(State):
    pass


@dataclass(frozen=True)
class AwaitingReply(State):
    pass


@dataclass(frozen=True)
class Draining(State):
    pass


@dataclass(frozen=True)
class Cancelled(State):
    pass


StateT = Idle | Sending | AwaitingReply | Draining | Cancelled


class Event:
    pass


@dataclass(frozen=True)
class Send(Event):
    pass


@dataclass(frozen=True)
class ReplyChunk(Event):
    pass


@dataclass(frozen=True)
class ReplyEnd(Event):
    pass


@dataclass(frozen=True)
class CancelFire(Event):
    pass


@dataclass(frozen=True)
class DrainObserve(Event):
    pass


@dataclass(frozen=True)
class TurnReturn(Event):
    pass


EventT = Send | ReplyChunk | ReplyEnd | CancelFire | DrainObserve | TurnReturn


def transition(
    current: State,
    event0: Event,
) -> State | None:
    match current:
        case Idle():
            match event0:
                case Send():
                    return Sending()
                case ReplyChunk():
                    return None
                case ReplyEnd():
                    return None
                case CancelFire():
                    return None
                case DrainObserve():
                    return None
                case TurnReturn():
                    return None
                case __impossible:
                    assert_never(__impossible)
        case Sending():
            match event0:
                case Send():
                    return None
                case ReplyChunk():
                    return AwaitingReply()
                case ReplyEnd():
                    return None
                case CancelFire():
                    return Draining()
                case DrainObserve():
                    return None
                case TurnReturn():
                    return None
                case __impossible:
                    assert_never(__impossible)
        case AwaitingReply():
            match event0:
                case Send():
                    return None
                case ReplyChunk():
                    return AwaitingReply()
                case ReplyEnd():
                    return AwaitingReply()
                case CancelFire():
                    return Draining()
                case DrainObserve():
                    return None
                case TurnReturn():
                    return Idle()
                case __impossible:
                    assert_never(__impossible)
        case Draining():
            match event0:
                case Send():
                    return None
                case ReplyChunk():
                    return None
                case ReplyEnd():
                    return None
                case CancelFire():
                    return None
                case DrainObserve():
                    return Draining()
                case TurnReturn():
                    return Cancelled()
                case __impossible:
                    assert_never(__impossible)
        case Cancelled():
            match event0:
                case Send():
                    return None
                case ReplyChunk():
                    return None
                case ReplyEnd():
                    return None
                case CancelFire():
                    return None
                case DrainObserve():
                    return None
                case TurnReturn():
                    return Idle()
                case __impossible:
                    assert_never(__impossible)
        case __impossible:
            assert_never(__impossible)
