# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
)


# unit: remapped to Python primitive
# nat: remapped to Python primitive
# option: remapped to Python primitive
# list: remapped to Python primitive


def _io_roundtrip_message(message: int) -> IO[int]:
    def __io_bind_next(mutex):
        def __io_bracket_release(x):
            return mutex.release()

        def __io_bracket_use(x):
            def __io_bind_next(channel):
                def __io_bind_next(x0):
                    def __io_bind_next(received):
                        def __io_bind_next(future):
                            def __io_bind_next(x1):
                                def __io_bind_next(result):
                                    return IO.pure(result)

                                return future.result().bind(__io_bind_next)

                            return future.set_result(received).bind(__io_bind_next)

                        return Future.new().bind(__io_bind_next)

                    return channel.receive().bind(__io_bind_next)

                return channel.send(message).bind(__io_bind_next)

            return Channel.new().bind(__io_bind_next)

        return IO.bracket(mutex.acquire(), __io_bracket_release, __io_bracket_use)

    return Mutex.new().bind(__io_bind_next)


async def roundtrip_message(message: int) -> int:
    return await _io_roundtrip_message(message).run()
