# Generated by rocq-python-extraction (target: Python 3.14t)
from itertools import islice
from dataclasses import dataclass
from fractions import Fraction
from typing import (
    Any,
    Awaitable,
    Callable,
    Generic,
    Iterable,
    Iterator,
    Never,
    Protocol,
    TypeVar,
    assert_never,
    cast,
)

_CoForceT = TypeVar("_CoForceT")
_ModuleArgT = TypeVar("_ModuleArgT")
_ModuleRetT = TypeVar("_ModuleRetT")
_StateTState = TypeVar("_StateTState")
_StateTValue = TypeVar("_StateTValue")
_StateTNext = TypeVar("_StateTNext")
_IOValue = TypeVar("_IOValue")
_IONext = TypeVar("_IONext")


class _Impossible(RuntimeError):
    pass


def _impossible() -> Never:
    raise _Impossible()


class _RocqUtf8BoundaryError(UnicodeError):
    pass


class _RocqNumericDomainError(ValueError):
    pass


def _rocq_numeric_domain_error(kind: str, value: object) -> Never:
    raise _RocqNumericDomainError(f"Rocq {kind} value out of domain: {value!r}")


key = int  # finite-map module key alias
elt = int  # finite-set module element alias


def _rocq_positive_key(key: int) -> int:
    if key <= 0:
        raise _RocqNumericDomainError("positive map/set key", key)
    return key


def _rocq_string_key(key: str) -> str:
    if not isinstance(key, str):
        raise TypeError(f"Rocq string map/set key must be str: {key!r}")
    return key


def _rocq_sorted_key(key: object) -> Any:
    return key.encode("utf-8") if isinstance(key, str) else key


def _rocq_map_add(
    key: object, value: object, mapping: dict[object, object]
) -> dict[object, object]:
    result = dict(mapping)
    result[key] = value
    return result


def _rocq_map_remove(
    key: object, mapping: dict[object, object]
) -> dict[object, object]:
    result = dict(mapping)
    result.pop(key, None)
    return result


def _rocq_map_elements(mapping: dict[object, object]) -> list[tuple[object, object]]:
    return sorted(mapping.items(), key=lambda item: _rocq_sorted_key(item[0]))


def _rocq_map_fold(
    function: Callable[[object, object, object], object],
    mapping: dict[object, object],
    initial: object,
) -> object:
    result = initial
    for key, value in _rocq_map_elements(mapping):
        result = function(key, value, result)
    return result


def _rocq_set_add(key: object, values: frozenset[object]) -> frozenset[object]:
    return frozenset((*values, key))


def _rocq_set_remove(key: object, values: frozenset[object]) -> frozenset[object]:
    return frozenset(value for value in values if value != key)


def _rocq_set_elements(values: frozenset[object]) -> list[object]:
    return sorted(values, key=_rocq_sorted_key)


def _rocq_set_fold(
    function: Callable[[object, object], object],
    values: frozenset[object],
    initial: object,
) -> object:
    result = initial
    for value in _rocq_set_elements(values):
        result = function(value, result)
    return result


def _rocq_string_cons(head: int, tail: str) -> str:
    try:
        return bytes([head]).decode("utf-8") + tail
    except UnicodeDecodeError as exc:
        raise _RocqUtf8BoundaryError(
            "Rocq string split crosses a UTF-8 boundary"
        ) from exc


def _rocq_string_uncons(value: str) -> tuple[int, str]:
    encoded = value.encode("utf-8")
    if not encoded:
        raise _Impossible()
    try:
        tail = encoded[1:].decode("utf-8")
    except UnicodeDecodeError as exc:
        raise _RocqUtf8BoundaryError(
            "Rocq string split crosses a UTF-8 boundary"
        ) from exc
    return encoded[0], tail


def _rocq_ascii_to_int(
    b0: bool,
    b1: bool,
    b2: bool,
    b3: bool,
    b4: bool,
    b5: bool,
    b6: bool,
    b7: bool,
) -> int:
    return sum(
        (1 << i) for i, bit in enumerate((b0, b1, b2, b3, b4, b5, b6, b7)) if bit
    )


def _rocq_ascii_bits(
    value: int,
) -> tuple[bool, bool, bool, bool, bool, bool, bool, bool]:
    if value < 0 or value > 255:
        raise ValueError("Rocq byte/ascii value out of range")
    return cast(
        tuple[bool, bool, bool, bool, bool, bool, bool, bool],
        tuple(bool(value & (1 << i)) for i in range(8)),
    )


class StateT(Generic[_StateTState, _StateTValue]):
    def __init__(
        self,
        step: Callable[[_StateTState], tuple[_StateTValue, _StateTState]],
        state: _StateTState | None = None,
    ) -> None:
        self._step = step
        self.state = state

    def run(self, state: _StateTState) -> _StateTValue:
        value, next_state = self._step(state)
        self.state = next_state
        return value

    def run_with_state(self, state: _StateTState) -> tuple[_StateTValue, _StateTState]:
        result = self._step(state)
        self.state = result[1]
        return result

    def bind(
        self,
        f: Callable[[_StateTValue], StateT[_StateTState, _StateTNext]],
    ) -> StateT[_StateTState, _StateTNext]:
        def run_bound(state: _StateTState) -> tuple[_StateTNext, _StateTState]:
            value, next_state = self._step(state)
            return f(value).run_with_state(next_state)

        return StateT(run_bound, self.state)

    @classmethod
    def pure(cls, value: _StateTValue) -> StateT[_StateTState, _StateTValue]:
        return StateT(lambda state: (value, state))

    @classmethod
    def get_state(cls) -> StateT[_StateTState, _StateTState]:
        return StateT(lambda state: (state, state))

    @classmethod
    def put_state(cls, new_state: _StateTState) -> StateT[_StateTState, None]:
        return StateT(lambda _state: (None, new_state))


class IO(Generic[_IOValue]):
    def __init__(self, thunk: Callable[[], Awaitable[_IOValue]]) -> None:
        self._thunk = thunk

    async def run(self) -> _IOValue:
        return await self._thunk()

    def bind(self, f: Callable[[_IOValue], IO[_IONext]]) -> IO[_IONext]:
        async def run_bound() -> _IONext:
            value = await self.run()
            return await f(value).run()

        return IO(run_bound)

    @classmethod
    def pure(cls, value: _IOValue) -> IO[_IOValue]:
        async def run_pure() -> _IOValue:
            return value

        return IO(run_pure)

    @classmethod
    def from_sync(cls, thunk: Callable[[], _IOValue]) -> IO[_IOValue]:
        async def run_sync() -> _IOValue:
            return thunk()

        return IO(run_sync)


def coforce(value: Callable[[], _CoForceT]) -> _CoForceT:
    return value()


def coprefix_eq(n: int, left: Iterable[object], right: Iterable[object]) -> bool:
    return tuple(islice(iter(left), n)) == tuple(islice(iter(right), n))


def coprefix_hash(n: int, value: Iterable[object]) -> int:
    return hash(tuple(islice(iter(value), n)))


class __ModuleNamespace:
    pass


def __apply_applicative(
    cache: dict[int, _ModuleRetT],
    build: Callable[[_ModuleArgT], _ModuleRetT],
    arg: _ModuleArgT,
) -> _ModuleRetT:
    key = id(arg)
    cached = cache.get(key)
    if cached is None:
        cached = build(arg)
        cache[key] = cached
    return cached


__ = None  # erased logical argument


# bool: remapped to Python primitive
# nat: remapped to Python primitive
_A = TypeVar("_A")


# option: remapped to Python primitive
_A = TypeVar("_A")
_B = TypeVar("_B")


# prod: remapped to Python primitive
_A = TypeVar("_A")


# list: remapped to Python primitive


_LengthT0 = TypeVar("_LengthT0")


def length(x: list[_LengthT0]) -> int:
    def length(l):
        __list = l
        if __list == []:
            return 0
        a = __list[0]
        l_ = __list[1:]
        return length(l_) + 1

    return length(x)


# positive: remapped to Python primitive
# ascii: remapped to Python primitive
# string: remapped to Python primitive


def add_claim(thread: int, claims: frozenset[int]) -> frozenset[int]:
    return _rocq_set_add(_rocq_positive_key(thread), claims)


def remove_claim(thread: int, claims: frozenset[int]) -> frozenset[int]:
    return _rocq_set_remove(_rocq_positive_key(thread), claims)


def has_claim(claims: frozenset[int], thread: int) -> bool:
    return _rocq_positive_key(thread) in claims


def assign_issue(issue: int, owner: str, owners: dict[int, str]) -> dict[int, str]:
    return _rocq_map_add(_rocq_positive_key(issue), owner, owners)


def unassign_issue(issue: int, owners: dict[int, str]) -> dict[int, str]:
    return _rocq_map_remove(_rocq_positive_key(issue), owners)


def issue_owner(owners: dict[int, str], issue: int) -> str | None:
    return owners.get(_rocq_positive_key(issue))


# Python ExtractionDiagnostic [PYEX003]: Type alias declaration is not emitted Remediation: Use a concrete inductive/record or add an extraction remapping for the type.


def repo_provider(repo: repo_entry) -> str:
    __pair = repo
    s = __pair[0]
    p = __pair[1]
    __pair = p
    s0 = __pair[0]
    provider = __pair[1]
    return provider


def repo_providers(repos: list[repo_entry]) -> list[str]:
    __list = repos
    if __list == []:
        return []
    repo = __list[0]
    rest = __list[1:]
    return [repo_provider(repo)] + repo_providers(rest)


def repo_count(repos: list[repo_entry]) -> int:
    return length(repos)
