# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
)


# bool: remapped to Python primitive
# nat: remapped to Python primitive
# option: remapped to Python primitive
# prod: remapped to Python primitive
# list: remapped to Python primitive


_LengthT0 = TypeVar("_LengthT0")


def length(x: list[_LengthT0]) -> int:
    def length0(l):
        __list = l
        if __list == []:
            return 0
        a = __list[0]
        l_ = __list[1:]
        return length0(l_) + 1

    return length0(x)


# positive: remapped to Python primitive
# ascii: remapped to Python primitive
# string: remapped to Python primitive


def add_claim(
    thread: int,
    claims: frozenset[int],
) -> frozenset[int]:
    return _rocq_set_add(_rocq_positive_key(thread), claims)


def remove_claim(
    thread: int,
    claims: frozenset[int],
) -> frozenset[int]:
    return _rocq_set_remove(
        _rocq_positive_key(thread),
        claims,
    )


def has_claim(
    claims: frozenset[int],
    thread: int,
) -> bool:
    return _rocq_positive_key(thread) in claims


def assign_issue(
    issue: int,
    owner: str,
    owners: dict[int, str],
) -> dict[int, str]:
    return _rocq_map_add(
        _rocq_positive_key(issue),
        owner,
        owners,
    )


def unassign_issue(
    issue: int,
    owners: dict[int, str],
) -> dict[int, str]:
    return _rocq_map_remove(
        _rocq_positive_key(issue),
        owners,
    )


def issue_owner(
    owners: dict[int, str],
    issue: int,
) -> str | None:
    return owners.get(_rocq_positive_key(issue))


# Python ExtractionDiagnostic [PYEX003]: Type alias declaration is not emitted Remediation: Use a concrete inductive/record or add an extraction remapping for the type.


def repo_provider(repo: repo_entry) -> str:
    __pair = repo
    s = __pair[0]
    p = __pair[1]
    __pair = p
    s0 = __pair[0]
    provider = __pair[1]
    return provider


def repo_providers(repos: list[repo_entry]) -> list[str]:
    __list = repos
    if __list == []:
        return []
    repo = __list[0]
    rest = __list[1:]
    return [repo_provider(repo)] + repo_providers(rest)


def repo_count(repos: list[repo_entry]) -> int:
    return length(repos)


@dataclass(frozen=True)
class CoordIndex:
    coord_claims: frozenset[int]
    coord_issue_owners: dict[int, str]
    coord_repos: list[repo_entry]

    def add_claim(
        self,
        thread: int,
    ) -> CoordIndex:
        index = self
        return CoordIndex(
            coord_claims=add_claim(thread, coord_claims(index)),
            coord_issue_owners=coord_issue_owners(index),
            coord_repos=coord_repos(index),
        )

    def remove_claim(
        self,
        thread: int,
    ) -> CoordIndex:
        index = self
        return CoordIndex(
            coord_claims=remove_claim(thread, coord_claims(index)),
            coord_issue_owners=coord_issue_owners(index),
            coord_repos=coord_repos(index),
        )

    def has_claim(
        self,
        thread: int,
    ) -> bool:
        index = self
        return has_claim(coord_claims(index), thread)

    def assign_issue(
        self,
        issue: int,
        owner: str,
    ) -> CoordIndex:
        index = self
        return CoordIndex(
            coord_claims=coord_claims(index),
            coord_issue_owners=assign_issue(
                issue,
                owner,
                coord_issue_owners(index),
            ),
            coord_repos=coord_repos(index),
        )

    def unassign_issue(
        self,
        issue: int,
    ) -> CoordIndex:
        index = self
        return CoordIndex(
            coord_claims=coord_claims(index),
            coord_issue_owners=unassign_issue(issue, coord_issue_owners(index)),
            coord_repos=coord_repos(index),
        )

    def issue_owner(
        self,
        issue: int,
    ) -> str | None:
        index = self
        return issue_owner(coord_issue_owners(index), issue)

    def repo_providers(self) -> list[str]:
        index = self
        return repo_providers(coord_repos(index))

    def repo_count(self) -> int:
        index = self
        return repo_count(coord_repos(index))


def coord_claims(c: CoordIndex) -> frozenset[int]:
    return c.coord_claims


def coord_issue_owners(c: CoordIndex) -> dict[int, str]:
    return c.coord_issue_owners


def coord_repos(c: CoordIndex) -> list[repo_entry]:
    return c.coord_repos


empty_coord_index: CoordIndex = CoordIndex(
    coord_claims=frozenset(),
    coord_issue_owners={},
    coord_repos=[],
)
