# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass, replace
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
    final,
)


class State:
    pass


@final
@dataclass(frozen=True)
class Empty(State):
    pass


@final
@dataclass(frozen=True)
class NonEmpty(State):
    pass


StateT = Empty | NonEmpty


class Event:
    pass


@final
@dataclass(frozen=True)
class WebhookArrives(Event):
    pass


@final
@dataclass(frozen=True)
class HandlerDone(Event):
    pass


@final
@dataclass(frozen=True)
class WorkerTurnStart(Event):
    pass


EventT = WebhookArrives | HandlerDone | WorkerTurnStart


def transition(
    current: State,
    event0: Event,
) -> State | None:
    match current:
        case Empty():
            match event0:
                case WebhookArrives():
                    return NonEmpty()
                case HandlerDone():
                    return None
                case WorkerTurnStart():
                    return Empty()
                case __impossible:
                    assert_never(__impossible)
        case NonEmpty():
            match event0:
                case WebhookArrives():
                    return NonEmpty()
                case HandlerDone():
                    return NonEmpty()
                case WorkerTurnStart():
                    return None
                case __impossible:
                    assert_never(__impossible)
        case __impossible:
            assert_never(__impossible)
