# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass, replace
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
    final,
)


class CommitResult:
    pass


@final
@dataclass(frozen=True)
class CommitSuccess(CommitResult):
    sha: str


@final
@dataclass(frozen=True)
class CommitHookFailure(CommitResult):
    output: str


@final
@dataclass(frozen=True)
class CommitNothingStaged(CommitResult):
    pass


@final
@dataclass(frozen=True)
class CommitSkipped(CommitResult):
    reason: str


CommitResultT = CommitSuccess | CommitHookFailure | CommitNothingStaged | CommitSkipped


class NudgeKind:
    pass


@final
@dataclass(frozen=True)
class NudgeMissingSentinel(NudgeKind):
    pass


@final
@dataclass(frozen=True)
class NudgeNothingStaged(NudgeKind):
    pass


@final
@dataclass(frozen=True)
class NudgeHookFailure(NudgeKind):
    pass


NudgeKindT = NudgeMissingSentinel | NudgeNothingStaged | NudgeHookFailure


def commit_result_nudge(r: CommitResult) -> NudgeKind | None:
    match r:
        case CommitSuccess(sha):
            return None
        case CommitHookFailure(output):
            return NudgeHookFailure()
        case CommitNothingStaged():
            return NudgeNothingStaged()
        case CommitSkipped(reason):
            return None
        case __impossible:
            assert_never(__impossible)
