# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
)


# bool: remapped to Python primitive
# byte: remapped to Python primitive
# ascii: remapped to Python primitive
# string: remapped to Python primitive


event_name: str = "pull_request"


event_name_bytes: bytes = b"pull_request"


newline_byte: int = 10


def first_char_or_newline(s: str) -> str:
    __s = s
    if __s == "":
        return "\n"
    c = __s[0]
    s0 = __s[1:]
    return c
