# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
)


class TaskKind:
    pass


@dataclass(frozen=True)
class TaskCI(TaskKind):
    pass


@dataclass(frozen=True)
class TaskThread(TaskKind):
    pass


@dataclass(frozen=True)
class TaskSpec(TaskKind):
    pass


@dataclass(frozen=True)
class TaskAsk(TaskKind):
    pass


@dataclass(frozen=True)
class TaskDefer(TaskKind):
    pass


TaskKindT = TaskCI | TaskThread | TaskSpec | TaskAsk | TaskDefer


class TaskStatus:
    pass


@dataclass(frozen=True)
class StatusPending(TaskStatus):
    pass


@dataclass(frozen=True)
class StatusCompleted(TaskStatus):
    pass


@dataclass(frozen=True)
class StatusBlocked(TaskStatus):
    pass


TaskStatusT = StatusPending | StatusCompleted | StatusBlocked


@dataclass(frozen=True)
class TaskRow:
    title: str
    description: str
    kind: TaskKind
    status: TaskStatus
    source_comment: int | None


class RescopeOp:
    pass


@dataclass(frozen=True)
class KeepTask(RescopeOp):
    task: int


@dataclass(frozen=True)
class RewriteTask(RescopeOp):
    task: int
    new_title: str
    new_description: str


@dataclass(frozen=True)
class CompleteTask(RescopeOp):
    task: int


RescopeOpT = KeepTask | RewriteTask | CompleteTask


def task_kind_is_ci(kind0: TaskKind) -> bool:
    match kind0:
        case TaskCI():
            return True
        case TaskThread():
            return False
        case TaskSpec():
            return False
        case TaskAsk():
            return False
        case TaskDefer():
            return False
        case __impossible:
            assert_never(__impossible)


def positive_mem(
    target: int,
    items: list[int],
) -> bool:
    __list = items
    if __list == []:
        return False
    item = __list[0]
    rest = __list[1:]
    if target == item:
        return True
    return positive_mem(target, rest)


def find_comment_duplicate(
    comment: int,
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    __list = order
    if __list == []:
        return None
    task = __list[0]
    rest = __list[1:]
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return find_comment_duplicate(
            comment,
            rest,
            rows,
        )
    row = __option
    __option = row.source_comment
    if __option is None:
        return find_comment_duplicate(
            comment,
            rest,
            rows,
        )
    existing = __option
    if existing == comment:
        return task
    return find_comment_duplicate(
        comment,
        rest,
        rows,
    )


def row_has_pending_title(
    candidate_title: str,
    row: TaskRow,
) -> bool:
    match row.status:
        case StatusPending():
            return row.title == candidate_title
        case StatusCompleted():
            return False
        case StatusBlocked():
            return False
        case __impossible:
            assert_never(__impossible)


def task_has_pending_title(
    candidate_title: str,
    task: int,
    rows: dict[int, TaskRow],
) -> bool:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return False
    row = __option
    return row_has_pending_title(candidate_title, row)


def find_pending_title_duplicate(
    candidate_title: str,
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    __list = order
    if __list == []:
        return None
    task = __list[0]
    rest = __list[1:]
    if task_has_pending_title(candidate_title, task, rows):
        return task
    return find_pending_title_duplicate(
        candidate_title,
        rest,
        rows,
    )


def enqueue_task(
    task: int,
    row: TaskRow,
    order: list[int],
    rows: dict[int, TaskRow],
) -> tuple[tuple[list[int], dict[int, TaskRow]], int]:
    __option = row.source_comment
    if __option is None:
        __option = find_pending_title_duplicate(row.title, order, rows)
        if __option is None:
            return (
                (
                    order + [task] + [],
                    _rocq_map_add(
                        _rocq_positive_key(task),
                        row,
                        rows,
                    ),
                ),
                task,
            )
        existing = __option
        return (
            (
                order,
                rows,
            ),
            existing,
        )
    comment = __option
    __option = find_comment_duplicate(comment, order, rows)
    if __option is None:
        return (
            (
                order + [task] + [],
                _rocq_map_add(
                    _rocq_positive_key(task),
                    row,
                    rows,
                ),
            ),
            task,
        )
    existing = __option
    return (
        (
            order,
            rows,
        ),
        existing,
    )


def row_with_status(
    row: TaskRow,
    new_status: TaskStatus,
) -> TaskRow:
    return TaskRow(
        title=row.title,
        description=row.description,
        kind=row.kind,
        status=new_status,
        source_comment=row.source_comment,
    )


def rescope_task_id(op: RescopeOp) -> int:
    match op:
        case KeepTask(task):
            return task
        case RewriteTask(task, new_title, new_description):
            return task
        case CompleteTask(task):
            return task
        case __impossible:
            assert_never(__impossible)


def apply_rescope_ops(
    ops: list[RescopeOp],
    rows: dict[int, TaskRow],
    pending_ids: list[int],
    completed_ids: list[int],
) -> tuple[tuple[dict[int, TaskRow], list[int]], list[int]]:
    __list = ops
    if __list == []:
        return (
            (
                rows,
                pending_ids,
            ),
            completed_ids,
        )
    op = __list[0]
    rest = __list[1:]
    task = rescope_task_id(op)
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return apply_rescope_ops(
            rest,
            rows,
            pending_ids,
            completed_ids,
        )
    row = __option
    match op:
        case KeepTask(task0):
            match row.status:
                case StatusPending():
                    return apply_rescope_ops(
                        rest,
                        rows,
                        pending_ids + [task] + [],
                        completed_ids,
                    )
                case StatusCompleted():
                    return apply_rescope_ops(
                        rest,
                        rows,
                        pending_ids,
                        completed_ids,
                    )
                case StatusBlocked():
                    return apply_rescope_ops(
                        rest,
                        rows,
                        pending_ids + [task] + [],
                        completed_ids,
                    )
                case __impossible:
                    assert_never(__impossible)
        case RewriteTask(task0, new_title, new_description):
            match row.status:
                case StatusPending():
                    row_ = TaskRow(
                        title=row.title,
                        description=new_description,
                        kind=row.kind,
                        status=row.status,
                        source_comment=row.source_comment,
                    )
                    return apply_rescope_ops(
                        rest,
                        _rocq_map_add(
                            _rocq_positive_key(task),
                            row_,
                            rows,
                        ),
                        pending_ids + [task] + [],
                        completed_ids,
                    )
                case StatusCompleted():
                    return apply_rescope_ops(
                        rest,
                        rows,
                        pending_ids,
                        completed_ids,
                    )
                case StatusBlocked():
                    row_ = TaskRow(
                        title=row.title,
                        description=new_description,
                        kind=row.kind,
                        status=row.status,
                        source_comment=row.source_comment,
                    )
                    return apply_rescope_ops(
                        rest,
                        _rocq_map_add(
                            _rocq_positive_key(task),
                            row_,
                            rows,
                        ),
                        pending_ids + [task] + [],
                        completed_ids,
                    )
                case __impossible:
                    assert_never(__impossible)
        case CompleteTask(task0):
            match row.status:
                case StatusPending():
                    row_ = TaskRow(
                        title=row.title,
                        description=row.description,
                        kind=row.kind,
                        status=StatusCompleted(),
                        source_comment=row.source_comment,
                    )
                    return apply_rescope_ops(
                        rest,
                        _rocq_map_add(
                            _rocq_positive_key(task),
                            row_,
                            rows,
                        ),
                        pending_ids,
                        completed_ids + [task] + [],
                    )
                case StatusCompleted():
                    return apply_rescope_ops(
                        rest,
                        rows,
                        pending_ids,
                        completed_ids,
                    )
                case StatusBlocked():
                    row_ = TaskRow(
                        title=row.title,
                        description=row.description,
                        kind=row.kind,
                        status=StatusCompleted(),
                        source_comment=row.source_comment,
                    )
                    return apply_rescope_ops(
                        rest,
                        _rocq_map_add(
                            _rocq_positive_key(task),
                            row_,
                            rows,
                        ),
                        pending_ids,
                        completed_ids + [task] + [],
                    )
                case __impossible:
                    assert_never(__impossible)
        case __impossible:
            assert_never(__impossible)


def completed_tasks_in_order(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    __list = order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return completed_tasks_in_order(rest, rows)
    row = __option
    match row.status:
        case StatusPending():
            return completed_tasks_in_order(rest, rows)
        case StatusCompleted():
            return [task] + completed_tasks_in_order(rest, rows)
        case StatusBlocked():
            return completed_tasks_in_order(rest, rows)
        case __impossible:
            assert_never(__impossible)


def preserve_newly_added(
    snapshot_order: list[int],
    current_order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    __list = current_order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    rest_ = preserve_newly_added(
        snapshot_order,
        rest,
        rows,
    )
    if positive_mem(task, snapshot_order):
        return rest_
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return rest_
    row = __option
    match row.status:
        case StatusPending():
            return [task] + rest_
        case StatusCompleted():
            return rest_
        case StatusBlocked():
            return [task] + rest_
        case __impossible:
            assert_never(__impossible)


def task_is_ci(
    rows: dict[int, TaskRow],
    task: int,
) -> bool:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return False
    row = __option
    return task_kind_is_ci(row.kind)


def collect_ci_tasks(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    __list = order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    rest_ = collect_ci_tasks(rest, rows)
    if task_is_ci(rows, task):
        return [task] + rest_
    return rest_


def collect_non_ci_tasks(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    __list = order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    rest_ = collect_non_ci_tasks(rest, rows)
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return rest_
    row = __option
    if not task_kind_is_ci(row.kind):
        return [task] + rest_
    return rest_


def stable_ci_first(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    ci = collect_ci_tasks(order, rows)
    non_ci = collect_non_ci_tasks(order, rows)
    return ci + non_ci


def apply_rescope(
    snapshot_order: list[int],
    current_order: list[int],
    rows: dict[int, TaskRow],
    ops: list[RescopeOp],
) -> tuple[list[int], dict[int, TaskRow]]:
    __pair = apply_rescope_ops(ops, rows, [], [])
    p = __pair[0]
    newly_completed = __pair[1]
    __pair = p
    rows_ = __pair[0]
    pending_ids = __pair[1]
    completed_existing = completed_tasks_in_order(current_order, rows)
    newly_added = preserve_newly_added(
        snapshot_order,
        current_order,
        rows_,
    )
    pending_order = stable_ci_first(pending_ids, rows_)
    return (
        pending_order + completed_existing + newly_completed + newly_added,
        rows_,
    )


def complete_task_visible(
    task: int,
    rows: dict[int, TaskRow],
) -> tuple[dict[int, TaskRow], int | None]:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return (
            rows,
            None,
        )
    row = __option
    match row.status:
        case StatusPending():
            row_ = row_with_status(row, StatusCompleted())
            return (
                _rocq_map_add(
                    _rocq_positive_key(task),
                    row_,
                    rows,
                ),
                row.source_comment,
            )
        case StatusCompleted():
            return (
                rows,
                None,
            )
        case StatusBlocked():
            row_ = row_with_status(row, StatusCompleted())
            return (
                _rocq_map_add(
                    _rocq_positive_key(task),
                    row_,
                    rows,
                ),
                row.source_comment,
            )
        case __impossible:
            assert_never(__impossible)


model_version: int = 0


@dataclass(frozen=True)
class TaskStore:
    task_store_order: list[int]
    task_store_rows: dict[int, TaskRow]


class PRBodyStatus:
    pass


@dataclass(frozen=True)
class PRPending(PRBodyStatus):
    pass


@dataclass(frozen=True)
class PRCompleted(PRBodyStatus):
    pass


PRBodyStatusT = PRPending | PRCompleted


@dataclass(frozen=True)
class PRBodyRow:
    pr_body_task: int
    pr_body_title: str
    pr_body_description: str
    pr_body_kind: TaskKind
    pr_body_status: PRBodyStatus


def task_kind_matches_ci_filter(
    include_ci: bool,
    kind0: TaskKind,
) -> bool:
    if include_ci:
        return task_kind_is_ci(kind0)
    return not task_kind_is_ci(kind0)


def pending_projection(
    include_ci: bool,
    task: int,
    rows: dict[int, TaskRow],
) -> list[PRBodyRow]:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return []
    row = __option
    match row.status:
        case StatusPending():
            if task_kind_matches_ci_filter(include_ci, row.kind):
                return [
                    PRBodyRow(
                        pr_body_task=task,
                        pr_body_title=row.title,
                        pr_body_description=row.description,
                        pr_body_kind=row.kind,
                        pr_body_status=PRPending(),
                    ),
                ] + []
            return []
        case StatusCompleted():
            return []
        case StatusBlocked():
            return []
        case __impossible:
            assert_never(__impossible)


def completed_projection(
    task: int,
    rows: dict[int, TaskRow],
) -> list[PRBodyRow]:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return []
    row = __option
    match row.status:
        case StatusPending():
            return []
        case StatusCompleted():
            return [
                PRBodyRow(
                    pr_body_task=task,
                    pr_body_title=row.title,
                    pr_body_description=row.description,
                    pr_body_kind=row.kind,
                    pr_body_status=PRCompleted(),
                ),
            ] + []
        case StatusBlocked():
            return []
        case __impossible:
            assert_never(__impossible)


def project_pending(
    include_ci: bool,
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[PRBodyRow]:
    __list = order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    current = pending_projection(
        include_ci,
        task,
        rows,
    )
    remaining = project_pending(
        include_ci,
        rest,
        rows,
    )
    return current + remaining


def project_completed(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[PRBodyRow]:
    __list = order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    return completed_projection(task, rows) + project_completed(rest, rows)


def project_task_store(store: TaskStore) -> list[PRBodyRow]:
    order = store.task_store_order
    rows = store.task_store_rows
    pending_ci = project_pending(
        True,
        order,
        rows,
    )
    pending_non_ci = project_pending(
        False,
        order,
        rows,
    )
    completed = project_completed(order, rows)
    return pending_ci + pending_non_ci + completed


def task_kind_eqb(
    left: TaskKind,
    right: TaskKind,
) -> bool:
    match left:
        case TaskCI():
            match right:
                case TaskCI():
                    return True
                case TaskThread():
                    return False
                case TaskSpec():
                    return False
                case TaskAsk():
                    return False
                case TaskDefer():
                    return False
                case __impossible:
                    assert_never(__impossible)
        case TaskThread():
            match right:
                case TaskCI():
                    return False
                case TaskThread():
                    return True
                case TaskSpec():
                    return False
                case TaskAsk():
                    return False
                case TaskDefer():
                    return False
                case __impossible:
                    assert_never(__impossible)
        case TaskSpec():
            match right:
                case TaskCI():
                    return False
                case TaskThread():
                    return False
                case TaskSpec():
                    return True
                case TaskAsk():
                    return False
                case TaskDefer():
                    return False
                case __impossible:
                    assert_never(__impossible)
        case TaskAsk():
            match right:
                case TaskCI():
                    return False
                case TaskThread():
                    return False
                case TaskSpec():
                    return False
                case TaskAsk():
                    return True
                case TaskDefer():
                    return False
                case __impossible:
                    assert_never(__impossible)
        case TaskDefer():
            match right:
                case TaskCI():
                    return False
                case TaskThread():
                    return False
                case TaskSpec():
                    return False
                case TaskAsk():
                    return False
                case TaskDefer():
                    return True
                case __impossible:
                    assert_never(__impossible)
        case __impossible:
            assert_never(__impossible)


def pr_body_status_eqb(
    left: PRBodyStatus,
    right: PRBodyStatus,
) -> bool:
    match left:
        case PRPending():
            match right:
                case PRPending():
                    return True
                case PRCompleted():
                    return False
                case __impossible:
                    assert_never(__impossible)
        case PRCompleted():
            match right:
                case PRPending():
                    return False
                case PRCompleted():
                    return True
                case __impossible:
                    assert_never(__impossible)
        case __impossible:
            assert_never(__impossible)


pr_body_row_eqb = __import__("operator").eq


def pr_body_eqb(
    left: list[PRBodyRow],
    right: list[PRBodyRow],
) -> bool:
    __list = left
    if __list == []:
        __list = right
        if __list == []:
            return True
        p = __list[0]
        l = __list[1:]
        return False
    left_row = __list[0]
    left_rest = __list[1:]
    __list = right
    if __list == []:
        return False
    right_row = __list[0]
    right_rest = __list[1:]
    return pr_body_row_eqb(left_row, right_row) and pr_body_eqb(left_rest, right_rest)


@dataclass(frozen=True)
class SystemState:
    durable_task_store: TaskStore
    visible_pr_body: list[PRBodyRow]


def pr_body_matches_store_bool(state: SystemState) -> bool:
    visible = state.visible_pr_body
    projected = project_task_store(state.durable_task_store)
    return pr_body_eqb(visible, projected)


def synced_state(store: TaskStore) -> SystemState:
    return SystemState(
        durable_task_store=store,
        visible_pr_body=project_task_store(store),
    )


class TaskWrite:
    pass


@dataclass(frozen=True)
class WriteTaskAdd(TaskWrite):
    task: int
    row: TaskRow


@dataclass(frozen=True)
class WriteTaskComplete(TaskWrite):
    task: int


@dataclass(frozen=True)
class WriteTaskRescope(TaskWrite):
    snapshot_order: list[int]
    ops: list[RescopeOp]


TaskWriteT = WriteTaskAdd | WriteTaskComplete | WriteTaskRescope


def apply_task_write(
    write: TaskWrite,
    store: TaskStore,
) -> TaskStore:
    match write:
        case WriteTaskAdd(task, row):
            order = store.task_store_order
            rows = store.task_store_rows
            __pair = enqueue_task(task, row, order, rows)
            p = __pair[0]
            p0 = __pair[1]
            __pair = p
            order_ = __pair[0]
            rows_ = __pair[1]
            return TaskStore(
                task_store_order=order_,
                task_store_rows=rows_,
            )
        case WriteTaskComplete(task):
            __pair = complete_task_visible(task, store.task_store_rows)
            rows_ = __pair[0]
            o = __pair[1]
            return TaskStore(
                task_store_order=store.task_store_order,
                task_store_rows=rows_,
            )
        case WriteTaskRescope(snapshot_order, ops):
            order = store.task_store_order
            rows = store.task_store_rows
            __pair = apply_rescope(snapshot_order, order, rows, ops)
            order_ = __pair[0]
            rows_ = __pair[1]
            return TaskStore(
                task_store_order=order_,
                task_store_rows=rows_,
            )
        case __impossible:
            assert_never(__impossible)


def transition(
    state: SystemState,
    write: TaskWrite,
) -> SystemState | None:
    if pr_body_matches_store_bool(state):
        return synced_state(apply_task_write(write, state.durable_task_store))
    return None
