# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
)


# bool: remapped to Python primitive
# nat: remapped to Python primitive
# option: remapped to Python primitive
# prod: remapped to Python primitive
# list: remapped to Python primitive
# positive: remapped to Python primitive
# ascii: remapped to Python primitive
# string: remapped to Python primitive


class TaskKind:
    pass


@dataclass(frozen=True)
class TaskCI(TaskKind):
    pass


@dataclass(frozen=True)
class TaskThread(TaskKind):
    pass


@dataclass(frozen=True)
class TaskSpec(TaskKind):
    pass


@dataclass(frozen=True)
class TaskAsk(TaskKind):
    pass


@dataclass(frozen=True)
class TaskDefer(TaskKind):
    pass


TaskKindT = TaskCI | TaskThread | TaskSpec | TaskAsk | TaskDefer


class TaskStatus:
    pass


@dataclass(frozen=True)
class StatusPending(TaskStatus):
    pass


@dataclass(frozen=True)
class StatusCompleted(TaskStatus):
    pass


@dataclass(frozen=True)
class StatusBlocked(TaskStatus):
    pass


TaskStatusT = StatusPending | StatusCompleted | StatusBlocked


@dataclass(frozen=True)
class TaskRow:
    task_title: str
    task_description: str
    task_kind: TaskKind
    task_status: TaskStatus
    task_source_comment: int | None


def task_title(t0: TaskRow) -> str:
    return t0.task_title


def task_description(t0: TaskRow) -> str:
    return t0.task_description


def task_kind(t0: TaskRow) -> TaskKind:
    return t0.task_kind


def task_status(t0: TaskRow) -> TaskStatus:
    return t0.task_status


def task_source_comment(t0: TaskRow) -> int | None:
    return t0.task_source_comment


class RescopeOp:
    pass


@dataclass(frozen=True)
class KeepTask(RescopeOp):
    task: int


@dataclass(frozen=True)
class RewriteTask(RescopeOp):
    task: int
    new_title: str
    new_description: str


@dataclass(frozen=True)
class CompleteTask(RescopeOp):
    task: int


RescopeOpT = KeepTask | RewriteTask | CompleteTask


def task_kind_is_ci(kind: TaskKind) -> bool:
    match kind:
        case TaskCI():
            return True
        case TaskThread():
            return False
        case TaskSpec():
            return False
        case TaskAsk():
            return False
        case TaskDefer():
            return False
        case __impossible:
            assert_never(__impossible)


def task_kind_is_non_ci(kind: TaskKind) -> bool:
    return not (task_kind_is_ci(kind))


def positive_eqb(
    left: int,
    right: int,
) -> bool:
    return left == right


def positive_mem(
    target: int,
    items: list[int],
) -> bool:
    __list = items
    if __list == []:
        return False
    item = __list[0]
    rest = __list[1:]
    if positive_eqb(target, item):
        return True
    return positive_mem(target, rest)


def find_comment_duplicate(
    comment: int,
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    __list = order
    if __list == []:
        return None
    task = __list[0]
    rest = __list[1:]
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return find_comment_duplicate(
            comment,
            rest,
            rows,
        )
    row = __option
    __option = task_source_comment(row)
    if __option is None:
        return find_comment_duplicate(
            comment,
            rest,
            rows,
        )
    existing = __option
    if positive_eqb(existing, comment):
        return task
    return find_comment_duplicate(
        comment,
        rest,
        rows,
    )


def find_pending_title_duplicate(
    title: str,
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    __list = order
    if __list == []:
        return None
    task = __list[0]
    rest = __list[1:]
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return find_pending_title_duplicate(
            title,
            rest,
            rows,
        )
    row = __option
    match task_status(row):
        case StatusPending():
            if task_title(row) == title:
                return task
            return find_pending_title_duplicate(
                title,
                rest,
                rows,
            )
        case StatusCompleted():
            return find_pending_title_duplicate(
                title,
                rest,
                rows,
            )
        case StatusBlocked():
            return find_pending_title_duplicate(
                title,
                rest,
                rows,
            )
        case __impossible:
            assert_never(__impossible)


def enqueue_task(
    task: int,
    row: TaskRow,
    order: list[int],
    rows: dict[int, TaskRow],
) -> tuple[tuple[list[int], dict[int, TaskRow]], int]:
    __option = task_source_comment(row)
    if __option is None:
        __option = find_pending_title_duplicate(task_title(row), order, rows)
        if __option is None:
            return (
                (
                    order + [task] + [],
                    _rocq_map_add(
                        _rocq_positive_key(task),
                        row,
                        rows,
                    ),
                ),
                task,
            )
        existing = __option
        return (
            (
                order,
                rows,
            ),
            existing,
        )
    comment = __option
    __option = find_comment_duplicate(comment, order, rows)
    if __option is None:
        return (
            (
                order + [task] + [],
                _rocq_map_add(
                    _rocq_positive_key(task),
                    row,
                    rows,
                ),
            ),
            task,
        )
    existing = __option
    return (
        (
            order,
            rows,
        ),
        existing,
    )


def row_with_status(
    row: TaskRow,
    status: TaskStatus,
) -> TaskRow:
    return TaskRow(
        task_title=task_title(row),
        task_description=task_description(row),
        task_kind=task_kind(row),
        task_status=status,
        task_source_comment=task_source_comment(row),
    )


def rescope_task_id(op: RescopeOp) -> int:
    match op:
        case KeepTask(task):
            return task
        case RewriteTask(task, new_title, new_description):
            return task
        case CompleteTask(task):
            return task
        case __impossible:
            assert_never(__impossible)


def apply_rescope_ops(
    ops: list[RescopeOp],
    rows: dict[int, TaskRow],
    pending_ids: list[int],
    completed_ids: list[int],
) -> tuple[tuple[dict[int, TaskRow], list[int]], list[int]]:
    __list = ops
    if __list == []:
        return (
            (
                rows,
                pending_ids,
            ),
            completed_ids,
        )
    op = __list[0]
    rest = __list[1:]
    task = rescope_task_id(op)
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return apply_rescope_ops(
            rest,
            rows,
            pending_ids,
            completed_ids,
        )
    row = __option
    match op:
        case KeepTask(task0):
            match task_status(row):
                case StatusPending():
                    return apply_rescope_ops(
                        rest,
                        rows,
                        pending_ids + [task] + [],
                        completed_ids,
                    )
                case StatusCompleted():
                    return apply_rescope_ops(
                        rest,
                        rows,
                        pending_ids,
                        completed_ids,
                    )
                case StatusBlocked():
                    return apply_rescope_ops(
                        rest,
                        rows,
                        pending_ids + [task] + [],
                        completed_ids,
                    )
                case __impossible:
                    assert_never(__impossible)
        case RewriteTask(task0, title, description):
            match task_status(row):
                case StatusPending():
                    row_ = TaskRow(
                        task_title=title,
                        task_description=description,
                        task_kind=task_kind(row),
                        task_status=task_status(row),
                        task_source_comment=task_source_comment(row),
                    )
                    return apply_rescope_ops(
                        rest,
                        _rocq_map_add(
                            _rocq_positive_key(task),
                            row_,
                            rows,
                        ),
                        pending_ids + [task] + [],
                        completed_ids,
                    )
                case StatusCompleted():
                    return apply_rescope_ops(
                        rest,
                        rows,
                        pending_ids,
                        completed_ids,
                    )
                case StatusBlocked():
                    row_ = TaskRow(
                        task_title=title,
                        task_description=description,
                        task_kind=task_kind(row),
                        task_status=task_status(row),
                        task_source_comment=task_source_comment(row),
                    )
                    return apply_rescope_ops(
                        rest,
                        _rocq_map_add(
                            _rocq_positive_key(task),
                            row_,
                            rows,
                        ),
                        pending_ids + [task] + [],
                        completed_ids,
                    )
                case __impossible:
                    assert_never(__impossible)
        case CompleteTask(task0):
            match task_status(row):
                case StatusPending():
                    row_ = TaskRow(
                        task_title=task_title(row),
                        task_description=task_description(row),
                        task_kind=task_kind(row),
                        task_status=StatusCompleted(),
                        task_source_comment=task_source_comment(row),
                    )
                    return apply_rescope_ops(
                        rest,
                        _rocq_map_add(
                            _rocq_positive_key(task),
                            row_,
                            rows,
                        ),
                        pending_ids,
                        completed_ids + [task] + [],
                    )
                case StatusCompleted():
                    return apply_rescope_ops(
                        rest,
                        rows,
                        pending_ids,
                        completed_ids,
                    )
                case StatusBlocked():
                    row_ = TaskRow(
                        task_title=task_title(row),
                        task_description=task_description(row),
                        task_kind=task_kind(row),
                        task_status=StatusCompleted(),
                        task_source_comment=task_source_comment(row),
                    )
                    return apply_rescope_ops(
                        rest,
                        _rocq_map_add(
                            _rocq_positive_key(task),
                            row_,
                            rows,
                        ),
                        pending_ids,
                        completed_ids + [task] + [],
                    )
                case __impossible:
                    assert_never(__impossible)
        case __impossible:
            assert_never(__impossible)


def completed_tasks_in_order(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    __list = order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return completed_tasks_in_order(rest, rows)
    row = __option
    match task_status(row):
        case StatusPending():
            return completed_tasks_in_order(rest, rows)
        case StatusCompleted():
            return [task] + completed_tasks_in_order(rest, rows)
        case StatusBlocked():
            return completed_tasks_in_order(rest, rows)
        case __impossible:
            assert_never(__impossible)


def preserve_newly_added(
    snapshot_order: list[int],
    current_order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    __list = current_order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    rest_ = preserve_newly_added(
        snapshot_order,
        rest,
        rows,
    )
    if positive_mem(task, snapshot_order):
        return rest_
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return rest_
    row = __option
    match task_status(row):
        case StatusPending():
            return [task] + rest_
        case StatusCompleted():
            return rest_
        case StatusBlocked():
            return [task] + rest_
        case __impossible:
            assert_never(__impossible)


def task_is_ci(
    rows: dict[int, TaskRow],
    task: int,
) -> bool:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return False
    row = __option
    return task_kind_is_ci(task_kind(row))


def task_is_non_ci(
    rows: dict[int, TaskRow],
    task: int,
) -> bool:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return False
    row = __option
    return task_kind_is_non_ci(task_kind(row))


def collect_ci_tasks(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    __list = order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    rest_ = collect_ci_tasks(rest, rows)
    if task_is_ci(rows, task):
        return [task] + rest_
    return rest_


def collect_non_ci_tasks(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    __list = order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    rest_ = collect_non_ci_tasks(rest, rows)
    if task_is_non_ci(rows, task):
        return [task] + rest_
    return rest_


def stable_ci_first(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    ci = collect_ci_tasks(order, rows)
    non_ci = collect_non_ci_tasks(order, rows)
    return ci + non_ci


def apply_rescope(
    snapshot_order: list[int],
    current_order: list[int],
    rows: dict[int, TaskRow],
    ops: list[RescopeOp],
) -> tuple[list[int], dict[int, TaskRow]]:
    __pair = apply_rescope_ops(ops, rows, [], [])
    p = __pair[0]
    newly_completed = __pair[1]
    __pair = p
    rows_ = __pair[0]
    pending_ids = __pair[1]
    completed_existing = completed_tasks_in_order(current_order, rows)
    newly_added = preserve_newly_added(
        snapshot_order,
        current_order,
        rows_,
    )
    pending_order = stable_ci_first(pending_ids, rows_)
    return (
        pending_order + completed_existing + newly_completed + newly_added,
        rows_,
    )


def complete_task_visible(
    task: int,
    rows: dict[int, TaskRow],
) -> tuple[dict[int, TaskRow], int | None]:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return (
            rows,
            None,
        )
    row = __option
    match task_status(row):
        case StatusPending():
            row_ = row_with_status(row, StatusCompleted())
            return (
                _rocq_map_add(
                    _rocq_positive_key(task),
                    row_,
                    rows,
                ),
                task_source_comment(row),
            )
        case StatusCompleted():
            return (
                rows,
                None,
            )
        case StatusBlocked():
            row_ = row_with_status(row, StatusCompleted())
            return (
                _rocq_map_add(
                    _rocq_positive_key(task),
                    row_,
                    rows,
                ),
                task_source_comment(row),
            )
        case __impossible:
            assert_never(__impossible)


model_version: int = 0


@dataclass(frozen=True)
class TaskStore:
    task_store_order: list[int]
    task_store_rows: dict[int, TaskRow]


def task_store_order(t0: TaskStore) -> list[int]:
    return t0.task_store_order


def task_store_rows(t0: TaskStore) -> dict[int, TaskRow]:
    return t0.task_store_rows


class PRBodyStatus:
    pass


@dataclass(frozen=True)
class PRPending(PRBodyStatus):
    pass


@dataclass(frozen=True)
class PRCompleted(PRBodyStatus):
    pass


PRBodyStatusT = PRPending | PRCompleted


@dataclass(frozen=True)
class PRBodyRow:
    pr_body_task: int
    pr_body_title: str
    pr_body_description: str
    pr_body_kind: TaskKind
    pr_body_status: PRBodyStatus

    def body_row_eqb(
        self,
        right: PRBodyRow,
    ) -> bool:
        left = self
        same_task = positive_eqb(pr_body_task(left), pr_body_task(right))
        same_title = pr_body_title(left) == pr_body_title(right)
        same_description = pr_body_description(left) == pr_body_description(right)
        same_kind = task_kind_eqb(pr_body_kind(left), pr_body_kind(right))
        same_status = pr_body_status_eqb(pr_body_status(left), pr_body_status(right))
        same_text = same_title and same_description
        same_metadata = same_kind and same_status
        return same_task and same_text and same_metadata


def pr_body_task(p: PRBodyRow) -> int:
    return p.pr_body_task


def pr_body_title(p: PRBodyRow) -> str:
    return p.pr_body_title


def pr_body_description(p: PRBodyRow) -> str:
    return p.pr_body_description


def pr_body_kind(p: PRBodyRow) -> TaskKind:
    return p.pr_body_kind


def pr_body_status(p: PRBodyRow) -> PRBodyStatus:
    return p.pr_body_status


def projected_row(
    task: int,
    row: TaskRow,
    status: PRBodyStatus,
) -> PRBodyRow:
    return PRBodyRow(
        pr_body_task=task,
        pr_body_title=task_title(row),
        pr_body_description=task_description(row),
        pr_body_kind=task_kind(row),
        pr_body_status=status,
    )


def pending_ci_projection(
    task: int,
    rows: dict[int, TaskRow],
) -> list[PRBodyRow]:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return []
    row = __option
    match task_status(row):
        case StatusPending():
            if task_kind_is_ci(task_kind(row)):
                return [projected_row(task, row, PRPending())] + []
            return []
        case StatusCompleted():
            return []
        case StatusBlocked():
            return []
        case __impossible:
            assert_never(__impossible)


def pending_non_ci_projection(
    task: int,
    rows: dict[int, TaskRow],
) -> list[PRBodyRow]:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return []
    row = __option
    match task_status(row):
        case StatusPending():
            if task_kind_is_non_ci(task_kind(row)):
                return [projected_row(task, row, PRPending())] + []
            return []
        case StatusCompleted():
            return []
        case StatusBlocked():
            return []
        case __impossible:
            assert_never(__impossible)


def completed_projection(
    task: int,
    rows: dict[int, TaskRow],
) -> list[PRBodyRow]:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return []
    row = __option
    match task_status(row):
        case StatusPending():
            return []
        case StatusCompleted():
            return [projected_row(task, row, PRCompleted())] + []
        case StatusBlocked():
            return []
        case __impossible:
            assert_never(__impossible)


def project_pending_ci(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[PRBodyRow]:
    __list = order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    return pending_ci_projection(task, rows) + project_pending_ci(rest, rows)


def project_pending_non_ci(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[PRBodyRow]:
    __list = order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    return pending_non_ci_projection(task, rows) + project_pending_non_ci(rest, rows)


def project_completed(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[PRBodyRow]:
    __list = order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    return completed_projection(task, rows) + project_completed(rest, rows)


def project_task_store(store: TaskStore) -> list[PRBodyRow]:
    order = task_store_order(store)
    rows = task_store_rows(store)
    pending_ci = project_pending_ci(order, rows)
    pending_non_ci = project_pending_non_ci(order, rows)
    completed = project_completed(order, rows)
    return pending_ci + pending_non_ci + completed


def task_kind_eqb(
    left: TaskKind,
    right: TaskKind,
) -> bool:
    match left:
        case TaskCI():
            match right:
                case TaskCI():
                    return True
                case TaskThread():
                    return False
                case TaskSpec():
                    return False
                case TaskAsk():
                    return False
                case TaskDefer():
                    return False
                case __impossible:
                    assert_never(__impossible)
        case TaskThread():
            match right:
                case TaskCI():
                    return False
                case TaskThread():
                    return True
                case TaskSpec():
                    return False
                case TaskAsk():
                    return False
                case TaskDefer():
                    return False
                case __impossible:
                    assert_never(__impossible)
        case TaskSpec():
            match right:
                case TaskCI():
                    return False
                case TaskThread():
                    return False
                case TaskSpec():
                    return True
                case TaskAsk():
                    return False
                case TaskDefer():
                    return False
                case __impossible:
                    assert_never(__impossible)
        case TaskAsk():
            match right:
                case TaskCI():
                    return False
                case TaskThread():
                    return False
                case TaskSpec():
                    return False
                case TaskAsk():
                    return True
                case TaskDefer():
                    return False
                case __impossible:
                    assert_never(__impossible)
        case TaskDefer():
            match right:
                case TaskCI():
                    return False
                case TaskThread():
                    return False
                case TaskSpec():
                    return False
                case TaskAsk():
                    return False
                case TaskDefer():
                    return True
                case __impossible:
                    assert_never(__impossible)
        case __impossible:
            assert_never(__impossible)


def pr_body_status_eqb(
    left: PRBodyStatus,
    right: PRBodyStatus,
) -> bool:
    match left:
        case PRPending():
            match right:
                case PRPending():
                    return True
                case PRCompleted():
                    return False
                case __impossible:
                    assert_never(__impossible)
        case PRCompleted():
            match right:
                case PRPending():
                    return False
                case PRCompleted():
                    return True
                case __impossible:
                    assert_never(__impossible)
        case __impossible:
            assert_never(__impossible)


def pr_body_eqb(
    left: list[PRBodyRow],
    right: list[PRBodyRow],
) -> bool:
    __list = left
    if __list == []:
        __list = right
        if __list == []:
            return True
        p = __list[0]
        l = __list[1:]
        return False
    left_row = __list[0]
    left_rest = __list[1:]
    __list = right
    if __list == []:
        return False
    right_row = __list[0]
    right_rest = __list[1:]
    return left_row.body_row_eqb(right_row) and pr_body_eqb(left_rest, right_rest)


@dataclass(frozen=True)
class SystemState:
    durable_task_store: TaskStore
    visible_pr_body: list[PRBodyRow]


def durable_task_store(s: SystemState) -> TaskStore:
    return s.durable_task_store


def visible_pr_body(s: SystemState) -> list[PRBodyRow]:
    return s.visible_pr_body


def pr_body_matches_store_bool(state: SystemState) -> bool:
    visible = visible_pr_body(state)
    projected = project_task_store(durable_task_store(state))
    return pr_body_eqb(visible, projected)


def synced_state(store: TaskStore) -> SystemState:
    return SystemState(
        durable_task_store=store,
        visible_pr_body=project_task_store(store),
    )


class TaskWrite:
    pass


@dataclass(frozen=True)
class WriteTaskAdd(TaskWrite):
    task: int
    row: TaskRow


@dataclass(frozen=True)
class WriteTaskComplete(TaskWrite):
    task: int


@dataclass(frozen=True)
class WriteTaskRescope(TaskWrite):
    snapshot_order: list[int]
    ops: list[RescopeOp]


TaskWriteT = WriteTaskAdd | WriteTaskComplete | WriteTaskRescope


def apply_task_write(
    write: TaskWrite,
    store: TaskStore,
) -> TaskStore:
    match write:
        case WriteTaskAdd(task, row):
            order = task_store_order(store)
            rows = task_store_rows(store)
            __pair = enqueue_task(task, row, order, rows)
            p = __pair[0]
            p0 = __pair[1]
            __pair = p
            order_ = __pair[0]
            rows_ = __pair[1]
            return TaskStore(
                task_store_order=order_,
                task_store_rows=rows_,
            )
        case WriteTaskComplete(task):
            __pair = complete_task_visible(task, task_store_rows(store))
            rows_ = __pair[0]
            o = __pair[1]
            return TaskStore(
                task_store_order=task_store_order(store),
                task_store_rows=rows_,
            )
        case WriteTaskRescope(snapshot_order, ops):
            order = task_store_order(store)
            rows = task_store_rows(store)
            __pair = apply_rescope(snapshot_order, order, rows, ops)
            order_ = __pair[0]
            rows_ = __pair[1]
            return TaskStore(
                task_store_order=order_,
                task_store_rows=rows_,
            )
        case __impossible:
            assert_never(__impossible)


def transition(
    state: SystemState,
    write: TaskWrite,
) -> SystemState | None:
    if pr_body_matches_store_bool(state):
        return synced_state(apply_task_write(write, durable_task_store(state)))
    return None
