# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
)


class ClaimState:
    pass


@dataclass(frozen=True)
class ClaimInProgress(ClaimState):
    pass


@dataclass(frozen=True)
class ClaimCompleted(ClaimState):
    pass


@dataclass(frozen=True)
class ClaimRetryableFailed(ClaimState):
    pass


ClaimStateT = ClaimInProgress | ClaimCompleted | ClaimRetryableFailed


class PromiseState:
    pass


@dataclass(frozen=True)
class PromisePrepared(PromiseState):
    pass


@dataclass(frozen=True)
class PromisePosted(PromiseState):
    pass


@dataclass(frozen=True)
class PromiseAcked(PromiseState):
    pass


@dataclass(frozen=True)
class PromiseFailed(PromiseState):
    pass


PromiseStateT = PromisePrepared | PromisePosted | PromiseAcked | PromiseFailed


class RecoveryObservation:
    pass


@dataclass(frozen=True)
class SeenPromiseMarker(RecoveryObservation):
    pass


@dataclass(frozen=True)
class AnchorDeleted(RecoveryObservation):
    pass


@dataclass(frozen=True)
class WrongPullRequest(RecoveryObservation):
    pass


@dataclass(frozen=True)
class ReplayPosted(RecoveryObservation):
    pass


@dataclass(frozen=True)
class ReplayFailed(RecoveryObservation):
    pass


RecoveryObservationT = (
    SeenPromiseMarker | AnchorDeleted | WrongPullRequest | ReplayPosted | ReplayFailed
)


class ClaimOwner:
    pass


@dataclass(frozen=True)
class OwnerWebhook(ClaimOwner):
    pass


@dataclass(frozen=True)
class OwnerWorker(ClaimOwner):
    pass


@dataclass(frozen=True)
class OwnerRecovery(ClaimOwner):
    pass


ClaimOwnerT = OwnerWebhook | OwnerWorker | OwnerRecovery


@dataclass(frozen=True)
class Attempt:
    attempt_owner: ClaimOwner
    attempt_retry_count: int
    attempt_next_retry_after: int


@dataclass(frozen=True)
class ClaimRow:
    claim_attempt: Attempt
    claim_state: ClaimState
    claim_promise: int

    def is_blocking(self) -> bool:
        row = self
        return not isinstance(row.claim_state, ClaimRetryableFailed)


@dataclass(frozen=True)
class PromiseRow:
    promise_attempt: Attempt
    promise_state: PromiseState
    promise_anchor_comment: int
    promise_covered_comments: list[int]


class ConversationLane:
    pass


@dataclass(frozen=True)
class ReviewThreadLane(ConversationLane):
    thread_id: int


@dataclass(frozen=True)
class PullRequestLane(ConversationLane):
    pr_number: int


ConversationLaneT = ReviewThreadLane | PullRequestLane


@dataclass(frozen=True)
class ReplyArtifact:
    artifact_comment: int
    artifact_lane: ConversationLane
    artifact_promises: list[int]


class ReviewReplyOutcome:
    pass


@dataclass(frozen=True)
class ReviewAct(ReviewReplyOutcome):
    pass


@dataclass(frozen=True)
class ReviewDo(ReviewReplyOutcome):
    pass


@dataclass(frozen=True)
class ReviewAsk(ReviewReplyOutcome):
    pass


@dataclass(frozen=True)
class ReviewAnswer(ReviewReplyOutcome):
    pass


@dataclass(frozen=True)
class ReviewDefer(ReviewReplyOutcome):
    pass


@dataclass(frozen=True)
class ReviewDump(ReviewReplyOutcome):
    pass


ReviewReplyOutcomeT = (
    ReviewAct | ReviewDo | ReviewAsk | ReviewAnswer | ReviewDefer | ReviewDump
)


def new_attempt(owner: ClaimOwner) -> Attempt:
    return Attempt(
        attempt_owner=owner,
        attempt_retry_count=0,
        attempt_next_retry_after=0,
    )


def retry_attempt(attempt0: Attempt) -> Attempt:
    return Attempt(
        attempt_owner=attempt0.attempt_owner,
        attempt_retry_count=attempt0.attempt_retry_count + 1,
        attempt_next_retry_after=attempt0.attempt_next_retry_after + 1,
    )


def reset_attempt_retry(attempt0: Attempt) -> Attempt:
    return Attempt(
        attempt_owner=attempt0.attempt_owner,
        attempt_retry_count=attempt0.attempt_retry_count,
        attempt_next_retry_after=0,
    )


def comment_claimable(
    claims: dict[int, ClaimRow],
    comment: int,
) -> bool:
    __option = claims.get(_rocq_positive_key(comment))
    if __option is None:
        return True
    row = __option
    return not row.is_blocking()


def all_claimable(
    claims: dict[int, ClaimRow],
    comments: list[int],
) -> bool:
    __list = comments
    if __list == []:
        return True
    comment = __list[0]
    rest = __list[1:]
    if comment_claimable(claims, comment):
        return all_claimable(claims, rest)
    return False


def in_progress_row(
    owner: ClaimOwner,
    promise: int,
) -> ClaimRow:
    return ClaimRow(
        claim_attempt=new_attempt(owner),
        claim_state=ClaimInProgress(),
        claim_promise=promise,
    )


def claim_all(
    owner: ClaimOwner,
    promise: int,
    comments: list[int],
    claims: dict[int, ClaimRow],
) -> dict[int, ClaimRow]:
    __list = comments
    if __list == []:
        return claims
    comment = __list[0]
    rest = __list[1:]
    return claim_all(
        owner,
        promise,
        rest,
        _rocq_map_add(
            _rocq_positive_key(comment),
            in_progress_row(owner, promise),
            claims,
        ),
    )


def prepare_claims(
    owner: ClaimOwner,
    promise: int,
    anchor: int,
    covered: list[int],
    claims: dict[int, ClaimRow],
    promises: dict[int, PromiseRow],
) -> tuple[dict[int, ClaimRow], dict[int, PromiseRow]] | None:
    comments = [anchor] + covered
    if all_claimable(claims, comments):
        claims_ = claim_all(
            owner,
            promise,
            comments,
            claims,
        )
        promise_row = PromiseRow(
            promise_attempt=new_attempt(owner),
            promise_state=PromisePrepared(),
            promise_anchor_comment=anchor,
            promise_covered_comments=comments,
        )
        return (
            claims_,
            _rocq_map_add(
                _rocq_positive_key(promise),
                promise_row,
                promises,
            ),
        )
    return None


def mark_promise_posted(
    promise: int,
    promises: dict[int, PromiseRow],
) -> dict[int, PromiseRow]:
    __option = promises.get(_rocq_positive_key(promise))
    if __option is None:
        return promises
    row = __option
    return _rocq_map_add(
        _rocq_positive_key(promise),
        PromiseRow(
            promise_attempt=row.promise_attempt,
            promise_state=PromisePosted(),
            promise_anchor_comment=row.promise_anchor_comment,
            promise_covered_comments=row.promise_covered_comments,
        ),
        promises,
    )


def promise_recoverable(state: PromiseState) -> bool:
    return not isinstance(state, PromiseAcked)


def complete_comment(
    promise: int,
    comment: int,
    claims: dict[int, ClaimRow],
) -> dict[int, ClaimRow]:
    __option = claims.get(_rocq_positive_key(comment))
    if __option is None:
        return claims
    row = __option
    return _rocq_map_add(
        _rocq_positive_key(comment),
        ClaimRow(
            claim_attempt=reset_attempt_retry(row.claim_attempt),
            claim_state=ClaimCompleted(),
            claim_promise=promise,
        ),
        claims,
    )


def complete_all(
    promise: int,
    comments: list[int],
    claims: dict[int, ClaimRow],
) -> dict[int, ClaimRow]:
    __list = comments
    if __list == []:
        return claims
    comment = __list[0]
    rest = __list[1:]
    return complete_all(
        promise,
        rest,
        complete_comment(
            promise,
            comment,
            claims,
        ),
    )


def ack_promise(
    promise: int,
    claims: dict[int, ClaimRow],
    promises: dict[int, PromiseRow],
) -> tuple[dict[int, ClaimRow], dict[int, PromiseRow]]:
    __option = promises.get(_rocq_positive_key(promise))
    if __option is None:
        return (
            claims,
            promises,
        )
    row = __option
    claims_ = complete_all(
        promise,
        row.promise_covered_comments,
        claims,
    )
    promises_ = _rocq_map_add(
        _rocq_positive_key(promise),
        PromiseRow(
            promise_attempt=reset_attempt_retry(row.promise_attempt),
            promise_state=PromiseAcked(),
            promise_anchor_comment=row.promise_anchor_comment,
            promise_covered_comments=row.promise_covered_comments,
        ),
        promises,
    )
    return (
        claims_,
        promises_,
    )


def retryable_row(row: ClaimRow) -> ClaimRow:
    return ClaimRow(
        claim_attempt=retry_attempt(row.claim_attempt),
        claim_state=ClaimRetryableFailed(),
        claim_promise=row.claim_promise,
    )


def fail_comment(
    comment: int,
    claims: dict[int, ClaimRow],
) -> dict[int, ClaimRow]:
    __option = claims.get(_rocq_positive_key(comment))
    if __option is None:
        return claims
    row = __option
    return _rocq_map_add(
        _rocq_positive_key(comment),
        retryable_row(row),
        claims,
    )


def fail_all(
    comments: list[int],
    claims: dict[int, ClaimRow],
) -> dict[int, ClaimRow]:
    __list = comments
    if __list == []:
        return claims
    comment = __list[0]
    rest = __list[1:]
    return fail_all(rest, fail_comment(comment, claims))


def fail_promise(
    promise: int,
    claims: dict[int, ClaimRow],
    promises: dict[int, PromiseRow],
) -> tuple[dict[int, ClaimRow], dict[int, PromiseRow]]:
    __option = promises.get(_rocq_positive_key(promise))
    if __option is None:
        return (
            claims,
            promises,
        )
    row = __option
    claims_ = fail_all(row.promise_covered_comments, claims)
    promises_ = _rocq_map_add(
        _rocq_positive_key(promise),
        PromiseRow(
            promise_attempt=retry_attempt(row.promise_attempt),
            promise_state=PromiseFailed(),
            promise_anchor_comment=row.promise_anchor_comment,
            promise_covered_comments=row.promise_covered_comments,
        ),
        promises,
    )
    return (
        claims_,
        promises_,
    )


def recover_promise(
    promise: int,
    observation: RecoveryObservation,
    claims: dict[int, ClaimRow],
    promises: dict[int, PromiseRow],
) -> tuple[dict[int, ClaimRow], dict[int, PromiseRow]]:
    match observation:
        case SeenPromiseMarker():
            return ack_promise(
                promise,
                claims,
                promises,
            )
        case AnchorDeleted():
            return fail_promise(
                promise,
                claims,
                promises,
            )
        case WrongPullRequest():
            return (
                claims,
                promises,
            )
        case ReplayPosted():
            promises_ = mark_promise_posted(promise, promises)
            __pair = ack_promise(promise, claims, promises_)
            claims_ = __pair[0]
            promises__ = __pair[1]
            return (
                claims_,
                promises__,
            )
        case ReplayFailed():
            return fail_promise(
                promise,
                claims,
                promises,
            )
        case __impossible:
            assert_never(__impossible)


def record_reply_artifact(
    artifact_comment0: int,
    lane: ConversationLane,
    covered_promises: list[int],
    artifacts: dict[int, ReplyArtifact],
) -> dict[int, ReplyArtifact]:
    return _rocq_map_add(
        _rocq_positive_key(artifact_comment0),
        ReplyArtifact(
            artifact_comment=artifact_comment0,
            artifact_lane=lane,
            artifact_promises=covered_promises,
        ),
        artifacts,
    )


def review_outcome_creates_tasks(outcome: ReviewReplyOutcome) -> bool:
    match outcome:
        case ReviewAct():
            return True
        case ReviewDo():
            return True
        case ReviewAsk():
            return False
        case ReviewAnswer():
            return False
        case ReviewDefer():
            return False
        case ReviewDump():
            return False
        case __impossible:
            assert_never(__impossible)


def review_outcome_resolves_thread(outcome: ReviewReplyOutcome) -> bool:
    match outcome:
        case ReviewAct():
            return False
        case ReviewDo():
            return False
        case ReviewAsk():
            return False
        case ReviewAnswer():
            return False
        case ReviewDefer():
            return True
        case ReviewDump():
            return True
        case __impossible:
            assert_never(__impossible)


def claim_state_completed(state: ClaimState) -> bool:
    return isinstance(state, ClaimCompleted)


def claim_completed(
    claims: dict[int, ClaimRow],
    comment: int,
) -> bool:
    __option = claims.get(_rocq_positive_key(comment))
    if __option is None:
        return False
    row = __option
    return claim_state_completed(row.claim_state)
