# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass, replace
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
    final,
)


class OriginKind:
    pass


@final
@dataclass(frozen=True)
class ReviewThreadOrigin(OriginKind):
    pass


@final
@dataclass(frozen=True)
class IssueCommentOrigin(OriginKind):
    pass


OriginKindT = ReviewThreadOrigin | IssueCommentOrigin


class OutboxKind:
    pass


@final
@dataclass(frozen=True)
class ReplyPostEffect(OutboxKind):
    pass


@final
@dataclass(frozen=True)
class DeferredIssueEffect(OutboxKind):
    pass


OutboxKindT = ReplyPostEffect | DeferredIssueEffect


class ReplyClaimState:
    pass


@final
@dataclass(frozen=True)
class ReplyClaimInProgress(ReplyClaimState):
    pass


@final
@dataclass(frozen=True)
class ReplyClaimCompleted(ReplyClaimState):
    pass


@final
@dataclass(frozen=True)
class ReplyClaimRetryable(ReplyClaimState):
    pass


ReplyClaimStateT = ReplyClaimInProgress | ReplyClaimCompleted | ReplyClaimRetryable


class EffectState:
    pass


@final
@dataclass(frozen=True)
class EffectPrepared(EffectState):
    pass


@final
@dataclass(frozen=True)
class EffectClaimed(EffectState):
    pass


@final
@dataclass(frozen=True)
class EffectDelivered(EffectState):
    pass


@final
@dataclass(frozen=True)
class EffectFailed(EffectState):
    pass


EffectStateT = EffectPrepared | EffectClaimed | EffectDelivered | EffectFailed


class EffectDecision:
    pass


@final
@dataclass(frozen=True)
class EmitEffect(EffectDecision):
    pass


@final
@dataclass(frozen=True)
class ReuseDeliveredEffect(EffectDecision):
    pass


@final
@dataclass(frozen=True)
class WaitForInFlightEffect(EffectDecision):
    pass


@final
@dataclass(frozen=True)
class RetryLaterEffect(EffectDecision):
    pass


@final
@dataclass(frozen=True)
class RejectMissingEffect(EffectDecision):
    pass


EffectDecisionT = (
    EmitEffect
    | ReuseDeliveredEffect
    | WaitForInFlightEffect
    | RetryLaterEffect
    | RejectMissingEffect
)


@final
@dataclass(frozen=True)
class OriginClaim:
    origin_claim_kind: OriginKind
    origin_claim_state: ReplyClaimState
    origin_claim_promise: int
    origin_claim_delivery: int


@final
@dataclass(frozen=True)
class OutboxEffect:
    effect_kind: OutboxKind
    effect_origin: int
    effect_promise: int
    effect_state: EffectState
    effect_external_id: int | None

    def claimable(self) -> bool:
        effect = self
        match effect.effect_state:
            case EffectPrepared():
                return True
            case EffectClaimed():
                return False
            case EffectDelivered():
                return False
            case EffectFailed():
                return True
            case __impossible:
                assert_never(__impossible)

    def decision_for(self) -> EffectDecision:
        effect = self
        match effect.effect_state:
            case EffectPrepared():
                return EmitEffect()
            case EffectClaimed():
                return WaitForInFlightEffect()
            case EffectDelivered():
                return ReuseDeliveredEffect()
            case EffectFailed():
                return RetryLaterEffect()
            case __impossible:
                assert_never(__impossible)


@final
@dataclass(frozen=True)
class ProtocolState:
    protocol_origins: dict[int, OriginClaim]
    protocol_deliveries: dict[int, int]
    protocol_effects: dict[int, OutboxEffect]
    protocol_deferred_effects: dict[int, int]
    protocol_live_replies: dict[int, int]
    protocol_live_issues: dict[int, int]


empty_protocol_state: ProtocolState = ProtocolState(
    protocol_origins={},
    protocol_deliveries={},
    protocol_effects={},
    protocol_deferred_effects={},
    protocol_live_replies={},
    protocol_live_issues={},
)


def claim_blocks_generation(claim: OriginClaim) -> bool:
    return not isinstance(claim.origin_claim_state, ReplyClaimRetryable)


def origin_claimable(
    state: ProtocolState,
    origin: int,
) -> bool:
    __option = state.protocol_origins.get(_rocq_positive_key(origin))
    if __option is None:
        return True
    claim = __option
    return not claim_blocks_generation(claim)


def origin_completed(
    state: ProtocolState,
    origin: int,
) -> bool:
    __option = state.protocol_origins.get(_rocq_positive_key(origin))
    if __option is None:
        return False
    claim = __option
    return isinstance(claim.origin_claim_state, ReplyClaimCompleted)


def delivery_origin(
    state: ProtocolState,
    delivery: int,
) -> int | None:
    return state.protocol_deliveries.get(_rocq_positive_key(delivery))


def promise_owns_origin(
    state: ProtocolState,
    promise: int,
    origin: int,
) -> bool:
    __option = state.protocol_origins.get(_rocq_positive_key(origin))
    if __option is None:
        return False
    claim = __option
    if claim.origin_claim_promise == promise:
        return isinstance(claim.origin_claim_state, ReplyClaimInProgress)
    return False


def can_generate_reply(
    state: ProtocolState,
    promise: int,
    origin: int,
) -> bool:
    return promise_owns_origin(
        state,
        promise,
        origin,
    )


def in_progress_claim(
    kind: OriginKind,
    promise: int,
    delivery: int,
) -> OriginClaim:
    return OriginClaim(
        origin_claim_kind=kind,
        origin_claim_state=ReplyClaimInProgress(),
        origin_claim_promise=promise,
        origin_claim_delivery=delivery,
    )


def prepared_effect(
    kind: OutboxKind,
    origin: int,
    promise: int,
) -> OutboxEffect:
    return OutboxEffect(
        effect_kind=kind,
        effect_origin=origin,
        effect_promise=promise,
        effect_state=EffectPrepared(),
        effect_external_id=None,
    )


def prepare_reply(
    delivery: int,
    origin: int,
    promise: int,
    reply_effect: int,
    kind: OriginKind,
    state: ProtocolState,
) -> ProtocolState | None:
    if origin_claimable(state, origin):
        return replace(
            state,
            protocol_origins=_rocq_map_add(
                _rocq_positive_key(origin),
                in_progress_claim(
                    kind,
                    promise,
                    delivery,
                ),
                state.protocol_origins,
            ),
            protocol_deliveries=_rocq_map_add(
                _rocq_positive_key(delivery),
                origin,
                state.protocol_deliveries,
            ),
            protocol_effects=_rocq_map_add(
                _rocq_positive_key(reply_effect),
                prepared_effect(
                    ReplyPostEffect(),
                    origin,
                    promise,
                ),
                state.protocol_effects,
            ),
        )
    return None


def outbox_decision(
    state: ProtocolState,
    effect_id: int,
) -> EffectDecision:
    __option = state.protocol_effects.get(_rocq_positive_key(effect_id))
    if __option is None:
        return RejectMissingEffect()
    effect = __option
    return effect.decision_for()


def claimed_effect(effect: OutboxEffect) -> OutboxEffect:
    return replace(
        effect,
        effect_state=EffectClaimed(),
    )


def claim_outbox_effect(
    effect_id: int,
    state: ProtocolState,
) -> ProtocolState | None:
    __option = state.protocol_effects.get(_rocq_positive_key(effect_id))
    if __option is None:
        return None
    effect = __option
    if effect.claimable():
        return replace(
            state,
            protocol_effects=_rocq_map_add(
                _rocq_positive_key(effect_id),
                claimed_effect(effect),
                state.protocol_effects,
            ),
        )
    return None


def delivered_effect(
    external_id: int,
    effect: OutboxEffect,
) -> OutboxEffect:
    return replace(
        effect,
        effect_state=EffectDelivered(),
        effect_external_id=external_id,
    )


def completed_claim(claim: OriginClaim) -> OriginClaim:
    return replace(
        claim,
        origin_claim_state=ReplyClaimCompleted(),
    )


def retryable_claim(claim: OriginClaim) -> OriginClaim:
    return replace(
        claim,
        origin_claim_state=ReplyClaimRetryable(),
    )


def failed_effect(effect: OutboxEffect) -> OutboxEffect:
    return replace(
        effect,
        effect_state=EffectFailed(),
    )


def record_reply_posted(
    effect_id: int,
    artifact_id: int,
    state: ProtocolState,
) -> ProtocolState | None:
    __option = state.protocol_effects.get(_rocq_positive_key(effect_id))
    if __option is None:
        return None
    effect = __option
    match effect.effect_kind:
        case ReplyPostEffect():
            match effect.effect_state:
                case EffectPrepared():
                    return None
                case EffectClaimed():
                    origin = effect.effect_origin
                    __option = state.protocol_origins.get(_rocq_positive_key(origin))
                    if __option is None:
                        return None
                    claim = __option
                    return replace(
                        state,
                        protocol_origins=_rocq_map_add(
                            _rocq_positive_key(origin),
                            completed_claim(claim),
                            state.protocol_origins,
                        ),
                        protocol_effects=_rocq_map_add(
                            _rocq_positive_key(effect_id),
                            delivered_effect(artifact_id, effect),
                            state.protocol_effects,
                        ),
                        protocol_live_replies=_rocq_map_add(
                            _rocq_positive_key(origin),
                            artifact_id,
                            state.protocol_live_replies,
                        ),
                    )
                case EffectDelivered():
                    return state
                case EffectFailed():
                    return None
                case __impossible:
                    assert_never(__impossible)
        case DeferredIssueEffect():
            return None
        case __impossible:
            assert_never(__impossible)


def prepare_deferred_issue(
    issue_effect: int,
    origin: int,
    promise: int,
    state: ProtocolState,
) -> ProtocolState | None:
    __option = state.protocol_origins.get(_rocq_positive_key(origin))
    if __option is None:
        return None
    claim = __option
    if claim.origin_claim_promise == promise:
        __option = state.protocol_deferred_effects.get(_rocq_positive_key(origin))
        if __option is None:
            __option = state.protocol_effects.get(_rocq_positive_key(issue_effect))
            if __option is None:
                return replace(
                    state,
                    protocol_effects=_rocq_map_add(
                        _rocq_positive_key(issue_effect),
                        prepared_effect(
                            DeferredIssueEffect(),
                            origin,
                            promise,
                        ),
                        state.protocol_effects,
                    ),
                    protocol_deferred_effects=_rocq_map_add(
                        _rocq_positive_key(origin),
                        issue_effect,
                        state.protocol_deferred_effects,
                    ),
                )
            o = __option
            return state
        existing_effect = __option
        if existing_effect == issue_effect:
            return state
        return None
    return None


def record_deferred_issue_opened(
    effect_id: int,
    issue_id: int,
    state: ProtocolState,
) -> ProtocolState | None:
    __option = state.protocol_effects.get(_rocq_positive_key(effect_id))
    if __option is None:
        return None
    effect = __option
    match effect.effect_kind:
        case ReplyPostEffect():
            return None
        case DeferredIssueEffect():
            match effect.effect_state:
                case EffectPrepared():
                    return None
                case EffectClaimed():
                    return replace(
                        state,
                        protocol_effects=_rocq_map_add(
                            _rocq_positive_key(effect_id),
                            delivered_effect(issue_id, effect),
                            state.protocol_effects,
                        ),
                        protocol_live_issues=_rocq_map_add(
                            _rocq_positive_key(effect_id),
                            issue_id,
                            state.protocol_live_issues,
                        ),
                    )
                case EffectDelivered():
                    return state
                case EffectFailed():
                    return None
                case __impossible:
                    assert_never(__impossible)
        case __impossible:
            assert_never(__impossible)


def record_outbox_failure(
    effect_id: int,
    state: ProtocolState,
) -> ProtocolState | None:
    __option = state.protocol_effects.get(_rocq_positive_key(effect_id))
    if __option is None:
        return None
    effect = __option
    match effect.effect_state:
        case EffectPrepared():
            return None
        case EffectClaimed():
            effects_ = _rocq_map_add(
                _rocq_positive_key(effect_id),
                failed_effect(effect),
                state.protocol_effects,
            )
            match effect.effect_kind:
                case ReplyPostEffect():
                    origin = effect.effect_origin
                    __option = state.protocol_origins.get(_rocq_positive_key(origin))
                    if __option is None:
                        return None
                    claim = __option
                    return replace(
                        state,
                        protocol_origins=_rocq_map_add(
                            _rocq_positive_key(origin),
                            retryable_claim(claim),
                            state.protocol_origins,
                        ),
                        protocol_effects=effects_,
                    )
                case DeferredIssueEffect():
                    return replace(
                        state,
                        protocol_effects=effects_,
                    )
                case __impossible:
                    assert_never(__impossible)
        case EffectDelivered():
            return None
        case EffectFailed():
            return None
        case __impossible:
            assert_never(__impossible)


def live_reply_for_origin(
    state: ProtocolState,
    origin: int,
) -> int | None:
    return state.protocol_live_replies.get(_rocq_positive_key(origin))


def live_issue_for_effect(
    state: ProtocolState,
    effect_id: int,
) -> int | None:
    return state.protocol_live_issues.get(_rocq_positive_key(effect_id))


def effect_external(
    state: ProtocolState,
    effect_id: int,
) -> int | None:
    __option = state.protocol_effects.get(_rocq_positive_key(effect_id))
    if __option is None:
        return None
    effect = __option
    return effect.effect_external_id
