# Generated by rocq-python-extraction (target: Python 3.14t)
import asyncio
import queue
import threading
from contextlib import asynccontextmanager
from concurrent.futures import Future as _ConcurrentFuture
from itertools import islice
from dataclasses import dataclass
from fractions import Fraction
from typing import (
    Any,
    AsyncIterator,
    Awaitable,
    Callable,
    Generic,
    Iterable,
    Iterator,
    Never,
    Protocol,
    TypeVar,
    assert_never,
    cast,
)

_CoForceT = TypeVar("_CoForceT")
_ModuleArgT = TypeVar("_ModuleArgT")
_ModuleRetT = TypeVar("_ModuleRetT")
_StateTState = TypeVar("_StateTState")
_StateTValue = TypeVar("_StateTValue")
_StateTNext = TypeVar("_StateTNext")
_IOValue = TypeVar("_IOValue")
_IONext = TypeVar("_IONext")
_IOOwner = TypeVar("_IOOwner")
_ChannelValue = TypeVar("_ChannelValue")
_FutureValue = TypeVar("_FutureValue")


class _Impossible(RuntimeError):
    pass


def _impossible() -> Never:
    raise _Impossible()


class _RocqUtf8BoundaryError(UnicodeError):
    pass


class _RocqNumericDomainError(ValueError):
    pass


def _rocq_numeric_domain_error(kind: str, value: object) -> Never:
    raise _RocqNumericDomainError(f"Rocq {kind} value out of domain: {value!r}")


key = int  # finite-map module key alias
elt = int  # finite-set module element alias


def _rocq_positive_key(key: int) -> int:
    if key <= 0:
        raise _RocqNumericDomainError("positive map/set key", key)
    return key


def _rocq_string_key(key: str) -> str:
    if not isinstance(key, str):
        raise TypeError(f"Rocq string map/set key must be str: {key!r}")
    return key


def _rocq_sorted_key(key: object) -> Any:
    return key.encode("utf-8") if isinstance(key, str) else key


def _rocq_map_add(
    key: object, value: object, mapping: dict[object, object]
) -> dict[object, object]:
    result = dict(mapping)
    result[key] = value
    return result


def _rocq_map_remove(
    key: object, mapping: dict[object, object]
) -> dict[object, object]:
    result = dict(mapping)
    result.pop(key, None)
    return result


def _rocq_map_elements(mapping: dict[object, object]) -> list[tuple[object, object]]:
    return sorted(mapping.items(), key=lambda item: _rocq_sorted_key(item[0]))


def _rocq_map_fold(
    function: Callable[[object, object, object], object],
    mapping: dict[object, object],
    initial: object,
) -> object:
    result = initial
    for key, value in _rocq_map_elements(mapping):
        result = function(key, value, result)
    return result


def _rocq_set_add(key: object, values: frozenset[object]) -> frozenset[object]:
    return frozenset((*values, key))


def _rocq_set_remove(key: object, values: frozenset[object]) -> frozenset[object]:
    return frozenset(value for value in values if value != key)


def _rocq_set_elements(values: frozenset[object]) -> list[object]:
    return sorted(values, key=_rocq_sorted_key)


def _rocq_set_fold(
    function: Callable[[object, object], object],
    values: frozenset[object],
    initial: object,
) -> object:
    result = initial
    for value in _rocq_set_elements(values):
        result = function(value, result)
    return result


def _rocq_string_cons(head: int, tail: str) -> str:
    try:
        return bytes([head]).decode("utf-8") + tail
    except UnicodeDecodeError as exc:
        raise _RocqUtf8BoundaryError(
            "Rocq string split crosses a UTF-8 boundary"
        ) from exc


def _rocq_string_uncons(value: str) -> tuple[int, str]:
    encoded = value.encode("utf-8")
    if not encoded:
        raise _Impossible()
    try:
        tail = encoded[1:].decode("utf-8")
    except UnicodeDecodeError as exc:
        raise _RocqUtf8BoundaryError(
            "Rocq string split crosses a UTF-8 boundary"
        ) from exc
    return encoded[0], tail


def _rocq_ascii_to_int(
    b0: bool,
    b1: bool,
    b2: bool,
    b3: bool,
    b4: bool,
    b5: bool,
    b6: bool,
    b7: bool,
) -> int:
    return sum(
        (1 << i) for i, bit in enumerate((b0, b1, b2, b3, b4, b5, b6, b7)) if bit
    )


def _rocq_ascii_bits(
    value: int,
) -> tuple[bool, bool, bool, bool, bool, bool, bool, bool]:
    if value < 0 or value > 255:
        raise ValueError("Rocq byte/ascii value out of range")
    return cast(
        tuple[bool, bool, bool, bool, bool, bool, bool, bool],
        tuple(bool(value & (1 << i)) for i in range(8)),
    )


class StateT(Generic[_StateTState, _StateTValue]):
    def __init__(
        self,
        step: Callable[[_StateTState], tuple[_StateTValue, _StateTState]],
        state: _StateTState | None = None,
    ) -> None:
        self._step = step
        self.state = state

    def run(self, state: _StateTState) -> _StateTValue:
        value, next_state = self._step(state)
        self.state = next_state
        return value

    def run_with_state(self, state: _StateTState) -> tuple[_StateTValue, _StateTState]:
        result = self._step(state)
        self.state = result[1]
        return result

    def bind(
        self,
        f: Callable[[_StateTValue], StateT[_StateTState, _StateTNext]],
    ) -> StateT[_StateTState, _StateTNext]:
        def run_bound(state: _StateTState) -> tuple[_StateTNext, _StateTState]:
            value, next_state = self._step(state)
            return f(value).run_with_state(next_state)

        return StateT(run_bound, self.state)

    @classmethod
    def pure(cls, value: _StateTValue) -> StateT[_StateTState, _StateTValue]:
        return StateT(lambda state: (value, state))

    @classmethod
    def get_state(cls) -> StateT[_StateTState, _StateTState]:
        return StateT(lambda state: (state, state))

    @classmethod
    def put_state(cls, new_state: _StateTState) -> StateT[_StateTState, None]:
        return StateT(lambda _state: (None, new_state))


class IO(Generic[_IOValue]):
    def __init__(self, thunk: Callable[[], Awaitable[_IOValue]]) -> None:
        self._thunk = thunk

    async def run(self) -> _IOValue:
        return await self._thunk()

    def bind(self, f: Callable[[_IOValue], IO[_IONext]]) -> IO[_IONext]:
        async def run_bound() -> _IONext:
            value = await self.run()
            return await f(value).run()

        return IO(run_bound)

    @classmethod
    def pure(cls, value: _IOValue) -> IO[_IOValue]:
        async def run_pure() -> _IOValue:
            return value

        return IO(run_pure)

    @classmethod
    def from_sync(cls, thunk: Callable[[], _IOValue]) -> IO[_IOValue]:
        async def run_sync() -> _IOValue:
            return thunk()

        return IO(run_sync)

    @classmethod
    def from_blocking(cls, thunk: Callable[[], _IOValue]) -> IO[_IOValue]:
        async def run_blocking() -> _IOValue:
            return await asyncio.to_thread(thunk)

        return IO(run_blocking)

    @classmethod
    @asynccontextmanager
    async def ownership(
        cls,
        acquire: IO[_IOOwner],
        release: Callable[[_IOOwner], IO[None]],
    ) -> AsyncIterator[_IOOwner]:
        owner = await acquire.run()
        try:
            yield owner
        finally:
            await release(owner).run()

    @classmethod
    def bracket(
        cls,
        acquire: IO[_IOOwner],
        release: Callable[[_IOOwner], IO[None]],
        use: Callable[[_IOOwner], IO[_IONext]],
    ) -> IO[_IONext]:
        async def run_bracket() -> _IONext:
            async with cls.ownership(acquire, release) as owner:
                return await use(owner).run()

        return IO(run_bracket)


class Mutex:
    """Explicit threading mutex wrapper for extracted coordination models.

    This wrapper exposes Python's lock behavior; it does not prove fairness,
    starvation freedom, or a Rocq-level scheduler semantics.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()

    @classmethod
    def new(cls) -> IO[Mutex]:
        return IO.from_sync(cls)

    def acquire(self) -> IO[None]:
        def lock() -> None:
            self._lock.acquire()

        return IO.from_blocking(lock)

    def release(self) -> IO[None]:
        def unlock() -> None:
            self._lock.release()

        return IO.from_sync(unlock)


class Channel(Generic[_ChannelValue]):
    """Explicit FIFO channel wrapper backed by queue.SimpleQueue.

    FIFO order is for completed sends observed by this queue.  This wrapper
    does not model scheduler fairness, producer/consumer races, or cancellation.
    """

    def __init__(self) -> None:
        self._queue: queue.SimpleQueue[_ChannelValue] = queue.SimpleQueue()

    @classmethod
    def new(cls) -> IO[Channel[_ChannelValue]]:
        return IO.from_sync(cls)

    def send(self, value: _ChannelValue) -> IO[None]:
        def put() -> None:
            self._queue.put(value)

        return IO.from_sync(put)

    def receive(self) -> IO[_ChannelValue]:
        return IO.from_blocking(self._queue.get)


class Future(Generic[_FutureValue]):
    """Explicit future wrapper backed by concurrent.futures.Future.

    Completion follows Python Future semantics: result blocks until completed,
    double completion raises, and no Rocq-level thread interleaving is implied.
    """

    def __init__(self) -> None:
        self._future: _ConcurrentFuture[_FutureValue] = _ConcurrentFuture()

    @classmethod
    def new(cls) -> IO[Future[_FutureValue]]:
        return IO.from_sync(cls)

    def set_result(self, value: _FutureValue) -> IO[None]:
        def set_value() -> None:
            self._future.set_result(value)

        return IO.from_sync(set_value)

    def result(self) -> IO[_FutureValue]:
        return IO.from_blocking(self._future.result)

    def done(self) -> bool:
        return self._future.done()


def coforce(value: Callable[[], _CoForceT]) -> _CoForceT:
    return value()


def coprefix_eq(n: int, left: Iterable[object], right: Iterable[object]) -> bool:
    return tuple(islice(iter(left), n)) == tuple(islice(iter(right), n))


def coprefix_hash(n: int, value: Iterable[object]) -> int:
    return hash(tuple(islice(iter(value), n)))


class __ModuleNamespace:
    pass


def __apply_applicative(
    cache: dict[int, _ModuleRetT],
    build: Callable[[_ModuleArgT], _ModuleRetT],
    arg: _ModuleArgT,
) -> _ModuleRetT:
    key = id(arg)
    cached = cache.get(key)
    if cached is None:
        cached = build(arg)
        cache[key] = cached
    return cached


__ = None  # erased logical argument


# bool: remapped to Python primitive


def negb(b: bool) -> bool:
    if b:
        return False
    return True


# nat: remapped to Python primitive
_A = TypeVar("_A")


# option: remapped to Python primitive
_A = TypeVar("_A")
_B = TypeVar("_B")


# prod: remapped to Python primitive
_A = TypeVar("_A")


# list: remapped to Python primitive
# positive: remapped to Python primitive


class ClaimState:
    pass


@dataclass(frozen=True)
class ClaimInProgress(ClaimState):
    pass


@dataclass(frozen=True)
class ClaimCompleted(ClaimState):
    pass


@dataclass(frozen=True)
class ClaimRetryableFailed(ClaimState):
    pass


ClaimStateT = ClaimInProgress | ClaimCompleted | ClaimRetryableFailed


class PromiseState:
    pass


@dataclass(frozen=True)
class PromisePrepared(PromiseState):
    pass


@dataclass(frozen=True)
class PromisePosted(PromiseState):
    pass


@dataclass(frozen=True)
class PromiseAcked(PromiseState):
    pass


@dataclass(frozen=True)
class PromiseFailed(PromiseState):
    pass


PromiseStateT = PromisePrepared | PromisePosted | PromiseAcked | PromiseFailed


class ClaimOwner:
    pass


@dataclass(frozen=True)
class OwnerWebhook(ClaimOwner):
    pass


@dataclass(frozen=True)
class OwnerWorker(ClaimOwner):
    pass


@dataclass(frozen=True)
class OwnerRecovery(ClaimOwner):
    pass


ClaimOwnerT = OwnerWebhook | OwnerWorker | OwnerRecovery


@dataclass(frozen=True)
class Build_Attempt:
    attempt_owner: ClaimOwner
    attempt_retry_count: int
    attempt_next_retry_after: int


def attempt_owner(a: Attempt) -> ClaimOwner:
    return a.attempt_owner


def attempt_retry_count(a: Attempt) -> int:
    return a.attempt_retry_count


def attempt_next_retry_after(a: Attempt) -> int:
    return a.attempt_next_retry_after


@dataclass(frozen=True)
class Build_ClaimRow:
    claim_attempt: Attempt
    claim_state: ClaimState
    claim_promise: int


def claim_attempt(c: ClaimRow) -> Attempt:
    return c.claim_attempt


def claim_state(c: ClaimRow) -> ClaimState:
    return c.claim_state


def claim_promise(c: ClaimRow) -> int:
    return c.claim_promise


@dataclass(frozen=True)
class Build_PromiseRow:
    promise_attempt: Attempt
    promise_state: PromiseState
    promise_anchor_comment: int
    promise_covered_comments: list[int]


def promise_attempt(p: PromiseRow) -> Attempt:
    return p.promise_attempt


def promise_anchor_comment(p: PromiseRow) -> int:
    return p.promise_anchor_comment


def promise_covered_comments(p: PromiseRow) -> list[int]:
    return p.promise_covered_comments


def new_attempt(owner: ClaimOwner) -> Attempt:
    return Build_Attempt(
        attempt_owner=owner,
        attempt_retry_count=0,
        attempt_next_retry_after=0,
    )


def retry_attempt(attempt0: Attempt) -> Attempt:
    return Build_Attempt(
        attempt_owner=attempt_owner(attempt0),
        attempt_retry_count=attempt_retry_count(attempt0) + 1,
        attempt_next_retry_after=attempt_next_retry_after(attempt0) + 1,
    )


def reset_attempt_retry(attempt0: Attempt) -> Attempt:
    return Build_Attempt(
        attempt_owner=attempt_owner(attempt0),
        attempt_retry_count=attempt_retry_count(attempt0),
        attempt_next_retry_after=0,
    )


def claim_is_blocking(row: ClaimRow) -> bool:
    match claim_state(row):
        case ClaimInProgress():
            return True
        case ClaimCompleted():
            return True
        case ClaimRetryableFailed():
            return False
        case __impossible:
            assert_never(__impossible)


def comment_claimable(
    claims: dict[int, ClaimRow],
    comment: int,
) -> bool:
    __option = claims.get(_rocq_positive_key(comment))
    if __option is None:
        return True
    row = __option
    return negb(claim_is_blocking(row))


def all_claimable(
    claims: dict[int, ClaimRow],
    comments: list[int],
) -> bool:
    __list = comments
    if __list == []:
        return True
    comment = __list[0]
    rest = __list[1:]
    if comment_claimable(claims, comment):
        return all_claimable(claims, rest)
    return False


def in_progress_row(
    owner: ClaimOwner,
    promise: int,
) -> ClaimRow:
    return Build_ClaimRow(
        claim_attempt=new_attempt(owner),
        claim_state=ClaimInProgress(),
        claim_promise=promise,
    )


def claim_all(
    owner: ClaimOwner,
    promise: int,
    comments: list[int],
    claims: dict[int, ClaimRow],
) -> dict[int, ClaimRow]:
    __list = comments
    if __list == []:
        return claims
    comment = __list[0]
    rest = __list[1:]
    return claim_all(
        owner,
        promise,
        rest,
        _rocq_map_add(
            _rocq_positive_key(comment),
            in_progress_row(owner, promise),
            claims,
        ),
    )


def prepare_claims(
    owner: ClaimOwner,
    promise: int,
    anchor: int,
    covered: list[int],
    claims: dict[int, ClaimRow],
    promises: dict[int, PromiseRow],
) -> tuple[dict[int, ClaimRow], dict[int, PromiseRow]] | None:
    comments = [anchor] + covered
    if all_claimable(claims, comments):
        claims_ = claim_all(
            owner,
            promise,
            comments,
            claims,
        )
        promise_row = Build_PromiseRow(
            promise_attempt=new_attempt(owner),
            promise_state=PromisePrepared(),
            promise_anchor_comment=anchor,
            promise_covered_comments=comments,
        )
        return (
            claims_,
            _rocq_map_add(
                _rocq_positive_key(promise),
                promise_row,
                promises,
            ),
        )
    return None


def mark_promise_posted(
    promise: int,
    promises: dict[int, PromiseRow],
) -> dict[int, PromiseRow]:
    __option = promises.get(_rocq_positive_key(promise))
    if __option is None:
        return promises
    row = __option
    return _rocq_map_add(
        _rocq_positive_key(promise),
        Build_PromiseRow(
            promise_attempt=promise_attempt(row),
            promise_state=PromisePosted(),
            promise_anchor_comment=promise_anchor_comment(row),
            promise_covered_comments=promise_covered_comments(row),
        ),
        promises,
    )


def complete_comment(
    promise: int,
    comment: int,
    claims: dict[int, ClaimRow],
) -> dict[int, ClaimRow]:
    __option = claims.get(_rocq_positive_key(comment))
    if __option is None:
        return claims
    row = __option
    return _rocq_map_add(
        _rocq_positive_key(comment),
        Build_ClaimRow(
            claim_attempt=reset_attempt_retry(claim_attempt(row)),
            claim_state=ClaimCompleted(),
            claim_promise=promise,
        ),
        claims,
    )


def complete_all(
    promise: int,
    comments: list[int],
    claims: dict[int, ClaimRow],
) -> dict[int, ClaimRow]:
    __list = comments
    if __list == []:
        return claims
    comment = __list[0]
    rest = __list[1:]
    return complete_all(
        promise,
        rest,
        complete_comment(
            promise,
            comment,
            claims,
        ),
    )


def ack_promise(
    promise: int,
    claims: dict[int, ClaimRow],
    promises: dict[int, PromiseRow],
) -> tuple[dict[int, ClaimRow], dict[int, PromiseRow]]:
    __option = promises.get(_rocq_positive_key(promise))
    if __option is None:
        return (
            claims,
            promises,
        )
    row = __option
    claims_ = complete_all(
        promise,
        promise_covered_comments(row),
        claims,
    )
    promises_ = _rocq_map_add(
        _rocq_positive_key(promise),
        Build_PromiseRow(
            promise_attempt=reset_attempt_retry(promise_attempt(row)),
            promise_state=PromiseAcked(),
            promise_anchor_comment=promise_anchor_comment(row),
            promise_covered_comments=promise_covered_comments(row),
        ),
        promises,
    )
    return (
        claims_,
        promises_,
    )


def retryable_row(row: ClaimRow) -> ClaimRow:
    return Build_ClaimRow(
        claim_attempt=retry_attempt(claim_attempt(row)),
        claim_state=ClaimRetryableFailed(),
        claim_promise=claim_promise(row),
    )


def fail_comment(
    comment: int,
    claims: dict[int, ClaimRow],
) -> dict[int, ClaimRow]:
    __option = claims.get(_rocq_positive_key(comment))
    if __option is None:
        return claims
    row = __option
    return _rocq_map_add(
        _rocq_positive_key(comment),
        retryable_row(row),
        claims,
    )


def fail_all(
    comments: list[int],
    claims: dict[int, ClaimRow],
) -> dict[int, ClaimRow]:
    __list = comments
    if __list == []:
        return claims
    comment = __list[0]
    rest = __list[1:]
    return fail_all(rest, fail_comment(comment, claims))


def fail_promise(
    promise: int,
    claims: dict[int, ClaimRow],
    promises: dict[int, PromiseRow],
) -> tuple[dict[int, ClaimRow], dict[int, PromiseRow]]:
    __option = promises.get(_rocq_positive_key(promise))
    if __option is None:
        return (
            claims,
            promises,
        )
    row = __option
    claims_ = fail_all(promise_covered_comments(row), claims)
    promises_ = _rocq_map_add(
        _rocq_positive_key(promise),
        Build_PromiseRow(
            promise_attempt=retry_attempt(promise_attempt(row)),
            promise_state=PromiseFailed(),
            promise_anchor_comment=promise_anchor_comment(row),
            promise_covered_comments=promise_covered_comments(row),
        ),
        promises,
    )
    return (
        claims_,
        promises_,
    )


def claim_state_completed(state: ClaimState) -> bool:
    match state:
        case ClaimInProgress():
            return False
        case ClaimCompleted():
            return True
        case ClaimRetryableFailed():
            return False
        case __impossible:
            assert_never(__impossible)


def claim_completed(
    claims: dict[int, ClaimRow],
    comment: int,
) -> bool:
    __option = claims.get(_rocq_positive_key(comment))
    if __option is None:
        return False
    row = __option
    return claim_state_completed(claim_state(row))
