# Generated by rocq-python-extraction (target: Python 3.14t)  # From retry_budget.v:17:11
from itertools import islice  # From retry_budget.v:17:11
from dataclasses import dataclass  # From retry_budget.v:17:11
from fractions import Fraction  # From retry_budget.v:17:11
from typing import (
    Any,
    Awaitable,
    Callable,
    Generic,
    Iterable,
    Iterator,
    Never,
    Protocol,
    TypeVar,
    assert_never,
    cast,
)  # From retry_budget.v:17:11

_CoForceT = TypeVar("_CoForceT")  # From retry_budget.v:17:11
_ModuleArgT = TypeVar("_ModuleArgT")  # From retry_budget.v:17:11
_ModuleRetT = TypeVar("_ModuleRetT")  # From retry_budget.v:17:11
_StateTState = TypeVar("_StateTState")  # From retry_budget.v:17:11
_StateTValue = TypeVar("_StateTValue")  # From retry_budget.v:17:11
_StateTNext = TypeVar("_StateTNext")  # From retry_budget.v:17:11
_IOValue = TypeVar("_IOValue")  # From retry_budget.v:17:11
_IONext = TypeVar("_IONext")  # From retry_budget.v:17:11


class _Impossible(RuntimeError):  # From retry_budget.v:17:11
    pass  # From retry_budget.v:17:11


def _impossible() -> Never:  # From retry_budget.v:17:11
    raise _Impossible()  # From retry_budget.v:17:11


class _RocqUtf8BoundaryError(UnicodeError):  # From retry_budget.v:17:11
    pass  # From retry_budget.v:17:11


class _RocqNumericDomainError(ValueError):  # From retry_budget.v:17:11
    pass  # From retry_budget.v:17:11


def _rocq_numeric_domain_error(
    kind: str, value: object
) -> Never:  # From retry_budget.v:17:11
    raise _RocqNumericDomainError(
        f"Rocq {kind} value out of domain: {value!r}"
    )  # From retry_budget.v:17:11


def _rocq_string_cons(head: int, tail: str) -> str:  # From retry_budget.v:17:11
    try:  # From retry_budget.v:17:11
        return bytes([head]).decode("utf-8") + tail  # From retry_budget.v:17:11
    except UnicodeDecodeError as exc:  # From retry_budget.v:17:11
        raise _RocqUtf8BoundaryError(
            "Rocq string split crosses a UTF-8 boundary"
        ) from exc  # From retry_budget.v:17:11


def _rocq_string_uncons(value: str) -> tuple[int, str]:  # From retry_budget.v:17:11
    encoded = value.encode("utf-8")  # From retry_budget.v:17:11
    if not encoded:  # From retry_budget.v:17:11
        raise _Impossible()  # From retry_budget.v:17:11
    try:  # From retry_budget.v:17:11
        tail = encoded[1:].decode("utf-8")  # From retry_budget.v:17:11
    except UnicodeDecodeError as exc:  # From retry_budget.v:17:11
        raise _RocqUtf8BoundaryError(
            "Rocq string split crosses a UTF-8 boundary"
        ) from exc  # From retry_budget.v:17:11
    return encoded[0], tail  # From retry_budget.v:17:11


def _rocq_ascii_to_int(
    b0: bool, b1: bool, b2: bool, b3: bool, b4: bool, b5: bool, b6: bool, b7: bool
) -> int:  # From retry_budget.v:17:11
    return sum(
        (1 << i) for i, bit in enumerate((b0, b1, b2, b3, b4, b5, b6, b7)) if bit
    )  # From retry_budget.v:17:11


def _rocq_ascii_bits(
    value: int,
) -> tuple[bool, bool, bool, bool, bool, bool, bool, bool]:  # From retry_budget.v:17:11
    if value < 0 or value > 255:  # From retry_budget.v:17:11
        raise ValueError(
            "Rocq byte/ascii value out of range"
        )  # From retry_budget.v:17:11
    return cast(
        tuple[bool, bool, bool, bool, bool, bool, bool, bool],
        tuple(bool(value & (1 << i)) for i in range(8)),
    )  # From retry_budget.v:17:11


class StateT(Generic[_StateTState, _StateTValue]):  # From retry_budget.v:17:11
    def __init__(
        self,
        step: Callable[[_StateTState], tuple[_StateTValue, _StateTState]],
        state: _StateTState | None = None,
    ) -> None:  # From retry_budget.v:17:11
        self._step = step  # From retry_budget.v:17:11
        self.state = state  # From retry_budget.v:17:11

    def run(self, state: _StateTState) -> _StateTValue:  # From retry_budget.v:17:11
        value, next_state = self._step(state)  # From retry_budget.v:17:11
        self.state = next_state  # From retry_budget.v:17:11
        return value  # From retry_budget.v:17:11

    def run_with_state(
        self, state: _StateTState
    ) -> tuple[_StateTValue, _StateTState]:  # From retry_budget.v:17:11
        result = self._step(state)  # From retry_budget.v:17:11
        self.state = result[1]  # From retry_budget.v:17:11
        return result  # From retry_budget.v:17:11

    def bind(
        self, f: Callable[[_StateTValue], StateT[_StateTState, _StateTNext]]
    ) -> StateT[_StateTState, _StateTNext]:  # From retry_budget.v:17:11
        def run_bound(
            state: _StateTState,
        ) -> tuple[_StateTNext, _StateTState]:  # From retry_budget.v:17:11
            value, next_state = self._step(state)  # From retry_budget.v:17:11
            return f(value).run_with_state(next_state)  # From retry_budget.v:17:11

        return StateT(run_bound, self.state)  # From retry_budget.v:17:11

    @classmethod  # From retry_budget.v:17:11
    def pure(
        cls, value: _StateTValue
    ) -> StateT[_StateTState, _StateTValue]:  # From retry_budget.v:17:11
        return StateT(lambda state: (value, state))  # From retry_budget.v:17:11

    @classmethod  # From retry_budget.v:17:11
    def get_state(
        cls,
    ) -> StateT[_StateTState, _StateTState]:  # From retry_budget.v:17:11
        return StateT(lambda state: (state, state))  # From retry_budget.v:17:11

    @classmethod  # From retry_budget.v:17:11
    def put_state(
        cls, new_state: _StateTState
    ) -> StateT[_StateTState, None]:  # From retry_budget.v:17:11
        return StateT(lambda _state: (None, new_state))  # From retry_budget.v:17:11


class IO(Generic[_IOValue]):  # From retry_budget.v:17:11
    def __init__(
        self, thunk: Callable[[], Awaitable[_IOValue]]
    ) -> None:  # From retry_budget.v:17:11
        self._thunk = thunk  # From retry_budget.v:17:11

    async def run(self) -> _IOValue:  # From retry_budget.v:17:11
        return await self._thunk()  # From retry_budget.v:17:11

    def bind(
        self, f: Callable[[_IOValue], IO[_IONext]]
    ) -> IO[_IONext]:  # From retry_budget.v:17:11
        async def run_bound() -> _IONext:  # From retry_budget.v:17:11
            value = await self.run()  # From retry_budget.v:17:11
            return await f(value).run()  # From retry_budget.v:17:11

        return IO(run_bound)  # From retry_budget.v:17:11

    @classmethod  # From retry_budget.v:17:11
    def pure(cls, value: _IOValue) -> IO[_IOValue]:  # From retry_budget.v:17:11
        async def run_pure() -> _IOValue:  # From retry_budget.v:17:11
            return value  # From retry_budget.v:17:11

        return IO(run_pure)  # From retry_budget.v:17:11


def coforce(value: Callable[[], _CoForceT]) -> _CoForceT:  # From retry_budget.v:17:11
    return value()  # From retry_budget.v:17:11


def coprefix_eq(
    n: int, left: Iterable[object], right: Iterable[object]
) -> bool:  # From retry_budget.v:17:11
    return tuple(islice(iter(left), n)) == tuple(
        islice(iter(right), n)
    )  # From retry_budget.v:17:11


def coprefix_hash(n: int, value: Iterable[object]) -> int:  # From retry_budget.v:17:11
    return hash(tuple(islice(iter(value), n)))  # From retry_budget.v:17:11


class __ModuleNamespace:  # From retry_budget.v:17:11
    pass  # From retry_budget.v:17:11


def __apply_applicative(
    cache: dict[int, _ModuleRetT],
    build: Callable[[_ModuleArgT], _ModuleRetT],
    arg: _ModuleArgT,
) -> _ModuleRetT:  # From retry_budget.v:17:11
    key = id(arg)  # From retry_budget.v:17:11
    cached = cache.get(key)  # From retry_budget.v:17:11
    if cached is None:  # From retry_budget.v:17:11
        cached = build(arg)  # From retry_budget.v:17:11
        cache[key] = cached  # From retry_budget.v:17:11
    return cached  # From retry_budget.v:17:11


__ = None  # erased logical argument  # From retry_budget.v:17:11
# positive: remapped to Python primitive  # From retry_budget.v:17:11

# N: remapped to Python primitive  # From retry_budget.v:17:11

retry_budget: int = 1 * 2 + 1  # From retry_budget.v:17:11
