# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass, replace
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
    final,
)


max_retries: int = 3


retry_budget: int = 3


def retry_delta(remaining: int) -> int:
    __n = remaining
    if __n == 0:
        return -1
    if __n > 0:
        p = __n
        return p
    return _rocq_numeric_domain_error("N", __n)


backoff_ratio: Fraction = Fraction(1, 2)
