# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
)


# option: remapped to Python primitive


class State:
    pass


@dataclass(frozen=True)
class Running(State):
    pass


@dataclass(frozen=True)
class Syncing(State):
    pass


@dataclass(frozen=True)
class StoppingWorkers(State):
    pass


@dataclass(frozen=True)
class KillingChildren(State):
    pass


@dataclass(frozen=True)
class Exiting(State):
    pass


@dataclass(frozen=True)
class Aborted(State):
    pass


StateT = Running | Syncing | StoppingWorkers | KillingChildren | Exiting | Aborted


class Event:
    pass


@dataclass(frozen=True)
class TriggerRestart(Event):
    pass


@dataclass(frozen=True)
class SyncOk(Event):
    pass


@dataclass(frozen=True)
class SyncFail(Event):
    pass


@dataclass(frozen=True)
class WorkersStopped(Event):
    pass


@dataclass(frozen=True)
class ChildrenKilled(Event):
    pass


EventT = TriggerRestart | SyncOk | SyncFail | WorkersStopped | ChildrenKilled


def transition(
    current: State,
    event0: Event,
) -> State | None:
    match current:
        case Running():
            match event0:
                case TriggerRestart():
                    return Syncing()
                case SyncOk():
                    return None
                case SyncFail():
                    return None
                case WorkersStopped():
                    return None
                case ChildrenKilled():
                    return None
                case __impossible:
                    assert_never(__impossible)
        case Syncing():
            match event0:
                case TriggerRestart():
                    return None
                case SyncOk():
                    return StoppingWorkers()
                case SyncFail():
                    return Aborted()
                case WorkersStopped():
                    return None
                case ChildrenKilled():
                    return None
                case __impossible:
                    assert_never(__impossible)
        case StoppingWorkers():
            match event0:
                case TriggerRestart():
                    return None
                case SyncOk():
                    return None
                case SyncFail():
                    return None
                case WorkersStopped():
                    return KillingChildren()
                case ChildrenKilled():
                    return None
                case __impossible:
                    assert_never(__impossible)
        case KillingChildren():
            match event0:
                case TriggerRestart():
                    return None
                case SyncOk():
                    return None
                case SyncFail():
                    return None
                case WorkersStopped():
                    return None
                case ChildrenKilled():
                    return Exiting()
                case __impossible:
                    assert_never(__impossible)
        case Exiting():
            return None
        case Aborted():
            return None
        case __impossible:
            assert_never(__impossible)
