# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass, replace
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
    final,
)


class ReviewReplyOutcome:
    pass


@final
@dataclass(frozen=True)
class ReviewAct(ReviewReplyOutcome):
    pass


@final
@dataclass(frozen=True)
class ReviewDo(ReviewReplyOutcome):
    pass


@final
@dataclass(frozen=True)
class ReviewAsk(ReviewReplyOutcome):
    pass


@final
@dataclass(frozen=True)
class ReviewAnswer(ReviewReplyOutcome):
    pass


@final
@dataclass(frozen=True)
class ReviewDefer(ReviewReplyOutcome):
    pass


@final
@dataclass(frozen=True)
class ReviewDump(ReviewReplyOutcome):
    pass


ReviewReplyOutcomeT = (
    ReviewAct | ReviewDo | ReviewAsk | ReviewAnswer | ReviewDefer | ReviewDump
)


class Contender:
    pass


@final
@dataclass(frozen=True)
class Handler(Contender):
    pass


@final
@dataclass(frozen=True)
class CronSweep(Contender):
    pass


ContenderT = Handler | CronSweep


class ActiveSlot:
    pass


@final
@dataclass(frozen=True)
class Idle(ActiveSlot):
    pass


@final
@dataclass(frozen=True)
class HolderActive(ActiveSlot):
    c: Contender


@final
@dataclass(frozen=True)
class WorkerActive(ActiveSlot):
    pass


ActiveSlotT = Idle | HolderActive | WorkerActive


@final
@dataclass(frozen=True)
class FifoState:
    fifo_queue: list[Contender]
    fifo_active_slot: ActiveSlot
    fifo_worker_deferred: bool


class Event:
    pass


@final
@dataclass(frozen=True)
class Enqueue(Event):
    c: Contender


@final
@dataclass(frozen=True)
class Dequeue(Event):
    pass


@final
@dataclass(frozen=True)
class WorkerDefer(Event):
    pass


@final
@dataclass(frozen=True)
class WorkerResume(Event):
    pass


@final
@dataclass(frozen=True)
class Release(Event):
    outcome: ReviewReplyOutcome


EventT = Enqueue | Dequeue | WorkerDefer | WorkerResume | Release


def transition(
    s: FifoState,
    event0: Event,
) -> FifoState | None:
    match event0:
        case Enqueue(c):
            match s.fifo_active_slot:
                case Idle():
                    return replace(
                        s,
                        fifo_queue=s.fifo_queue + [c],
                    )
                case HolderActive(c0):
                    return replace(
                        s,
                        fifo_queue=s.fifo_queue + [c],
                    )
                case WorkerActive():
                    return FifoState(
                        fifo_queue=s.fifo_queue + [c],
                        fifo_active_slot=Idle(),
                        fifo_worker_deferred=True,
                    )
                case __impossible:
                    assert_never(__impossible)
        case Dequeue():
            match s.fifo_active_slot:
                case Idle():
                    __list = s.fifo_queue
                    if __list == []:
                        return None
                    c = __list[0]
                    rest = __list[1:]
                    return replace(
                        s,
                        fifo_queue=rest,
                        fifo_active_slot=HolderActive(c),
                    )
                case HolderActive(c):
                    return None
                case WorkerActive():
                    return None
                case __impossible:
                    assert_never(__impossible)
        case WorkerDefer():
            match s.fifo_active_slot:
                case Idle():
                    return None
                case HolderActive(c):
                    return None
                case WorkerActive():
                    return replace(
                        s,
                        fifo_active_slot=Idle(),
                        fifo_worker_deferred=True,
                    )
                case __impossible:
                    assert_never(__impossible)
        case WorkerResume():
            match s.fifo_active_slot:
                case Idle():
                    __list = s.fifo_queue
                    if __list == []:
                        if s.fifo_worker_deferred:
                            return FifoState(
                                fifo_queue=[],
                                fifo_active_slot=WorkerActive(),
                                fifo_worker_deferred=False,
                            )
                        return None
                    c = __list[0]
                    l = __list[1:]
                    return None
                case HolderActive(c):
                    return None
                case WorkerActive():
                    return None
                case __impossible:
                    assert_never(__impossible)
        case Release(outcome):
            match s.fifo_active_slot:
                case Idle():
                    return None
                case HolderActive(c):
                    return replace(
                        s,
                        fifo_active_slot=Idle(),
                    )
                case WorkerActive():
                    return replace(
                        s,
                        fifo_active_slot=Idle(),
                    )
                case __impossible:
                    assert_never(__impossible)
        case __impossible:
            assert_never(__impossible)
