# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
)


class TaskKind:
    pass


@dataclass(frozen=True)
class TaskCI(TaskKind):
    pass


@dataclass(frozen=True)
class TaskThread(TaskKind):
    pass


@dataclass(frozen=True)
class TaskSpec(TaskKind):
    pass


@dataclass(frozen=True)
class TaskAsk(TaskKind):
    pass


@dataclass(frozen=True)
class TaskDefer(TaskKind):
    pass


TaskKindT = TaskCI | TaskThread | TaskSpec | TaskAsk | TaskDefer


class TaskStatus:
    pass


@dataclass(frozen=True)
class StatusPending(TaskStatus):
    pass


@dataclass(frozen=True)
class StatusCompleted(TaskStatus):
    pass


@dataclass(frozen=True)
class StatusBlocked(TaskStatus):
    pass


TaskStatusT = StatusPending | StatusCompleted | StatusBlocked


@dataclass(frozen=True)
class TaskRow:
    task_title: str
    task_description: str
    task_kind: TaskKind
    task_status: TaskStatus
    task_source_comment: int | None

    def row_executable(self) -> bool:
        row = self
        match row.task_status:
            case StatusPending():
                return task_executable(row.task_kind)
            case StatusCompleted():
                return False
            case StatusBlocked():
                return False
            case __impossible:
                assert_never(__impossible)

    def requires_abort(
        self,
        current_row: TaskRow,
    ) -> bool:
        new_row = self
        __option = task_preempt_rank(new_row.task_kind)
        if __option is None:
            return False
        new_rank = __option
        __option = task_preempt_rank(current_row.task_kind)
        if __option is None:
            return False
        current_rank = __option
        return new_rank < current_rank

    def title_changed(
        self,
        after_row: TaskRow,
    ) -> bool:
        before_row = self
        return not (before_row.task_title == after_row.task_title)

    def description_changed(
        self,
        after_row: TaskRow,
    ) -> bool:
        before_row = self
        return not (before_row.task_description == after_row.task_description)

    def metadata_changed(
        self,
        after_row: TaskRow,
    ) -> bool:
        before_row = self
        if before_row.title_changed(after_row):
            return True
        return before_row.description_changed(after_row)

    def identity_changed(
        self,
        after_row: TaskRow,
    ) -> bool:
        before_row = self
        if before_row.title_changed(after_row):
            return True
        before_source = before_row.task_source_comment
        after_source = after_row.task_source_comment
        return task_source_comment_changed(before_source, after_source)


# ExecutionLease: singleton inductive, constructor was Build_ExecutionLease


def lease_task(e: ExecutionLease) -> int:
    lease_task0 = e
    return lease_task0


class RescopeOp:
    pass


@dataclass(frozen=True)
class KeepTask(RescopeOp):
    task: int


@dataclass(frozen=True)
class RewriteTask(RescopeOp):
    task: int
    new_title: str
    new_description: str


@dataclass(frozen=True)
class CompleteTask(RescopeOp):
    task: int


RescopeOpT = KeepTask | RewriteTask | CompleteTask


class RescopeReleaseKind:
    pass


@dataclass(frozen=True)
class ReleaseACT(RescopeReleaseKind):
    pass


@dataclass(frozen=True)
class ReleaseDO(RescopeReleaseKind):
    pass


RescopeReleaseKindT = ReleaseACT | ReleaseDO


@dataclass(frozen=True)
class RescopeRelease:
    release_kind: RescopeReleaseKind
    release_decision: RescopeOp

    def task_id(self) -> int:
        release = self
        return rescope_task_id(release.release_decision)


def task_executable(kind: TaskKind) -> bool:
    match kind:
        case TaskCI():
            return True
        case TaskThread():
            return True
        case TaskSpec():
            return True
        case TaskAsk():
            return False
        case TaskDefer():
            return False
        case __impossible:
            assert_never(__impossible)


def task_kind_is_ci(kind: TaskKind) -> bool:
    match kind:
        case TaskCI():
            return True
        case TaskThread():
            return False
        case TaskSpec():
            return False
        case TaskAsk():
            return False
        case TaskDefer():
            return False
        case __impossible:
            assert_never(__impossible)


def task_kind_is_non_ci(kind: TaskKind) -> bool:
    return not (task_kind_is_ci(kind))


def task_preempt_rank(kind: TaskKind) -> int | None:
    match kind:
        case TaskCI():
            return 0
        case TaskThread():
            return 0 + 1
        case TaskSpec():
            return (0 + 1) + 1
        case TaskAsk():
            return None
        case TaskDefer():
            return None
        case __impossible:
            assert_never(__impossible)


def positive_eqb(
    left: int,
    right: int,
) -> bool:
    return left == right


def positive_mem(
    target: int,
    items: list[int],
) -> bool:
    __list = items
    if __list == []:
        return False
    item = __list[0]
    rest = __list[1:]
    if positive_eqb(target, item):
        return True
    return positive_mem(target, rest)


def find_comment_duplicate(
    comment: int,
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    __list = order
    if __list == []:
        return None
    task = __list[0]
    rest = __list[1:]
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return find_comment_duplicate(
            comment,
            rest,
            rows,
        )
    row = __option
    __option = row.task_source_comment
    if __option is None:
        return find_comment_duplicate(
            comment,
            rest,
            rows,
        )
    existing = __option
    if positive_eqb(existing, comment):
        return task
    return find_comment_duplicate(
        comment,
        rest,
        rows,
    )


def find_pending_title_duplicate(
    title: str,
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    __list = order
    if __list == []:
        return None
    task = __list[0]
    rest = __list[1:]
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return find_pending_title_duplicate(
            title,
            rest,
            rows,
        )
    row = __option
    match row.task_status:
        case StatusPending():
            if row.task_title == title:
                return task
            return find_pending_title_duplicate(
                title,
                rest,
                rows,
            )
        case StatusCompleted():
            return find_pending_title_duplicate(
                title,
                rest,
                rows,
            )
        case StatusBlocked():
            return find_pending_title_duplicate(
                title,
                rest,
                rows,
            )
        case __impossible:
            assert_never(__impossible)


def enqueue_task(
    task: int,
    row: TaskRow,
    order: list[int],
    rows: dict[int, TaskRow],
) -> tuple[tuple[list[int], dict[int, TaskRow]], int]:
    __option = row.task_source_comment
    if __option is None:
        __option = find_pending_title_duplicate(row.task_title, order, rows)
        if __option is None:
            return (
                (
                    order + [task] + [],
                    _rocq_map_add(
                        _rocq_positive_key(task),
                        row,
                        rows,
                    ),
                ),
                task,
            )
        existing = __option
        return (
            (
                order,
                rows,
            ),
            existing,
        )
    comment = __option
    __option = find_comment_duplicate(comment, order, rows)
    if __option is None:
        return (
            (
                order + [task] + [],
                _rocq_map_add(
                    _rocq_positive_key(task),
                    row,
                    rows,
                ),
            ),
            task,
        )
    existing = __option
    return (
        (
            order,
            rows,
        ),
        existing,
    )


def pick_first_ci(
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    __list = order
    if __list == []:
        return None
    task = __list[0]
    rest = __list[1:]
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return pick_first_ci(rest, rows)
    row = __option
    if row.row_executable() and task_kind_is_ci(row.task_kind):
        return task
    return pick_first_ci(rest, rows)


def pick_first_non_ci(
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    __list = order
    if __list == []:
        return None
    task = __list[0]
    rest = __list[1:]
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return pick_first_non_ci(rest, rows)
    row = __option
    if row.row_executable() and task_kind_is_non_ci(row.task_kind):
        return task
    return pick_first_non_ci(rest, rows)


def pick_next_task(
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    __option = pick_first_ci(order, rows)
    if __option is None:
        return pick_first_non_ci(order, rows)
    task = __option
    return task


def begin_task(
    task: int,
    lease: ExecutionLease | None,
    rows: dict[int, TaskRow],
) -> ExecutionLease | None:
    __option = lease
    if __option is None:
        __option = rows.get(_rocq_positive_key(task))
        if __option is None:
            return None
        row = __option
        if row.row_executable():
            return task
        return None
    e = __option
    return None


def clear_matching_lease(
    task: int,
    lease: ExecutionLease | None,
) -> ExecutionLease | None:
    __option = lease
    if __option is None:
        return None
    active = __option
    if positive_eqb(lease_task(active), task):
        return None
    return lease


def complete_task(
    task: int,
    lease: ExecutionLease | None,
    rows: dict[int, TaskRow],
) -> tuple[ExecutionLease | None, dict[int, TaskRow]]:
    lease_ = clear_matching_lease(task, lease)
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return (
            lease_,
            rows,
        )
    row = __option
    row_ = TaskRow(
        task_title=row.task_title,
        task_description=row.task_description,
        task_kind=row.task_kind,
        task_status=StatusCompleted(),
        task_source_comment=row.task_source_comment,
    )
    return (
        lease_,
        _rocq_map_add(
            _rocq_positive_key(task),
            row_,
            rows,
        ),
    )


def abort_task(
    task: int,
    lease: ExecutionLease | None,
) -> ExecutionLease | None:
    __option = lease
    if __option is None:
        return None
    active = __option
    if positive_eqb(lease_task(active), task):
        return None
    return lease


def row_with_status(
    row: TaskRow,
    status: TaskStatus,
) -> TaskRow:
    return TaskRow(
        task_title=row.task_title,
        task_description=row.task_description,
        task_kind=row.task_kind,
        task_status=status,
        task_source_comment=row.task_source_comment,
    )


def unblock_task_row(
    task: int,
    row: TaskRow,
    rows: dict[int, TaskRow],
) -> dict[int, TaskRow]:
    match row.task_status:
        case StatusPending():
            return rows
        case StatusCompleted():
            return rows
        case StatusBlocked():
            return _rocq_map_add(
                _rocq_positive_key(task),
                row_with_status(row, StatusPending()),
                rows,
            )
        case __impossible:
            assert_never(__impossible)


def unblock_task_if_present(
    task: int,
    rows: dict[int, TaskRow],
) -> dict[int, TaskRow]:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return rows
    row = __option
    return unblock_task_row(
        task,
        row,
        rows,
    )


def unblock_task_rows(
    order: list[int],
    rows: dict[int, TaskRow],
) -> dict[int, TaskRow]:
    __list = order
    if __list == []:
        return rows
    task = __list[0]
    rest = __list[1:]
    return unblock_task_rows(rest, unblock_task_if_present(task, rows))


def unblock_tasks(
    order: list[int],
    rows: dict[int, TaskRow],
) -> dict[int, TaskRow]:
    return unblock_task_rows(order, rows)


def rescope_task_id(op: RescopeOp) -> int:
    match op:
        case KeepTask(task):
            return task
        case RewriteTask(task, new_title, new_description):
            return task
        case CompleteTask(task):
            return task
        case __impossible:
            assert_never(__impossible)


def op_covers_task(
    task: int,
    ops: list[RescopeOp],
) -> bool:
    __list = ops
    if __list == []:
        return False
    op = __list[0]
    rest = __list[1:]
    if positive_eqb(rescope_task_id(op), task):
        return True
    return op_covers_task(task, rest)


def rescope_ops_cover_snapshot(
    snapshot_order: list[int],
    ops: list[RescopeOp],
) -> bool:
    __list = snapshot_order
    if __list == []:
        return True
    task = __list[0]
    rest = __list[1:]
    if op_covers_task(task, ops):
        return rescope_ops_cover_snapshot(rest, ops)
    return False


def release_for_task(
    task: int,
    releases: list[RescopeRelease],
) -> RescopeOp | None:
    __list = releases
    if __list == []:
        return None
    release = __list[0]
    rest = __list[1:]
    if positive_eqb(release.task_id(), task):
        return release.release_decision
    return release_for_task(task, rest)


def normalize_rescope_batch(
    snapshot_order: list[int],
    releases: list[RescopeRelease],
) -> list[RescopeOp]:
    __list = snapshot_order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    rest_ = normalize_rescope_batch(rest, releases)
    __option = release_for_task(task, releases)
    if __option is None:
        return rest_
    op = __option
    return [op] + rest_


def apply_rescope_ops(
    ops: list[RescopeOp],
    rows: dict[int, TaskRow],
    pending_ids: list[int],
    completed_ids: list[int],
) -> tuple[tuple[dict[int, TaskRow], list[int]], list[int]]:
    __list = ops
    if __list == []:
        return (
            (
                rows,
                pending_ids,
            ),
            completed_ids,
        )
    op = __list[0]
    rest = __list[1:]
    task = rescope_task_id(op)
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return apply_rescope_ops(
            rest,
            rows,
            pending_ids,
            completed_ids,
        )
    row = __option
    match op:
        case KeepTask(task0):
            match row.task_status:
                case StatusPending():
                    return apply_rescope_ops(
                        rest,
                        rows,
                        pending_ids + [task] + [],
                        completed_ids,
                    )
                case StatusCompleted():
                    return apply_rescope_ops(
                        rest,
                        rows,
                        pending_ids,
                        completed_ids,
                    )
                case StatusBlocked():
                    return apply_rescope_ops(
                        rest,
                        rows,
                        pending_ids + [task] + [],
                        completed_ids,
                    )
                case __impossible:
                    assert_never(__impossible)
        case RewriteTask(task0, title, description):
            match row.task_status:
                case StatusPending():
                    row_ = TaskRow(
                        task_title=row.task_title,
                        task_description=description,
                        task_kind=row.task_kind,
                        task_status=row.task_status,
                        task_source_comment=row.task_source_comment,
                    )
                    return apply_rescope_ops(
                        rest,
                        _rocq_map_add(
                            _rocq_positive_key(task),
                            row_,
                            rows,
                        ),
                        pending_ids + [task] + [],
                        completed_ids,
                    )
                case StatusCompleted():
                    return apply_rescope_ops(
                        rest,
                        rows,
                        pending_ids,
                        completed_ids,
                    )
                case StatusBlocked():
                    row_ = TaskRow(
                        task_title=row.task_title,
                        task_description=description,
                        task_kind=row.task_kind,
                        task_status=row.task_status,
                        task_source_comment=row.task_source_comment,
                    )
                    return apply_rescope_ops(
                        rest,
                        _rocq_map_add(
                            _rocq_positive_key(task),
                            row_,
                            rows,
                        ),
                        pending_ids + [task] + [],
                        completed_ids,
                    )
                case __impossible:
                    assert_never(__impossible)
        case CompleteTask(task0):
            match row.task_status:
                case StatusPending():
                    row_ = TaskRow(
                        task_title=row.task_title,
                        task_description=row.task_description,
                        task_kind=row.task_kind,
                        task_status=StatusCompleted(),
                        task_source_comment=row.task_source_comment,
                    )
                    return apply_rescope_ops(
                        rest,
                        _rocq_map_add(
                            _rocq_positive_key(task),
                            row_,
                            rows,
                        ),
                        pending_ids,
                        completed_ids + [task] + [],
                    )
                case StatusCompleted():
                    return apply_rescope_ops(
                        rest,
                        rows,
                        pending_ids,
                        completed_ids,
                    )
                case StatusBlocked():
                    row_ = TaskRow(
                        task_title=row.task_title,
                        task_description=row.task_description,
                        task_kind=row.task_kind,
                        task_status=StatusCompleted(),
                        task_source_comment=row.task_source_comment,
                    )
                    return apply_rescope_ops(
                        rest,
                        _rocq_map_add(
                            _rocq_positive_key(task),
                            row_,
                            rows,
                        ),
                        pending_ids,
                        completed_ids + [task] + [],
                    )
                case __impossible:
                    assert_never(__impossible)
        case __impossible:
            assert_never(__impossible)


def completed_tasks_in_order(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    __list = order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return completed_tasks_in_order(rest, rows)
    row = __option
    match row.task_status:
        case StatusPending():
            return completed_tasks_in_order(rest, rows)
        case StatusCompleted():
            return [task] + completed_tasks_in_order(rest, rows)
        case StatusBlocked():
            return completed_tasks_in_order(rest, rows)
        case __impossible:
            assert_never(__impossible)


def preserve_newly_added(
    snapshot_order: list[int],
    current_order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    __list = current_order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    rest_ = preserve_newly_added(
        snapshot_order,
        rest,
        rows,
    )
    if positive_mem(task, snapshot_order):
        return rest_
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return rest_
    row = __option
    match row.task_status:
        case StatusPending():
            return [task] + rest_
        case StatusCompleted():
            return rest_
        case StatusBlocked():
            return [task] + rest_
        case __impossible:
            assert_never(__impossible)


def task_is_ci(
    rows: dict[int, TaskRow],
    task: int,
) -> bool:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return False
    row = __option
    return task_kind_is_ci(row.task_kind)


def task_is_non_ci(
    rows: dict[int, TaskRow],
    task: int,
) -> bool:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return False
    row = __option
    return task_kind_is_non_ci(row.task_kind)


def collect_ci_tasks(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    __list = order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    rest_ = collect_ci_tasks(rest, rows)
    if task_is_ci(rows, task):
        return [task] + rest_
    return rest_


def collect_non_ci_tasks(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    __list = order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    rest_ = collect_non_ci_tasks(rest, rows)
    if task_is_non_ci(rows, task):
        return [task] + rest_
    return rest_


def stable_ci_first(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    ci = collect_ci_tasks(order, rows)
    non_ci = collect_non_ci_tasks(order, rows)
    return ci + non_ci


def option_positive_eqb(
    left: int | None,
    right: int | None,
) -> bool:
    __option = left
    if __option is None:
        __option = right
        if __option is None:
            return True
        p = __option
        return False
    l = __option
    __option = right
    if __option is None:
        return False
    r = __option
    return positive_eqb(l, r)


def task_source_comment_changed(
    before_source: int | None,
    after_source: int | None,
) -> bool:
    return not (option_positive_eqb(before_source, after_source))


def rescope_preserves_task_identity(
    snapshot_order: list[int],
    rows_before: dict[int, TaskRow],
    rows_after: dict[int, TaskRow],
) -> bool:
    __list = snapshot_order
    if __list == []:
        return True
    task = __list[0]
    rest = __list[1:]
    __option = rows_before.get(_rocq_positive_key(task))
    if __option is None:
        return rescope_preserves_task_identity(
            rest,
            rows_before,
            rows_after,
        )
    before_row = __option
    __option = rows_after.get(_rocq_positive_key(task))
    if __option is None:
        return False
    after_row = __option
    if before_row.identity_changed(after_row):
        return False
    return rescope_preserves_task_identity(
        rest,
        rows_before,
        rows_after,
    )


def apply_rescope(
    snapshot_order: list[int],
    current_order: list[int],
    rows: dict[int, TaskRow],
    ops: list[RescopeOp],
) -> tuple[list[int], dict[int, TaskRow]]:
    __pair = apply_rescope_ops(ops, rows, [], [])
    p = __pair[0]
    newly_completed = __pair[1]
    __pair = p
    rows_ = __pair[0]
    pending_ids = __pair[1]
    completed_existing = completed_tasks_in_order(current_order, rows)
    newly_added = preserve_newly_added(
        snapshot_order,
        current_order,
        rows_,
    )
    pending_order = stable_ci_first(pending_ids, rows_)
    return (
        pending_order + completed_existing + newly_completed + newly_added,
        rows_,
    )


def apply_batched_rescope(
    snapshot_order: list[int],
    current_order: list[int],
    rows: dict[int, TaskRow],
    releases: list[RescopeRelease],
) -> tuple[list[int], dict[int, TaskRow]]:
    ops = normalize_rescope_batch(snapshot_order, releases)
    return apply_rescope(
        snapshot_order,
        current_order,
        rows,
        ops,
    )


def rescope_affects_active_task(
    lease: ExecutionLease | None,
    rows_before: dict[int, TaskRow],
    rows_after: dict[int, TaskRow],
) -> bool:
    __option = lease
    if __option is None:
        return False
    active = __option
    __option = rows_before.get(_rocq_positive_key(lease_task(active)))
    if __option is None:
        return False
    before_row = __option
    __option = rows_after.get(_rocq_positive_key(lease_task(active)))
    if __option is None:
        return True
    after_row = __option
    match after_row.task_status:
        case StatusPending():
            return before_row.metadata_changed(after_row)
        case StatusCompleted():
            return True
        case StatusBlocked():
            return before_row.metadata_changed(after_row)
        case __impossible:
            assert_never(__impossible)


def should_abort_for_new_task(
    new_task: int,
    lease: ExecutionLease | None,
    rows: dict[int, TaskRow],
) -> bool:
    __option = lease
    if __option is None:
        return False
    active = __option
    if positive_eqb(new_task, lease_task(active)):
        return False
    __option = rows.get(_rocq_positive_key(new_task))
    if __option is None:
        return False
    new_row = __option
    __option = rows.get(_rocq_positive_key(lease_task(active)))
    if __option is None:
        return False
    current_row = __option
    return new_row.requires_abort(current_row)


def complete_task_visible(
    task: int,
    rows: dict[int, TaskRow],
) -> tuple[dict[int, TaskRow], int | None]:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return (
            rows,
            None,
        )
    row = __option
    match row.task_status:
        case StatusPending():
            row_ = row_with_status(row, StatusCompleted())
            return (
                _rocq_map_add(
                    _rocq_positive_key(task),
                    row_,
                    rows,
                ),
                row.task_source_comment,
            )
        case StatusCompleted():
            return (
                rows,
                None,
            )
        case StatusBlocked():
            row_ = row_with_status(row, StatusCompleted())
            return (
                _rocq_map_add(
                    _rocq_positive_key(task),
                    row_,
                    rows,
                ),
                row.task_source_comment,
            )
        case __impossible:
            assert_never(__impossible)


class TaskChange:
    pass


@dataclass(frozen=True)
class TaskCompleted(TaskChange):
    task: int


@dataclass(frozen=True)
class TaskCancelled(TaskChange):
    task: int


@dataclass(frozen=True)
class TaskModified(TaskChange):
    task: int
    new_title: str
    new_description: str


TaskChangeT = TaskCompleted | TaskCancelled | TaskModified


def task_change(
    task: int,
    rows_before: dict[int, TaskRow],
    rows_after: dict[int, TaskRow],
) -> TaskChange | None:
    __option = rows_before.get(_rocq_positive_key(task))
    if __option is None:
        return None
    before_row = __option
    __option = before_row.task_source_comment
    if __option is None:
        return None
    p = __option
    match before_row.task_status:
        case StatusPending():
            __option = rows_after.get(_rocq_positive_key(task))
            if __option is None:
                return TaskCancelled(task)
            after_row = __option
            match after_row.task_status:
                case StatusPending():
                    if before_row.metadata_changed(after_row):
                        return TaskModified(
                            task,
                            after_row.task_title,
                            after_row.task_description,
                        )
                    return None
                case StatusCompleted():
                    return TaskCompleted(task)
                case StatusBlocked():
                    if before_row.metadata_changed(after_row):
                        return TaskModified(
                            task,
                            after_row.task_title,
                            after_row.task_description,
                        )
                    return None
                case __impossible:
                    assert_never(__impossible)
        case StatusCompleted():
            return None
        case StatusBlocked():
            __option = rows_after.get(_rocq_positive_key(task))
            if __option is None:
                return TaskCancelled(task)
            after_row = __option
            match after_row.task_status:
                case StatusPending():
                    if before_row.metadata_changed(after_row):
                        return TaskModified(
                            task,
                            after_row.task_title,
                            after_row.task_description,
                        )
                    return None
                case StatusCompleted():
                    return TaskCompleted(task)
                case StatusBlocked():
                    if before_row.metadata_changed(after_row):
                        return TaskModified(
                            task,
                            after_row.task_title,
                            after_row.task_description,
                        )
                    return None
                case __impossible:
                    assert_never(__impossible)
        case __impossible:
            assert_never(__impossible)


def compute_task_changes(
    snapshot_order: list[int],
    rows_before: dict[int, TaskRow],
    rows_after: dict[int, TaskRow],
) -> list[TaskChange]:
    __list = snapshot_order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    rest_ = compute_task_changes(
        rest,
        rows_before,
        rows_after,
    )
    __option = task_change(task, rows_before, rows_after)
    if __option is None:
        return rest_
    change = __option
    return [change] + rest_


def task_changes_materially_significant(changes: list[TaskChange]) -> bool:
    __list = changes
    if __list == []:
        return False
    t0 = __list[0]
    l = __list[1:]
    return True


def batched_rescope_materially_significant(
    snapshot_order: list[int],
    current_order: list[int],
    rows: dict[int, TaskRow],
    releases: list[RescopeRelease],
) -> bool:
    __pair = apply_batched_rescope(snapshot_order, current_order, rows, releases)
    l = __pair[0]
    rows_after = __pair[1]
    changes = compute_task_changes(
        snapshot_order,
        rows,
        rows_after,
    )
    return task_changes_materially_significant(changes)


def remove_from_order(
    task: int,
    order: list[int],
) -> list[int]:
    __list = order
    if __list == []:
        return []
    t0 = __list[0]
    rest = __list[1:]
    rest_ = remove_from_order(task, rest)
    if positive_eqb(t0, task):
        return rest_
    return [t0] + rest_


def cleanup_aborted_task(
    task: int,
    lease: ExecutionLease | None,
    order: list[int],
    rows: dict[int, TaskRow],
) -> tuple[tuple[ExecutionLease | None, list[int]], dict[int, TaskRow]]:
    lease_ = clear_matching_lease(task, lease)
    order_ = remove_from_order(task, order)
    rows_ = _rocq_map_remove(
        _rocq_positive_key(task),
        rows,
    )
    return (
        (
            lease_,
            order_,
        ),
        rows_,
    )


def task_still_pending(
    task: int,
    rows: dict[int, TaskRow],
) -> bool:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return False
    row = __option
    match row.task_status:
        case StatusPending():
            return True
        case StatusCompleted():
            return False
        case StatusBlocked():
            return False
        case __impossible:
            assert_never(__impossible)
