# Generated by rocq-python-extraction (target: Python 3.14t)
import asyncio
import queue
import threading
from contextlib import asynccontextmanager
from concurrent.futures import Future as _ConcurrentFuture
from itertools import islice
from dataclasses import dataclass
from fractions import Fraction
from typing import (
    Any,
    AsyncIterator,
    Awaitable,
    Callable,
    Generic,
    Iterable,
    Iterator,
    Never,
    Protocol,
    TypeVar,
    assert_never,
    cast,
)

_CoForceT = TypeVar("_CoForceT")
_ModuleArgT = TypeVar("_ModuleArgT")
_ModuleRetT = TypeVar("_ModuleRetT")
_StateTState = TypeVar("_StateTState")
_StateTValue = TypeVar("_StateTValue")
_StateTNext = TypeVar("_StateTNext")
_IOValue = TypeVar("_IOValue")
_IONext = TypeVar("_IONext")
_IOOwner = TypeVar("_IOOwner")
_ChannelValue = TypeVar("_ChannelValue")
_FutureValue = TypeVar("_FutureValue")


class _Impossible(RuntimeError):
    pass


def _impossible() -> Never:
    raise _Impossible()


class _RocqUtf8BoundaryError(UnicodeError):
    pass


class _RocqNumericDomainError(ValueError):
    pass


def _rocq_numeric_domain_error(kind: str, value: object) -> Never:
    raise _RocqNumericDomainError(f"Rocq {kind} value out of domain: {value!r}")


key = int  # finite-map module key alias
elt = int  # finite-set module element alias


def _rocq_positive_key(key: int) -> int:
    if key <= 0:
        raise _RocqNumericDomainError("positive map/set key", key)
    return key


def _rocq_string_key(key: str) -> str:
    if not isinstance(key, str):
        raise TypeError(f"Rocq string map/set key must be str: {key!r}")
    return key


def _rocq_sorted_key(key: object) -> Any:
    return key.encode("utf-8") if isinstance(key, str) else key


def _rocq_map_add(
    key: object, value: object, mapping: dict[object, object]
) -> dict[object, object]:
    result = dict(mapping)
    result[key] = value
    return result


def _rocq_map_remove(
    key: object, mapping: dict[object, object]
) -> dict[object, object]:
    result = dict(mapping)
    result.pop(key, None)
    return result


def _rocq_map_elements(mapping: dict[object, object]) -> list[tuple[object, object]]:
    return sorted(mapping.items(), key=lambda item: _rocq_sorted_key(item[0]))


def _rocq_map_fold(
    function: Callable[[object, object, object], object],
    mapping: dict[object, object],
    initial: object,
) -> object:
    result = initial
    for key, value in _rocq_map_elements(mapping):
        result = function(key, value, result)
    return result


def _rocq_set_add(key: object, values: frozenset[object]) -> frozenset[object]:
    return frozenset((*values, key))


def _rocq_set_remove(key: object, values: frozenset[object]) -> frozenset[object]:
    return frozenset(value for value in values if value != key)


def _rocq_set_elements(values: frozenset[object]) -> list[object]:
    return sorted(values, key=_rocq_sorted_key)


def _rocq_set_fold(
    function: Callable[[object, object], object],
    values: frozenset[object],
    initial: object,
) -> object:
    result = initial
    for value in _rocq_set_elements(values):
        result = function(value, result)
    return result


def _rocq_string_cons(head: int, tail: str) -> str:
    try:
        return bytes([head]).decode("utf-8") + tail
    except UnicodeDecodeError as exc:
        raise _RocqUtf8BoundaryError(
            "Rocq string split crosses a UTF-8 boundary"
        ) from exc


def _rocq_string_uncons(value: str) -> tuple[int, str]:
    encoded = value.encode("utf-8")
    if not encoded:
        raise _Impossible()
    try:
        tail = encoded[1:].decode("utf-8")
    except UnicodeDecodeError as exc:
        raise _RocqUtf8BoundaryError(
            "Rocq string split crosses a UTF-8 boundary"
        ) from exc
    return encoded[0], tail


def _rocq_ascii_to_int(
    b0: bool,
    b1: bool,
    b2: bool,
    b3: bool,
    b4: bool,
    b5: bool,
    b6: bool,
    b7: bool,
) -> int:
    return sum(
        (1 << i) for i, bit in enumerate((b0, b1, b2, b3, b4, b5, b6, b7)) if bit
    )


def _rocq_ascii_bits(
    value: int,
) -> tuple[bool, bool, bool, bool, bool, bool, bool, bool]:
    if value < 0 or value > 255:
        raise ValueError("Rocq byte/ascii value out of range")
    return cast(
        tuple[bool, bool, bool, bool, bool, bool, bool, bool],
        tuple(bool(value & (1 << i)) for i in range(8)),
    )


class StateT(Generic[_StateTState, _StateTValue]):
    def __init__(
        self,
        step: Callable[[_StateTState], tuple[_StateTValue, _StateTState]],
        state: _StateTState | None = None,
    ) -> None:
        self._step = step
        self.state = state

    def run(self, state: _StateTState) -> _StateTValue:
        value, next_state = self._step(state)
        self.state = next_state
        return value

    def run_with_state(self, state: _StateTState) -> tuple[_StateTValue, _StateTState]:
        result = self._step(state)
        self.state = result[1]
        return result

    def bind(
        self,
        f: Callable[[_StateTValue], StateT[_StateTState, _StateTNext]],
    ) -> StateT[_StateTState, _StateTNext]:
        def run_bound(state: _StateTState) -> tuple[_StateTNext, _StateTState]:
            value, next_state = self._step(state)
            return f(value).run_with_state(next_state)

        return StateT(run_bound, self.state)

    @classmethod
    def pure(cls, value: _StateTValue) -> StateT[_StateTState, _StateTValue]:
        return StateT(lambda state: (value, state))

    @classmethod
    def get_state(cls) -> StateT[_StateTState, _StateTState]:
        return StateT(lambda state: (state, state))

    @classmethod
    def put_state(cls, new_state: _StateTState) -> StateT[_StateTState, None]:
        return StateT(lambda _state: (None, new_state))


class IO(Generic[_IOValue]):
    def __init__(self, thunk: Callable[[], Awaitable[_IOValue]]) -> None:
        self._thunk = thunk

    async def run(self) -> _IOValue:
        return await self._thunk()

    def bind(self, f: Callable[[_IOValue], IO[_IONext]]) -> IO[_IONext]:
        async def run_bound() -> _IONext:
            value = await self.run()
            return await f(value).run()

        return IO(run_bound)

    @classmethod
    def pure(cls, value: _IOValue) -> IO[_IOValue]:
        async def run_pure() -> _IOValue:
            return value

        return IO(run_pure)

    @classmethod
    def from_sync(cls, thunk: Callable[[], _IOValue]) -> IO[_IOValue]:
        async def run_sync() -> _IOValue:
            return thunk()

        return IO(run_sync)

    @classmethod
    def from_blocking(cls, thunk: Callable[[], _IOValue]) -> IO[_IOValue]:
        async def run_blocking() -> _IOValue:
            return await asyncio.to_thread(thunk)

        return IO(run_blocking)

    @classmethod
    @asynccontextmanager
    async def ownership(
        cls,
        acquire: IO[_IOOwner],
        release: Callable[[_IOOwner], IO[None]],
    ) -> AsyncIterator[_IOOwner]:
        owner = await acquire.run()
        try:
            yield owner
        finally:
            await release(owner).run()

    @classmethod
    def bracket(
        cls,
        acquire: IO[_IOOwner],
        release: Callable[[_IOOwner], IO[None]],
        use: Callable[[_IOOwner], IO[_IONext]],
    ) -> IO[_IONext]:
        async def run_bracket() -> _IONext:
            async with cls.ownership(acquire, release) as owner:
                return await use(owner).run()

        return IO(run_bracket)


class Mutex:
    """Explicit threading mutex wrapper for extracted coordination models.

    This wrapper exposes Python's lock behavior; it does not prove fairness,
    starvation freedom, or a Rocq-level scheduler semantics.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()

    @classmethod
    def new(cls) -> IO[Mutex]:
        return IO.from_sync(cls)

    def acquire(self) -> IO[None]:
        def lock() -> None:
            self._lock.acquire()

        return IO.from_blocking(lock)

    def release(self) -> IO[None]:
        def unlock() -> None:
            self._lock.release()

        return IO.from_sync(unlock)


class Channel(Generic[_ChannelValue]):
    """Explicit FIFO channel wrapper backed by queue.SimpleQueue.

    FIFO order is for completed sends observed by this queue.  This wrapper
    does not model scheduler fairness, producer/consumer races, or cancellation.
    """

    def __init__(self) -> None:
        self._queue: queue.SimpleQueue[_ChannelValue] = queue.SimpleQueue()

    @classmethod
    def new(cls) -> IO[Channel[_ChannelValue]]:
        return IO.from_sync(cls)

    def send(self, value: _ChannelValue) -> IO[None]:
        def put() -> None:
            self._queue.put(value)

        return IO.from_sync(put)

    def receive(self) -> IO[_ChannelValue]:
        return IO.from_blocking(self._queue.get)


class Future(Generic[_FutureValue]):
    """Explicit future wrapper backed by concurrent.futures.Future.

    Completion follows Python Future semantics: result blocks until completed,
    double completion raises, and no Rocq-level thread interleaving is implied.
    """

    def __init__(self) -> None:
        self._future: _ConcurrentFuture[_FutureValue] = _ConcurrentFuture()

    @classmethod
    def new(cls) -> IO[Future[_FutureValue]]:
        return IO.from_sync(cls)

    def set_result(self, value: _FutureValue) -> IO[None]:
        def set_value() -> None:
            self._future.set_result(value)

        return IO.from_sync(set_value)

    def result(self) -> IO[_FutureValue]:
        return IO.from_blocking(self._future.result)

    def done(self) -> bool:
        return self._future.done()


def coforce(value: Callable[[], _CoForceT]) -> _CoForceT:
    return value()


def coprefix_eq(n: int, left: Iterable[object], right: Iterable[object]) -> bool:
    return tuple(islice(iter(left), n)) == tuple(islice(iter(right), n))


def coprefix_hash(n: int, value: Iterable[object]) -> int:
    return hash(tuple(islice(iter(value), n)))


class __ModuleNamespace:
    pass


def __apply_applicative(
    cache: dict[int, _ModuleRetT],
    build: Callable[[_ModuleArgT], _ModuleRetT],
    arg: _ModuleArgT,
) -> _ModuleRetT:
    key = id(arg)
    cached = cache.get(key)
    if cached is None:
        cached = build(arg)
        cache[key] = cached
    return cached


__ = None  # erased logical argument


# bool: remapped to Python primitive


def andb(
    b1: bool,
    b2: bool,
) -> bool:
    if b1:
        return b2
    return False


def negb(b: bool) -> bool:
    if b:
        return False
    return True


# nat: remapped to Python primitive
_A = TypeVar("_A")


# option: remapped to Python primitive
_A = TypeVar("_A")
_B = TypeVar("_B")


# prod: remapped to Python primitive
_A = TypeVar("_A")


# list: remapped to Python primitive


def eqb(
    b1: bool,
    b2: bool,
) -> bool:
    if b1:
        if b2:
            return True
        return False
    if b2:
        return False
    return True


# positive: remapped to Python primitive


class Pos_Module(Protocol):
    @property
    def eqb(self) -> Callable[[int], Callable[[int], bool]]: ...


__Pos_value: Any = __ModuleNamespace()
__Pos_value.eqb = eqb
Pos: Pos_Module = cast(Pos_Module, __Pos_value)


# ascii: remapped to Python primitive
# string: remapped to Python primitive


class TaskKind:
    pass


@dataclass(frozen=True)
class TaskCI(TaskKind):
    pass


@dataclass(frozen=True)
class TaskThread(TaskKind):
    pass


@dataclass(frozen=True)
class TaskSpec(TaskKind):
    pass


@dataclass(frozen=True)
class TaskAsk(TaskKind):
    pass


@dataclass(frozen=True)
class TaskDefer(TaskKind):
    pass


TaskKindT = TaskCI | TaskThread | TaskSpec | TaskAsk | TaskDefer


class TaskStatus:
    pass


@dataclass(frozen=True)
class StatusPending(TaskStatus):
    pass


@dataclass(frozen=True)
class StatusCompleted(TaskStatus):
    pass


@dataclass(frozen=True)
class StatusBlocked(TaskStatus):
    pass


TaskStatusT = StatusPending | StatusCompleted | StatusBlocked


@dataclass(frozen=True)
class TaskRow:
    task_title: str
    task_description: str
    task_kind: TaskKind
    task_status: TaskStatus
    task_source_comment: int | None

    def row_executable(self) -> bool:
        row = self
        match task_status(row):
            case StatusPending():
                return task_executable(task_kind(row))
            case StatusCompleted():
                return False
            case StatusBlocked():
                return False
            case __impossible:
                assert_never(__impossible)

    def requires_abort(
        self,
        current_row: TaskRow,
    ) -> bool:
        new_row = self
        __option = task_preempt_rank(task_kind(new_row))
        if __option is None:
            return False
        new_rank = __option
        __option = task_preempt_rank(task_kind(current_row))
        if __option is None:
            return False
        current_rank = __option
        return new_rank < current_rank

    def title_changed(
        self,
        after_row: TaskRow,
    ) -> bool:
        before_row = self
        return negb(task_title(before_row) == task_title(after_row))

    def description_changed(
        self,
        after_row: TaskRow,
    ) -> bool:
        before_row = self
        return negb(task_description(before_row) == task_description(after_row))

    def metadata_changed(
        self,
        after_row: TaskRow,
    ) -> bool:
        before_row = self
        if before_row.title_changed(after_row):
            return True
        return before_row.description_changed(after_row)


def task_title(t0: TaskRow) -> str:
    return t0.task_title


def task_description(t0: TaskRow) -> str:
    return t0.task_description


def task_kind(t0: TaskRow) -> TaskKind:
    return t0.task_kind


def task_status(t0: TaskRow) -> TaskStatus:
    return t0.task_status


def task_source_comment(t0: TaskRow) -> int | None:
    return t0.task_source_comment


# ExecutionLease: singleton inductive, constructor was Build_ExecutionLease


def lease_task(e: ExecutionLease) -> int:
    lease_task0 = e
    return lease_task0


class RescopeOp:
    pass


@dataclass(frozen=True)
class KeepTask(RescopeOp):
    arg0: int


@dataclass(frozen=True)
class RewriteTask(RescopeOp):
    arg0: int
    arg1: str
    arg2: str


@dataclass(frozen=True)
class CompleteTask(RescopeOp):
    arg0: int


RescopeOpT = KeepTask | RewriteTask | CompleteTask


def task_executable(kind: TaskKind) -> bool:
    match kind:
        case TaskCI():
            return True
        case TaskThread():
            return True
        case TaskSpec():
            return True
        case TaskAsk():
            return False
        case TaskDefer():
            return False
        case __impossible:
            assert_never(__impossible)


def task_kind_is_ci(kind: TaskKind) -> bool:
    match kind:
        case TaskCI():
            return True
        case TaskThread():
            return False
        case TaskSpec():
            return False
        case TaskAsk():
            return False
        case TaskDefer():
            return False
        case __impossible:
            assert_never(__impossible)


def task_kind_is_non_ci(kind: TaskKind) -> bool:
    return negb(task_kind_is_ci(kind))


def task_preempt_rank(kind: TaskKind) -> int | None:
    match kind:
        case TaskCI():
            return 0
        case TaskThread():
            return 0 + 1
        case TaskSpec():
            return (0 + 1) + 1
        case TaskAsk():
            return None
        case TaskDefer():
            return None
        case __impossible:
            assert_never(__impossible)


def positive_eqb(
    left: int,
    right: int,
) -> bool:
    return left == right


def positive_mem(
    target: int,
    items: list[int],
) -> bool:
    __list = items
    if __list == []:
        return False
    item = __list[0]
    rest = __list[1:]
    if positive_eqb(target, item):
        return True
    return positive_mem(target, rest)


def find_comment_duplicate(
    comment: int,
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    __list = order
    if __list == []:
        return None
    task = __list[0]
    rest = __list[1:]
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return find_comment_duplicate(
            comment,
            rest,
            rows,
        )
    row = __option
    __option = task_source_comment(row)
    if __option is None:
        return find_comment_duplicate(
            comment,
            rest,
            rows,
        )
    existing = __option
    if positive_eqb(existing, comment):
        return task
    return find_comment_duplicate(
        comment,
        rest,
        rows,
    )


def find_pending_title_duplicate(
    title: str,
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    __list = order
    if __list == []:
        return None
    task = __list[0]
    rest = __list[1:]
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return find_pending_title_duplicate(
            title,
            rest,
            rows,
        )
    row = __option
    match task_status(row):
        case StatusPending():
            if task_title(row) == title:
                return task
            return find_pending_title_duplicate(
                title,
                rest,
                rows,
            )
        case StatusCompleted():
            return find_pending_title_duplicate(
                title,
                rest,
                rows,
            )
        case StatusBlocked():
            return find_pending_title_duplicate(
                title,
                rest,
                rows,
            )
        case __impossible:
            assert_never(__impossible)


def enqueue_task(
    task: int,
    row: TaskRow,
    order: list[int],
    rows: dict[int, TaskRow],
) -> tuple[tuple[list[int], dict[int, TaskRow]], int]:
    __option = task_source_comment(row)
    if __option is None:
        __option = find_pending_title_duplicate(task_title(row), order, rows)
        if __option is None:
            return (
                (
                    order + [task] + [],
                    _rocq_map_add(
                        _rocq_positive_key(task),
                        row,
                        rows,
                    ),
                ),
                task,
            )
        existing = __option
        return (
            (
                order,
                rows,
            ),
            existing,
        )
    comment = __option
    __option = find_comment_duplicate(comment, order, rows)
    if __option is None:
        return (
            (
                order + [task] + [],
                _rocq_map_add(
                    _rocq_positive_key(task),
                    row,
                    rows,
                ),
            ),
            task,
        )
    existing = __option
    return (
        (
            order,
            rows,
        ),
        existing,
    )


def pick_first_ci(
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    __list = order
    if __list == []:
        return None
    task = __list[0]
    rest = __list[1:]
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return pick_first_ci(rest, rows)
    row = __option
    if andb(row.row_executable(), task_kind_is_ci(task_kind(row))):
        return task
    return pick_first_ci(rest, rows)


def pick_first_non_ci(
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    __list = order
    if __list == []:
        return None
    task = __list[0]
    rest = __list[1:]
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return pick_first_non_ci(rest, rows)
    row = __option
    if andb(row.row_executable(), task_kind_is_non_ci(task_kind(row))):
        return task
    return pick_first_non_ci(rest, rows)


def pick_next_task(
    order: list[int],
    rows: dict[int, TaskRow],
) -> int | None:
    __option = pick_first_ci(order, rows)
    if __option is None:
        return pick_first_non_ci(order, rows)
    task = __option
    return task


def begin_task(
    task: int,
    lease: ExecutionLease | None,
    rows: dict[int, TaskRow],
) -> ExecutionLease | None:
    __option = lease
    if __option is None:
        __option = rows.get(_rocq_positive_key(task))
        if __option is None:
            return None
        row = __option
        if row.row_executable():
            return task
        return None
    e = __option
    return None


def clear_matching_lease(
    task: int,
    lease: ExecutionLease | None,
) -> ExecutionLease | None:
    __option = lease
    if __option is None:
        return None
    active = __option
    if positive_eqb(lease_task(active), task):
        return None
    return lease


def complete_task(
    task: int,
    lease: ExecutionLease | None,
    rows: dict[int, TaskRow],
) -> tuple[ExecutionLease | None, dict[int, TaskRow]]:
    lease_ = clear_matching_lease(task, lease)
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return (
            lease_,
            rows,
        )
    row = __option
    row_ = TaskRow(
        task_title=task_title(row),
        task_description=task_description(row),
        task_kind=task_kind(row),
        task_status=StatusCompleted(),
        task_source_comment=task_source_comment(row),
    )
    return (
        lease_,
        _rocq_map_add(
            _rocq_positive_key(task),
            row_,
            rows,
        ),
    )


def abort_task(
    task: int,
    lease: ExecutionLease | None,
) -> ExecutionLease | None:
    __option = lease
    if __option is None:
        return None
    active = __option
    if positive_eqb(lease_task(active), task):
        return None
    return lease


def row_with_status(
    row: TaskRow,
    status: TaskStatus,
) -> TaskRow:
    return TaskRow(
        task_title=task_title(row),
        task_description=task_description(row),
        task_kind=task_kind(row),
        task_status=status,
        task_source_comment=task_source_comment(row),
    )


def unblock_task_row(
    task: int,
    row: TaskRow,
    rows: dict[int, TaskRow],
) -> dict[int, TaskRow]:
    match task_status(row):
        case StatusPending():
            return rows
        case StatusCompleted():
            return rows
        case StatusBlocked():
            return _rocq_map_add(
                _rocq_positive_key(task),
                row_with_status(row, StatusPending()),
                rows,
            )
        case __impossible:
            assert_never(__impossible)


def unblock_task_if_present(
    task: int,
    rows: dict[int, TaskRow],
) -> dict[int, TaskRow]:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return rows
    row = __option
    return unblock_task_row(
        task,
        row,
        rows,
    )


def unblock_task_rows(
    order: list[int],
    rows: dict[int, TaskRow],
) -> dict[int, TaskRow]:
    __list = order
    if __list == []:
        return rows
    task = __list[0]
    rest = __list[1:]
    return unblock_task_rows(rest, unblock_task_if_present(task, rows))


def unblock_tasks(
    order: list[int],
    rows: dict[int, TaskRow],
) -> dict[int, TaskRow]:
    return unblock_task_rows(order, rows)


def rescope_task_id(op: RescopeOp) -> int:
    match op:
        case KeepTask(task):
            return task
        case RewriteTask(task, s, s0):
            return task
        case CompleteTask(task):
            return task
        case __impossible:
            assert_never(__impossible)


def op_covers_task(
    task: int,
    ops: list[RescopeOp],
) -> bool:
    __list = ops
    if __list == []:
        return False
    op = __list[0]
    rest = __list[1:]
    if positive_eqb(rescope_task_id(op), task):
        return True
    return op_covers_task(task, rest)


def rescope_ops_cover_snapshot(
    snapshot_order: list[int],
    ops: list[RescopeOp],
) -> bool:
    __list = snapshot_order
    if __list == []:
        return True
    task = __list[0]
    rest = __list[1:]
    if op_covers_task(task, ops):
        return rescope_ops_cover_snapshot(rest, ops)
    return False


def apply_rescope_ops(
    ops: list[RescopeOp],
    rows: dict[int, TaskRow],
    pending_ids: list[int],
    completed_ids: list[int],
) -> tuple[tuple[dict[int, TaskRow], list[int]], list[int]]:
    __list = ops
    if __list == []:
        return (
            (
                rows,
                pending_ids,
            ),
            completed_ids,
        )
    op = __list[0]
    rest = __list[1:]
    task = rescope_task_id(op)
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return apply_rescope_ops(
            rest,
            rows,
            pending_ids,
            completed_ids,
        )
    row = __option
    match op:
        case KeepTask(p):
            match task_status(row):
                case StatusPending():
                    return apply_rescope_ops(
                        rest,
                        rows,
                        pending_ids + [task] + [],
                        completed_ids,
                    )
                case StatusCompleted():
                    return apply_rescope_ops(
                        rest,
                        rows,
                        pending_ids,
                        completed_ids,
                    )
                case StatusBlocked():
                    return apply_rescope_ops(
                        rest,
                        rows,
                        pending_ids + [task] + [],
                        completed_ids,
                    )
                case __impossible:
                    assert_never(__impossible)
        case RewriteTask(p, title, description):
            match task_status(row):
                case StatusPending():
                    row_ = TaskRow(
                        task_title=title,
                        task_description=description,
                        task_kind=task_kind(row),
                        task_status=task_status(row),
                        task_source_comment=task_source_comment(row),
                    )
                    return apply_rescope_ops(
                        rest,
                        _rocq_map_add(
                            _rocq_positive_key(task),
                            row_,
                            rows,
                        ),
                        pending_ids + [task] + [],
                        completed_ids,
                    )
                case StatusCompleted():
                    return apply_rescope_ops(
                        rest,
                        rows,
                        pending_ids,
                        completed_ids,
                    )
                case StatusBlocked():
                    row_ = TaskRow(
                        task_title=title,
                        task_description=description,
                        task_kind=task_kind(row),
                        task_status=task_status(row),
                        task_source_comment=task_source_comment(row),
                    )
                    return apply_rescope_ops(
                        rest,
                        _rocq_map_add(
                            _rocq_positive_key(task),
                            row_,
                            rows,
                        ),
                        pending_ids + [task] + [],
                        completed_ids,
                    )
                case __impossible:
                    assert_never(__impossible)
        case CompleteTask(p):
            match task_status(row):
                case StatusPending():
                    row_ = TaskRow(
                        task_title=task_title(row),
                        task_description=task_description(row),
                        task_kind=task_kind(row),
                        task_status=StatusCompleted(),
                        task_source_comment=task_source_comment(row),
                    )
                    return apply_rescope_ops(
                        rest,
                        _rocq_map_add(
                            _rocq_positive_key(task),
                            row_,
                            rows,
                        ),
                        pending_ids,
                        completed_ids + [task] + [],
                    )
                case StatusCompleted():
                    return apply_rescope_ops(
                        rest,
                        rows,
                        pending_ids,
                        completed_ids,
                    )
                case StatusBlocked():
                    row_ = TaskRow(
                        task_title=task_title(row),
                        task_description=task_description(row),
                        task_kind=task_kind(row),
                        task_status=StatusCompleted(),
                        task_source_comment=task_source_comment(row),
                    )
                    return apply_rescope_ops(
                        rest,
                        _rocq_map_add(
                            _rocq_positive_key(task),
                            row_,
                            rows,
                        ),
                        pending_ids,
                        completed_ids + [task] + [],
                    )
                case __impossible:
                    assert_never(__impossible)
        case __impossible:
            assert_never(__impossible)


def completed_tasks_in_order(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    __list = order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return completed_tasks_in_order(rest, rows)
    row = __option
    match task_status(row):
        case StatusPending():
            return completed_tasks_in_order(rest, rows)
        case StatusCompleted():
            return [task] + completed_tasks_in_order(rest, rows)
        case StatusBlocked():
            return completed_tasks_in_order(rest, rows)
        case __impossible:
            assert_never(__impossible)


def preserve_newly_added(
    snapshot_order: list[int],
    current_order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    __list = current_order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    rest_ = preserve_newly_added(
        snapshot_order,
        rest,
        rows,
    )
    if positive_mem(task, snapshot_order):
        return rest_
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return rest_
    row = __option
    match task_status(row):
        case StatusPending():
            return [task] + rest_
        case StatusCompleted():
            return rest_
        case StatusBlocked():
            return [task] + rest_
        case __impossible:
            assert_never(__impossible)


def task_is_ci(
    rows: dict[int, TaskRow],
    task: int,
) -> bool:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return False
    row = __option
    return task_kind_is_ci(task_kind(row))


def task_is_non_ci(
    rows: dict[int, TaskRow],
    task: int,
) -> bool:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return False
    row = __option
    return task_kind_is_non_ci(task_kind(row))


def collect_ci_tasks(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    __list = order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    rest_ = collect_ci_tasks(rest, rows)
    if task_is_ci(rows, task):
        return [task] + rest_
    return rest_


def collect_non_ci_tasks(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    __list = order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    rest_ = collect_non_ci_tasks(rest, rows)
    if task_is_non_ci(rows, task):
        return [task] + rest_
    return rest_


def stable_ci_first(
    order: list[int],
    rows: dict[int, TaskRow],
) -> list[int]:
    ci = collect_ci_tasks(order, rows)
    non_ci = collect_non_ci_tasks(order, rows)
    return ci + non_ci


def apply_rescope(
    snapshot_order: list[int],
    current_order: list[int],
    rows: dict[int, TaskRow],
    ops: list[RescopeOp],
) -> tuple[list[int], dict[int, TaskRow]]:
    __pair = apply_rescope_ops(ops, rows, [], [])
    p = __pair[0]
    newly_completed = __pair[1]
    __pair = p
    rows_ = __pair[0]
    pending_ids = __pair[1]
    completed_existing = completed_tasks_in_order(current_order, rows)
    newly_added = preserve_newly_added(
        snapshot_order,
        current_order,
        rows_,
    )
    pending_order = stable_ci_first(pending_ids, rows_)
    return (
        pending_order + completed_existing + newly_completed + newly_added,
        rows_,
    )


def rescope_affects_active_task(
    lease: ExecutionLease | None,
    rows_before: dict[int, TaskRow],
    rows_after: dict[int, TaskRow],
) -> bool:
    __option = lease
    if __option is None:
        return False
    active = __option
    __option = rows_before.get(_rocq_positive_key(lease_task(active)))
    if __option is None:
        return False
    before_row = __option
    __option = rows_after.get(_rocq_positive_key(lease_task(active)))
    if __option is None:
        return True
    after_row = __option
    match task_status(after_row):
        case StatusPending():
            return before_row.metadata_changed(after_row)
        case StatusCompleted():
            return True
        case StatusBlocked():
            return before_row.metadata_changed(after_row)
        case __impossible:
            assert_never(__impossible)


def should_abort_for_new_task(
    new_task: int,
    lease: ExecutionLease | None,
    rows: dict[int, TaskRow],
) -> bool:
    __option = lease
    if __option is None:
        return False
    active = __option
    if positive_eqb(new_task, lease_task(active)):
        return False
    __option = rows.get(_rocq_positive_key(new_task))
    if __option is None:
        return False
    new_row = __option
    __option = rows.get(_rocq_positive_key(lease_task(active)))
    if __option is None:
        return False
    current_row = __option
    return new_row.requires_abort(current_row)


def complete_task_visible(
    task: int,
    rows: dict[int, TaskRow],
) -> tuple[dict[int, TaskRow], int | None]:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return (
            rows,
            None,
        )
    row = __option
    match task_status(row):
        case StatusPending():
            row_ = row_with_status(row, StatusCompleted())
            return (
                _rocq_map_add(
                    _rocq_positive_key(task),
                    row_,
                    rows,
                ),
                task_source_comment(row),
            )
        case StatusCompleted():
            return (
                rows,
                None,
            )
        case StatusBlocked():
            row_ = row_with_status(row, StatusCompleted())
            return (
                _rocq_map_add(
                    _rocq_positive_key(task),
                    row_,
                    rows,
                ),
                task_source_comment(row),
            )
        case __impossible:
            assert_never(__impossible)


class TaskChange:
    pass


@dataclass(frozen=True)
class TaskCompleted(TaskChange):
    arg0: int


@dataclass(frozen=True)
class TaskCancelled(TaskChange):
    arg0: int


@dataclass(frozen=True)
class TaskModified(TaskChange):
    arg0: int
    arg1: str
    arg2: str


TaskChangeT = TaskCompleted | TaskCancelled | TaskModified


def task_thread_change(
    task: int,
    rows_before: dict[int, TaskRow],
    rows_after: dict[int, TaskRow],
) -> TaskChange | None:
    __option = rows_before.get(_rocq_positive_key(task))
    if __option is None:
        return None
    before_row = __option
    __option = task_source_comment(before_row)
    if __option is None:
        return None
    p = __option
    match task_status(before_row):
        case StatusPending():
            __option = rows_after.get(_rocq_positive_key(task))
            if __option is None:
                return TaskCancelled(task)
            after_row = __option
            match task_status(after_row):
                case StatusPending():
                    if before_row.metadata_changed(after_row):
                        return TaskModified(
                            task, task_title(after_row), task_description(after_row)
                        )
                    return None
                case StatusCompleted():
                    return TaskCompleted(task)
                case StatusBlocked():
                    if before_row.metadata_changed(after_row):
                        return TaskModified(
                            task, task_title(after_row), task_description(after_row)
                        )
                    return None
                case __impossible:
                    assert_never(__impossible)
        case StatusCompleted():
            return None
        case StatusBlocked():
            __option = rows_after.get(_rocq_positive_key(task))
            if __option is None:
                return TaskCancelled(task)
            after_row = __option
            match task_status(after_row):
                case StatusPending():
                    if before_row.metadata_changed(after_row):
                        return TaskModified(
                            task, task_title(after_row), task_description(after_row)
                        )
                    return None
                case StatusCompleted():
                    return TaskCompleted(task)
                case StatusBlocked():
                    if before_row.metadata_changed(after_row):
                        return TaskModified(
                            task, task_title(after_row), task_description(after_row)
                        )
                    return None
                case __impossible:
                    assert_never(__impossible)
        case __impossible:
            assert_never(__impossible)


def compute_thread_changes(
    snapshot_order: list[int],
    rows_before: dict[int, TaskRow],
    rows_after: dict[int, TaskRow],
) -> list[TaskChange]:
    __list = snapshot_order
    if __list == []:
        return []
    task = __list[0]
    rest = __list[1:]
    rest_ = compute_thread_changes(
        rest,
        rows_before,
        rows_after,
    )
    __option = task_thread_change(task, rows_before, rows_after)
    if __option is None:
        return rest_
    change = __option
    return [change] + rest_


def remove_from_order(
    task: int,
    order: list[int],
) -> list[int]:
    __list = order
    if __list == []:
        return []
    t0 = __list[0]
    rest = __list[1:]
    rest_ = remove_from_order(task, rest)
    if positive_eqb(t0, task):
        return rest_
    return [t0] + rest_


def cleanup_aborted_task(
    task: int,
    lease: ExecutionLease | None,
    order: list[int],
    rows: dict[int, TaskRow],
) -> tuple[tuple[ExecutionLease | None, list[int]], dict[int, TaskRow]]:
    lease_ = clear_matching_lease(task, lease)
    order_ = remove_from_order(task, order)
    rows_ = _rocq_map_remove(
        _rocq_positive_key(task),
        rows,
    )
    return (
        (
            lease_,
            order_,
        ),
        rows_,
    )


def task_still_pending(
    task: int,
    rows: dict[int, TaskRow],
) -> bool:
    __option = rows.get(_rocq_positive_key(task))
    if __option is None:
        return False
    row = __option
    match task_status(row):
        case StatusPending():
            return True
        case StatusCompleted():
            return False
        case StatusBlocked():
            return False
        case __impossible:
            assert_never(__impossible)
