# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass, replace
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
    final,
)


class TaskStatus:
    pass


@final
@dataclass(frozen=True)
class StatusPending(TaskStatus):
    pass


@final
@dataclass(frozen=True)
class StatusCompleted(TaskStatus):
    pass


@final
@dataclass(frozen=True)
class StatusBlocked(TaskStatus):
    pass


TaskStatusT = StatusPending | StatusCompleted | StatusBlocked


class ThreadCommentAuthor:
    pass


@final
@dataclass(frozen=True)
class CommentByFido(ThreadCommentAuthor):
    pass


@final
@dataclass(frozen=True)
class CommentByHuman(ThreadCommentAuthor):
    pass


ThreadCommentAuthorT = CommentByFido | CommentByHuman


@final
@dataclass(frozen=True)
class ThreadComment:
    thread_comment_id: int
    thread_comment_author: ThreadCommentAuthor


@final
@dataclass(frozen=True)
class ReviewThread:
    review_thread_resolved: bool
    review_thread_comments: list[ThreadComment]


@final
@dataclass(frozen=True)
class ThreadTask:
    thread_task_comment: int
    thread_task_status: TaskStatus


class ThreadResolutionDecision:
    pass


@final
@dataclass(frozen=True)
class ResolveReviewThread(ThreadResolutionDecision):
    pass


@final
@dataclass(frozen=True)
class KeepReviewThreadOpen(ThreadResolutionDecision):
    pass


ThreadResolutionDecisionT = ResolveReviewThread | KeepReviewThreadOpen


class ResolvedThreadQueueDecision:
    pass


@final
@dataclass(frozen=True)
class QueueThreadTask(ResolvedThreadQueueDecision):
    pass


@final
@dataclass(frozen=True)
class DismissStaleResolvedThread(ResolvedThreadQueueDecision):
    pass


ResolvedThreadQueueDecisionT = QueueThreadTask | DismissStaleResolvedThread


def thread_comment_ids(comments: list[ThreadComment]) -> list[int]:
    __list = comments
    if __list == []:
        return []
    comment = __list[0]
    rest = __list[1:]
    return [comment.thread_comment_id] + thread_comment_ids(rest)


def last_comment_author_from(
    current: ThreadCommentAuthor | None,
    comments: list[ThreadComment],
) -> ThreadCommentAuthor | None:
    for comment in comments:
        current = comment.thread_comment_author
        continue
    return current


def last_comment_author(comments: list[ThreadComment]) -> ThreadCommentAuthor | None:
    return last_comment_author_from(None, comments)


def task_blocks_thread_resolution(
    comment_ids: list[int],
    task: ThreadTask,
) -> bool:
    match task.thread_task_status:
        case StatusPending():
            return task.thread_task_comment in comment_ids
        case StatusCompleted():
            return False
        case StatusBlocked():
            return False
        case __impossible:
            assert_never(__impossible)


def has_pending_thread_task(
    comment_ids: list[int],
    tasks: list[ThreadTask],
) -> bool:
    for task in tasks:
        if task_blocks_thread_resolution(comment_ids, task):
            return True
        continue
    return False


def latest_comment_is_fido(thread: ReviewThread) -> bool:
    __option = last_comment_author(thread.review_thread_comments)
    if __option is None:
        return False
    t = __option
    return isinstance(t, CommentByFido)


def should_resolve_thread(
    thread: ReviewThread,
    tasks: list[ThreadTask],
) -> bool:
    comment_ids = thread_comment_ids(thread.review_thread_comments)
    thread_open = not thread.review_thread_resolved
    fido_last = latest_comment_is_fido(thread)
    followup_done = not has_pending_thread_task(comment_ids, tasks)
    return thread_open and fido_last and followup_done


def resolution_decision(
    thread: ReviewThread,
    tasks: list[ThreadTask],
) -> ThreadResolutionDecision:
    if should_resolve_thread(thread, tasks):
        return ResolveReviewThread()
    return KeepReviewThreadOpen()


def latest_human_comment(comments: list[ThreadComment]) -> int | None:
    __list = comments
    if __list == []:
        return None
    comment = __list[0]
    rest = __list[1:]
    __option = latest_human_comment(rest)
    if __option is None:
        match comment.thread_comment_author:
            case CommentByFido():
                return None
            case CommentByHuman():
                return comment.thread_comment_id
            case __impossible:
                assert_never(__impossible)
    later = __option
    return later


def resolved_thread_queue_decision(
    thread: ReviewThread,
    incoming_comment: int,
) -> ResolvedThreadQueueDecision:
    if not thread.review_thread_resolved:
        return QueueThreadTask()
    __option = latest_human_comment(thread.review_thread_comments)
    if __option is None:
        return DismissStaleResolvedThread()
    latest = __option
    if latest == incoming_comment:
        return QueueThreadTask()
    return DismissStaleResolvedThread()
