# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass, replace
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
    final,
)


class TurnOutcome:
    pass


@final
@dataclass(frozen=True)
class CommitTaskComplete(TurnOutcome):
    summary: str


@final
@dataclass(frozen=True)
class CommitTaskInProgress(TurnOutcome):
    summary: str


@final
@dataclass(frozen=True)
class SkipTaskWithReason(TurnOutcome):
    reason: str


TurnOutcomeT = CommitTaskComplete | CommitTaskInProgress | SkipTaskWithReason


def outcome_summary(o: TurnOutcome) -> str:
    match o:
        case CommitTaskComplete(s):
            return s
        case CommitTaskInProgress(s):
            return s
        case SkipTaskWithReason(reason):
            return ""
        case __impossible:
            assert_never(__impossible)


def outcome_is_commit(o: TurnOutcome) -> bool:
    match o:
        case CommitTaskComplete(summary):
            return True
        case CommitTaskInProgress(summary):
            return True
        case SkipTaskWithReason(reason):
            return False
        case __impossible:
            assert_never(__impossible)


def outcome_is_terminal(o: TurnOutcome) -> bool:
    match o:
        case CommitTaskComplete(summary):
            return True
        case CommitTaskInProgress(summary):
            return False
        case SkipTaskWithReason(reason):
            return True
        case __impossible:
            assert_never(__impossible)
