# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
)


# option: remapped to Python primitive


class State:
    pass


@dataclass(frozen=True)
class Running(State):
    pass


@dataclass(frozen=True)
class Crashed(State):
    pass


@dataclass(frozen=True)
class Restarting(State):
    pass


@dataclass(frozen=True)
class Hung(State):
    pass


@dataclass(frozen=True)
class Stopped(State):
    pass


StateT = Running | Crashed | Restarting | Hung | Stopped


class Event:
    pass


@dataclass(frozen=True)
class WorkerCrash(Event):
    pass


@dataclass(frozen=True)
class WatchdogDetectAlive(Event):
    pass


@dataclass(frozen=True)
class WatchdogDetectDead(Event):
    pass


@dataclass(frozen=True)
class StaleTimeout(Event):
    pass


@dataclass(frozen=True)
class ActivityResume(Event):
    pass


@dataclass(frozen=True)
class RestartComplete(Event):
    pass


@dataclass(frozen=True)
class RestartCrash(Event):
    pass


@dataclass(frozen=True)
class StopRequest(Event):
    pass


EventT = (
    WorkerCrash
    | WatchdogDetectAlive
    | WatchdogDetectDead
    | StaleTimeout
    | ActivityResume
    | RestartComplete
    | RestartCrash
    | StopRequest
)


def transition(
    current: State,
    event0: Event,
) -> State | None:
    match current:
        case Running():
            match event0:
                case WorkerCrash():
                    return Crashed()
                case WatchdogDetectAlive():
                    return Running()
                case WatchdogDetectDead():
                    return None
                case StaleTimeout():
                    return Hung()
                case ActivityResume():
                    return None
                case RestartComplete():
                    return None
                case RestartCrash():
                    return None
                case StopRequest():
                    return Stopped()
                case __impossible:
                    assert_never(__impossible)
        case Crashed():
            match event0:
                case WorkerCrash():
                    return None
                case WatchdogDetectAlive():
                    return None
                case WatchdogDetectDead():
                    return Restarting()
                case StaleTimeout():
                    return None
                case ActivityResume():
                    return None
                case RestartComplete():
                    return None
                case RestartCrash():
                    return None
                case StopRequest():
                    return None
                case __impossible:
                    assert_never(__impossible)
        case Restarting():
            match event0:
                case WorkerCrash():
                    return None
                case WatchdogDetectAlive():
                    return None
                case WatchdogDetectDead():
                    return None
                case StaleTimeout():
                    return None
                case ActivityResume():
                    return None
                case RestartComplete():
                    return Running()
                case RestartCrash():
                    return Crashed()
                case StopRequest():
                    return None
                case __impossible:
                    assert_never(__impossible)
        case Hung():
            match event0:
                case WorkerCrash():
                    return Crashed()
                case WatchdogDetectAlive():
                    return Hung()
                case WatchdogDetectDead():
                    return None
                case StaleTimeout():
                    return None
                case ActivityResume():
                    return Running()
                case RestartComplete():
                    return None
                case RestartCrash():
                    return None
                case StopRequest():
                    return Stopped()
                case __impossible:
                    assert_never(__impossible)
        case Stopped():
            return None
        case __impossible:
            assert_never(__impossible)
