# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
)


# bool: remapped to Python primitive

_A = TypeVar("_A")


# list: remapped to Python primitive
# positive: remapped to Python primitive


class Pos_Module(Protocol):
    @property
    def eqb(self) -> Callable[[int], Callable[[int], bool]]: ...


__Pos_value: Any = __ModuleNamespace()
Pos: Pos_Module = cast(Pos_Module, __Pos_value)


# ascii: remapped to Python primitive
# string: remapped to Python primitive


class Contender:
    pass


@dataclass(frozen=True)
class Handler(Contender):
    pass


@dataclass(frozen=True)
class CronSweep(Contender):
    pass


ContenderT = Handler | CronSweep


# Python ExtractionDiagnostic [PYEX003]: Type alias declaration is not emitted Remediation: Use a concrete inductive/record or add an extraction remapping for the type.


class CheckConclusion:
    pass


@dataclass(frozen=True)
class CIFailure(CheckConclusion):
    pass


@dataclass(frozen=True)
class CITimedOut(CheckConclusion):
    pass


CheckConclusionT = CIFailure | CITimedOut


class CommentKind:
    pass


@dataclass(frozen=True)
class ReviewLine(CommentKind):
    pass


@dataclass(frozen=True)
class TopLevelPR(CommentKind):
    pass


CommentKindT = ReviewLine | TopLevelPR


class WebhookEvent:
    pass


@dataclass(frozen=True)
class WevReviewComment(WebhookEvent):
    wev_delivery: deliveryId
    wev_pr: int
    wev_comment_id: int
    wev_author: str
    wev_is_bot: bool


@dataclass(frozen=True)
class WevIssueComment(WebhookEvent):
    wev_delivery: deliveryId
    wev_pr: int
    wev_comment_id: int
    wev_author: str
    wev_is_bot: bool


@dataclass(frozen=True)
class WevCIFailure(WebhookEvent):
    wev_delivery: deliveryId
    wev_check_name: str
    wev_conclusion: CheckConclusion
    wev_pr_numbers: list[int]


@dataclass(frozen=True)
class WevPRMerged(WebhookEvent):
    wev_delivery: deliveryId
    wev_pr: int


@dataclass(frozen=True)
class WevIssueAssigned(WebhookEvent):
    wev_delivery: deliveryId
    wev_issue: int
    wev_assignee: str


@dataclass(frozen=True)
class WevReviewSubmitted(WebhookEvent):
    wev_delivery: deliveryId
    wev_pr: int
    wev_review_id: int
    wev_author: str


WebhookEventT = (
    WevReviewComment
    | WevIssueComment
    | WevCIFailure
    | WevPRMerged
    | WevIssueAssigned
    | WevReviewSubmitted
)


class WebhookCommand:
    pass


@dataclass(frozen=True)
class CmdComment(WebhookCommand):
    cmd_delivery: deliveryId
    cmd_pr: int
    cmd_comment_id: int
    cmd_author: str
    cmd_is_bot: bool
    cmd_kind: CommentKind


@dataclass(frozen=True)
class CmdCIFailure(WebhookCommand):
    cmd_delivery: deliveryId
    cmd_check_name: str
    cmd_conclusion: CheckConclusion
    cmd_pr_numbers: list[int]


@dataclass(frozen=True)
class CmdPRMerged(WebhookCommand):
    cmd_delivery: deliveryId
    cmd_pr: int


@dataclass(frozen=True)
class CmdIssueAssigned(WebhookCommand):
    cmd_delivery: deliveryId
    cmd_issue: int
    cmd_assignee: str


@dataclass(frozen=True)
class CmdReviewSubmitted(WebhookCommand):
    cmd_delivery: deliveryId
    cmd_pr: int
    cmd_review_id: int
    cmd_author: str


WebhookCommandT = (
    CmdComment | CmdCIFailure | CmdPRMerged | CmdIssueAssigned | CmdReviewSubmitted
)


def cmd_delivery_id(cmd: WebhookCommand) -> deliveryId:
    match cmd:
        case CmdComment(d, cmd_pr, cmd_comment_id, cmd_author, cmd_is_bot, cmd_kind):
            return d
        case CmdCIFailure(d, cmd_check_name, cmd_conclusion, cmd_pr_numbers):
            return d
        case CmdPRMerged(d, cmd_pr):
            return d
        case CmdIssueAssigned(d, cmd_issue, cmd_assignee):
            return d
        case CmdReviewSubmitted(d, cmd_pr, cmd_review_id, cmd_author):
            return d
        case __impossible:
            assert_never(__impossible)


def translate(ev: WebhookEvent) -> WebhookCommand:
    match ev:
        case WevReviewComment(d, pr, cid, author, is_bot):
            return CmdComment(
                d,
                pr,
                cid,
                author,
                is_bot,
                ReviewLine(),
            )
        case WevIssueComment(d, pr, cid, author, is_bot):
            return CmdComment(
                d,
                pr,
                cid,
                author,
                is_bot,
                TopLevelPR(),
            )
        case WevCIFailure(d, name, conclusion, pr_nums):
            return CmdCIFailure(
                d,
                name,
                conclusion,
                pr_nums,
            )
        case WevPRMerged(d, pr):
            return CmdPRMerged(
                d,
                pr,
            )
        case WevIssueAssigned(d, issue, assignee):
            return CmdIssueAssigned(
                d,
                issue,
                assignee,
            )
        case WevReviewSubmitted(d, pr, rid, author):
            return CmdReviewSubmitted(
                d,
                pr,
                rid,
                author,
            )
        case __impossible:
            assert_never(__impossible)


def same_delivery(
    c1: WebhookCommand,
    c2: WebhookCommand,
) -> bool:
    return cmd_delivery_id(c1) == cmd_delivery_id(c2)


def cmd_to_contender(cmd: WebhookCommand) -> Contender:
    match cmd:
        case CmdComment(
            cmd_delivery,
            cmd_pr,
            cmd_comment_id,
            cmd_author,
            cmd_is_bot,
            cmd_kind,
        ):
            return Handler()
        case CmdCIFailure(cmd_delivery, cmd_check_name, cmd_conclusion, cmd_pr_numbers):
            return Handler()
        case CmdPRMerged(cmd_delivery, cmd_pr):
            return Handler()
        case CmdIssueAssigned(cmd_delivery, cmd_issue, cmd_assignee):
            return Handler()
        case CmdReviewSubmitted(cmd_delivery, cmd_pr, cmd_review_id, cmd_author):
            return Handler()
        case __impossible:
            assert_never(__impossible)


def wev_delivery_id(ev: WebhookEvent) -> deliveryId:
    match ev:
        case WevReviewComment(d, wev_pr, wev_comment_id, wev_author, wev_is_bot):
            return d
        case WevIssueComment(d, wev_pr, wev_comment_id, wev_author, wev_is_bot):
            return d
        case WevCIFailure(d, wev_check_name, wev_conclusion, wev_pr_numbers):
            return d
        case WevPRMerged(d, wev_pr):
            return d
        case WevIssueAssigned(d, wev_issue, wev_assignee):
            return d
        case WevReviewSubmitted(d, wev_pr, wev_review_id, wev_author):
            return d
        case __impossible:
            assert_never(__impossible)
