# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
)


# bool: remapped to Python primitive
# list: remapped to Python primitive
# positive: remapped to Python primitive
# ascii: remapped to Python primitive
# string: remapped to Python primitive


class Contender:
    pass


@dataclass(frozen=True)
class Handler(Contender):
    pass


@dataclass(frozen=True)
class CronSweep(Contender):
    pass


ContenderT = Handler | CronSweep


# Python ExtractionDiagnostic [PYEX003]: Type alias declaration is not emitted Remediation: Use a concrete inductive/record or add an extraction remapping for the type.


class CheckConclusion:
    pass


@dataclass(frozen=True)
class CIFailure(CheckConclusion):
    pass


@dataclass(frozen=True)
class CITimedOut(CheckConclusion):
    pass


CheckConclusionT = CIFailure | CITimedOut


class CommentKind:
    pass


@dataclass(frozen=True)
class ReviewLine(CommentKind):
    pass


@dataclass(frozen=True)
class TopLevelPR(CommentKind):
    pass


CommentKindT = ReviewLine | TopLevelPR


class WebhookEvent:
    pass


@dataclass(frozen=True)
class EvtReviewComment(WebhookEvent):
    evt_delivery: deliveryId
    evt_pr: int
    evt_comment_id: int
    evt_author: str
    evt_is_bot: bool


@dataclass(frozen=True)
class EvtIssueComment(WebhookEvent):
    evt_delivery: deliveryId
    evt_pr: int
    evt_comment_id: int
    evt_author: str
    evt_is_bot: bool


@dataclass(frozen=True)
class EvtCIFailure(WebhookEvent):
    evt_delivery: deliveryId
    evt_check_name: str
    evt_conclusion: CheckConclusion
    evt_pr_numbers: list[int]


@dataclass(frozen=True)
class EvtPRMerged(WebhookEvent):
    evt_delivery: deliveryId
    evt_pr: int


@dataclass(frozen=True)
class EvtIssueAssigned(WebhookEvent):
    evt_delivery: deliveryId
    evt_issue: int
    evt_assignee: str


@dataclass(frozen=True)
class EvtReviewSubmitted(WebhookEvent):
    evt_delivery: deliveryId
    evt_pr: int
    evt_review_id: int
    evt_author: str


WebhookEventT = (
    EvtReviewComment
    | EvtIssueComment
    | EvtCIFailure
    | EvtPRMerged
    | EvtIssueAssigned
    | EvtReviewSubmitted
)


class WebhookCommand:
    pass


@dataclass(frozen=True)
class CmdComment(WebhookCommand):
    cmd_delivery: deliveryId
    cmd_pr: int
    cmd_comment_id: int
    cmd_author: str
    cmd_is_bot: bool
    cmd_kind: CommentKind


@dataclass(frozen=True)
class CmdCIFailure(WebhookCommand):
    cmd_delivery: deliveryId
    cmd_check_name: str
    cmd_conclusion: CheckConclusion
    cmd_pr_numbers: list[int]


@dataclass(frozen=True)
class CmdPRMerged(WebhookCommand):
    cmd_delivery: deliveryId
    cmd_pr: int


@dataclass(frozen=True)
class CmdIssueAssigned(WebhookCommand):
    cmd_delivery: deliveryId
    cmd_issue: int
    cmd_assignee: str


@dataclass(frozen=True)
class CmdReviewSubmitted(WebhookCommand):
    cmd_delivery: deliveryId
    cmd_pr: int
    cmd_review_id: int
    cmd_author: str


WebhookCommandT = (
    CmdComment | CmdCIFailure | CmdPRMerged | CmdIssueAssigned | CmdReviewSubmitted
)


def cmd_delivery_id(cmd: WebhookCommand) -> deliveryId:
    match cmd:
        case CmdComment(d, cmd_pr, cmd_comment_id, cmd_author, cmd_is_bot, cmd_kind):
            return d
        case CmdCIFailure(d, cmd_check_name, cmd_conclusion, cmd_pr_numbers):
            return d
        case CmdPRMerged(d, cmd_pr):
            return d
        case CmdIssueAssigned(d, cmd_issue, cmd_assignee):
            return d
        case CmdReviewSubmitted(d, cmd_pr, cmd_review_id, cmd_author):
            return d
        case __impossible:
            assert_never(__impossible)


def translate(ev: WebhookEvent) -> WebhookCommand:
    match ev:
        case EvtReviewComment(d, pr, cid, author, is_bot):
            return CmdComment(
                d,
                pr,
                cid,
                author,
                is_bot,
                ReviewLine(),
            )
        case EvtIssueComment(d, pr, cid, author, is_bot):
            return CmdComment(
                d,
                pr,
                cid,
                author,
                is_bot,
                TopLevelPR(),
            )
        case EvtCIFailure(d, name, conclusion, pr_nums):
            return CmdCIFailure(
                d,
                name,
                conclusion,
                pr_nums,
            )
        case EvtPRMerged(d, pr):
            return CmdPRMerged(
                d,
                pr,
            )
        case EvtIssueAssigned(d, issue, assignee):
            return CmdIssueAssigned(
                d,
                issue,
                assignee,
            )
        case EvtReviewSubmitted(d, pr, rid, author):
            return CmdReviewSubmitted(
                d,
                pr,
                rid,
                author,
            )
        case __impossible:
            assert_never(__impossible)


def same_delivery(
    c1: WebhookCommand,
    c2: WebhookCommand,
) -> bool:
    return cmd_delivery_id(c1) == cmd_delivery_id(c2)


def cmd_to_contender(cmd: WebhookCommand) -> Contender:
    match cmd:
        case CmdComment(
            cmd_delivery,
            cmd_pr,
            cmd_comment_id,
            cmd_author,
            cmd_is_bot,
            cmd_kind,
        ):
            return Handler()
        case CmdCIFailure(cmd_delivery, cmd_check_name, cmd_conclusion, cmd_pr_numbers):
            return Handler()
        case CmdPRMerged(cmd_delivery, cmd_pr):
            return Handler()
        case CmdIssueAssigned(cmd_delivery, cmd_issue, cmd_assignee):
            return Handler()
        case CmdReviewSubmitted(cmd_delivery, cmd_pr, cmd_review_id, cmd_author):
            return Handler()
        case __impossible:
            assert_never(__impossible)


def evt_delivery_id(ev: WebhookEvent) -> deliveryId:
    match ev:
        case EvtReviewComment(d, evt_pr, evt_comment_id, evt_author, evt_is_bot):
            return d
        case EvtIssueComment(d, evt_pr, evt_comment_id, evt_author, evt_is_bot):
            return d
        case EvtCIFailure(d, evt_check_name, evt_conclusion, evt_pr_numbers):
            return d
        case EvtPRMerged(d, evt_pr):
            return d
        case EvtIssueAssigned(d, evt_issue, evt_assignee):
            return d
        case EvtReviewSubmitted(d, evt_pr, evt_review_id, evt_author):
            return d
        case __impossible:
            assert_never(__impossible)
