# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass, replace
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
    final,
)


class WorkerState:
    pass


@final
@dataclass(frozen=True)
class Absent(WorkerState):
    pass


@final
@dataclass(frozen=True)
class Idle(WorkerState):
    pass


@final
@dataclass(frozen=True)
class Active(WorkerState):
    pass


@final
@dataclass(frozen=True)
class Deferred(WorkerState):
    pass


WorkerStateT = Absent | Idle | Active | Deferred


class WorkerEvent:
    pass


@final
@dataclass(frozen=True)
class Spawn(WorkerEvent):
    pass


@final
@dataclass(frozen=True)
class TakeWork(WorkerEvent):
    pass


@final
@dataclass(frozen=True)
class Yield(WorkerEvent):
    pass


@final
@dataclass(frozen=True)
class Resume(WorkerEvent):
    pass


@final
@dataclass(frozen=True)
class Finish(WorkerEvent):
    pass


@final
@dataclass(frozen=True)
class Restart(WorkerEvent):
    pass


@final
@dataclass(frozen=True)
class Shutdown(WorkerEvent):
    pass


WorkerEventT = Spawn | TakeWork | Yield | Resume | Finish | Restart | Shutdown


def transition(
    w: WorkerState,
    ev: WorkerEvent,
) -> WorkerState | None:
    match w:
        case Absent():
            match ev:
                case Spawn():
                    return Idle()
                case TakeWork():
                    return None
                case Yield():
                    return None
                case Resume():
                    return None
                case Finish():
                    return None
                case Restart():
                    return None
                case Shutdown():
                    return None
                case __impossible:
                    assert_never(__impossible)
        case Idle():
            match ev:
                case Spawn():
                    return None
                case TakeWork():
                    return Active()
                case Yield():
                    return None
                case Resume():
                    return None
                case Finish():
                    return None
                case Restart():
                    return Idle()
                case Shutdown():
                    return Absent()
                case __impossible:
                    assert_never(__impossible)
        case Active():
            match ev:
                case Spawn():
                    return None
                case TakeWork():
                    return None
                case Yield():
                    return Deferred()
                case Resume():
                    return None
                case Finish():
                    return Idle()
                case Restart():
                    return None
                case Shutdown():
                    return Absent()
                case __impossible:
                    assert_never(__impossible)
        case Deferred():
            match ev:
                case Spawn():
                    return None
                case TakeWork():
                    return None
                case Yield():
                    return None
                case Resume():
                    return Active()
                case Finish():
                    return None
                case Restart():
                    return None
                case Shutdown():
                    return Absent()
                case __impossible:
                    assert_never(__impossible)
        case __impossible:
            assert_never(__impossible)
