# Generated by rocq-python-extraction (target: Python 3.14t)
from fido.rocq_runtime import *
from dataclasses import dataclass, replace
from fractions import Fraction
from typing import (
    Any,
    Callable,
    Generic,
    Iterator,
    Protocol,
    TypeVar,
    assert_never,
    cast,
    final,
)


class State:
    pass


@final
@dataclass(frozen=True)
class Absent(State):
    pass


@final
@dataclass(frozen=True)
class Active(State):
    pass


@final
@dataclass(frozen=True)
class Crashed(State):
    pass


@final
@dataclass(frozen=True)
class Stopped(State):
    pass


StateT = Absent | Active | Crashed | Stopped


class Event:
    pass


@final
@dataclass(frozen=True)
class Launch(Event):
    pass


@final
@dataclass(frozen=True)
class Rescue(Event):
    pass


@final
@dataclass(frozen=True)
class ThreadDies(Event):
    pass


@final
@dataclass(frozen=True)
class ThreadStops(Event):
    pass


EventT = Launch | Rescue | ThreadDies | ThreadStops


def transition(
    current: State,
    event0: Event,
) -> State | None:
    match current:
        case Absent():
            match event0:
                case Launch():
                    return Active()
                case Rescue():
                    return None
                case ThreadDies():
                    return None
                case ThreadStops():
                    return None
                case __impossible:
                    assert_never(__impossible)
        case Active():
            match event0:
                case Launch():
                    return None
                case Rescue():
                    return None
                case ThreadDies():
                    return Crashed()
                case ThreadStops():
                    return Stopped()
                case __impossible:
                    assert_never(__impossible)
        case Crashed():
            match event0:
                case Launch():
                    return None
                case Rescue():
                    return Active()
                case ThreadDies():
                    return None
                case ThreadStops():
                    return None
                case __impossible:
                    assert_never(__impossible)
        case Stopped():
            match event0:
                case Launch():
                    return Active()
                case Rescue():
                    return None
                case ThreadDies():
                    return None
                case ThreadStops():
                    return None
                case __impossible:
                    assert_never(__impossible)
        case __impossible:
            assert_never(__impossible)
