"""Shared runtime helpers for Rocq-extracted Python modules.

Every file generated by rocq-python-extraction imports this module instead of
carrying an inlined copy of the preamble.  Keep this module stable — generated
code depends on every exported symbol here.

This module lives at fido.rocq_runtime (a sibling to the fido.rocq package)
so it is not subject to the smart-output pruning that keeps fido.rocq/ limited
to Rocq-extracted files only.

Target: Python 3.14t (free-threaded build, no GIL).
"""

import asyncio
import queue
import threading
from concurrent.futures import Future as _ConcurrentFuture
from contextlib import asynccontextmanager
from itertools import islice
from typing import (
    Any,
    AsyncIterator,
    Awaitable,
    Callable,
    Generic,
    Iterable,
    Never,
    TypeVar,
)

__all__ = [
    # type variables
    "_CoForceT",
    "_ModuleArgT",
    "_ModuleRetT",
    "_StateTState",
    "_StateTValue",
    "_StateTNext",
    "_IOValue",
    "_IONext",
    "_IOOwner",
    "_ChannelValue",
    "_FutureValue",
    # errors
    "_Impossible",
    "_impossible",
    "_RocqUtf8BoundaryError",
    "_RocqNumericDomainError",
    "_rocq_numeric_domain_error",
    # finite-collection type aliases
    "key",
    "elt",
    # finite-collection helpers
    "_rocq_positive_key",
    "_rocq_string_key",
    "_rocq_sorted_key",
    "_rocq_map_add",
    "_rocq_map_remove",
    "_rocq_map_elements",
    "_rocq_map_fold",
    "_rocq_set_add",
    "_rocq_set_remove",
    "_rocq_set_elements",
    "_rocq_set_fold",
    # ASCII helper
    "_rocq_ascii_to_int",
    # monads
    "StateT",
    "IO",
    # concurrency primitives
    "Mutex",
    "Channel",
    "Future",
    # lazy / coinductive
    "coforce",
    "coprefix_eq",
    "coprefix_hash",
    # module system
    "__ModuleNamespace",
    "__apply_applicative",
    # erased logical argument sentinel
    "__",
]

_CoForceT = TypeVar("_CoForceT")
_ModuleArgT = TypeVar("_ModuleArgT")
_ModuleRetT = TypeVar("_ModuleRetT")
_StateTState = TypeVar("_StateTState")
_StateTValue = TypeVar("_StateTValue")
_StateTNext = TypeVar("_StateTNext")
_IOValue = TypeVar("_IOValue")
_IONext = TypeVar("_IONext")
_IOOwner = TypeVar("_IOOwner")
_ChannelValue = TypeVar("_ChannelValue")
_FutureValue = TypeVar("_FutureValue")


class _Impossible(RuntimeError):
    pass


def _impossible() -> Never:
    raise _Impossible()


class _RocqUtf8BoundaryError(UnicodeError):
    pass


class _RocqNumericDomainError(ValueError):
    pass


def _rocq_numeric_domain_error(kind: str, value: object) -> Never:
    raise _RocqNumericDomainError(f"Rocq {kind} value out of domain: {value!r}")


key = int  # finite-map module key alias
elt = int  # finite-set module element alias


def _rocq_positive_key(key: int) -> int:
    if key <= 0:
        raise _RocqNumericDomainError("positive map/set key", key)
    return key


def _rocq_string_key(key: object) -> str:
    if not isinstance(key, str):
        raise TypeError(f"Rocq string map/set key must be str: {key!r}")
    return key


def _rocq_sorted_key(key: object) -> Any:  # noqa: ANN401  # rich-comparable opaque sort key
    return key.encode("utf-8") if isinstance(key, str) else key


def _rocq_map_add(
    key: object, value: object, mapping: dict[object, object]
) -> dict[object, object]:
    result = dict(mapping)
    result[key] = value
    return result


def _rocq_map_remove(
    key: object, mapping: dict[object, object]
) -> dict[object, object]:
    result = dict(mapping)
    result.pop(key, None)
    return result


def _rocq_map_elements(mapping: dict[object, object]) -> list[tuple[object, object]]:
    return sorted(mapping.items(), key=lambda item: _rocq_sorted_key(item[0]))


def _rocq_map_fold(
    function: Callable[[object, object, object], object],
    mapping: dict[object, object],
    initial: object,
) -> object:
    result = initial
    for key, value in _rocq_map_elements(mapping):
        result = function(key, value, result)
    return result


def _rocq_set_add(key: object, values: frozenset[object]) -> frozenset[object]:
    return frozenset((*values, key))


def _rocq_set_remove(key: object, values: frozenset[object]) -> frozenset[object]:
    return frozenset(value for value in values if value != key)


def _rocq_set_elements(values: frozenset[object]) -> list[object]:
    return sorted(values, key=_rocq_sorted_key)


def _rocq_set_fold(
    function: Callable[[object, object], object],
    values: frozenset[object],
    initial: object,
) -> object:
    result = initial
    for value in _rocq_set_elements(values):
        result = function(value, result)
    return result


def _rocq_ascii_to_int(
    b0: bool,
    b1: bool,
    b2: bool,
    b3: bool,
    b4: bool,
    b5: bool,
    b6: bool,
    b7: bool,
) -> int:
    return sum(
        (1 << i) for i, bit in enumerate((b0, b1, b2, b3, b4, b5, b6, b7)) if bit
    )


class StateT(Generic[_StateTState, _StateTValue]):
    def __init__(
        self,
        step: Callable[[_StateTState], tuple[_StateTValue, _StateTState]],
        state: _StateTState | None = None,
    ) -> None:
        self._step = step
        self.state = state

    def run(self, state: _StateTState) -> _StateTValue:
        value, next_state = self._step(state)
        self.state = next_state
        return value

    def run_with_state(self, state: _StateTState) -> tuple[_StateTValue, _StateTState]:
        result = self._step(state)
        self.state = result[1]
        return result

    def bind(
        self,
        f: Callable[[_StateTValue], StateT[_StateTState, _StateTNext]],
    ) -> StateT[_StateTState, _StateTNext]:
        def run_bound(state: _StateTState) -> tuple[_StateTNext, _StateTState]:
            value, next_state = self._step(state)
            return f(value).run_with_state(next_state)

        return StateT(run_bound, self.state)

    @classmethod
    def pure(cls, value: _StateTValue) -> StateT[_StateTState, _StateTValue]:
        return StateT(lambda state: (value, state))

    @classmethod
    def get_state(cls) -> StateT[_StateTState, _StateTState]:
        return StateT(lambda state: (state, state))

    @classmethod
    def put_state(cls, new_state: _StateTState) -> StateT[_StateTState, None]:
        return StateT(lambda _state: (None, new_state))


class IO(Generic[_IOValue]):
    def __init__(self, thunk: Callable[[], Awaitable[_IOValue]]) -> None:
        self._thunk = thunk

    async def run(self) -> _IOValue:
        return await self._thunk()

    def bind(self, f: Callable[[_IOValue], IO[_IONext]]) -> IO[_IONext]:
        async def run_bound() -> _IONext:
            value = await self.run()
            return await f(value).run()

        return IO(run_bound)

    @classmethod
    def pure(cls, value: _IOValue) -> IO[_IOValue]:
        async def run_pure() -> _IOValue:
            return value

        return IO(run_pure)

    @classmethod
    def from_sync(cls, thunk: Callable[[], _IOValue]) -> IO[_IOValue]:
        async def run_sync() -> _IOValue:
            return thunk()

        return IO(run_sync)

    @classmethod
    def from_blocking(cls, thunk: Callable[[], _IOValue]) -> IO[_IOValue]:
        async def run_blocking() -> _IOValue:
            return await asyncio.to_thread(thunk)

        return IO(run_blocking)

    @classmethod
    @asynccontextmanager
    async def ownership(
        cls,
        acquire: IO[_IOOwner],
        release: Callable[[_IOOwner], IO[None]],
    ) -> AsyncIterator[_IOOwner]:
        owner = await acquire.run()
        try:
            yield owner
        finally:
            await release(owner).run()

    @classmethod
    def bracket(
        cls,
        acquire: IO[_IOOwner],
        release: Callable[[_IOOwner], IO[None]],
        use: Callable[[_IOOwner], IO[_IONext]],
    ) -> IO[_IONext]:
        async def run_bracket() -> _IONext:
            async with cls.ownership(acquire, release) as owner:
                return await use(owner).run()

        return IO(run_bracket)


class Mutex:
    """Explicit threading mutex wrapper for extracted coordination models.

    This wrapper exposes Python's lock behavior; it does not prove fairness,
    starvation freedom, or a Rocq-level scheduler semantics.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()

    @classmethod
    def new(cls) -> IO[Mutex]:
        return IO.from_sync(cls)

    def acquire(self) -> IO[None]:
        def lock() -> None:
            self._lock.acquire()

        return IO.from_blocking(lock)

    def release(self) -> IO[None]:
        def unlock() -> None:
            self._lock.release()

        return IO.from_sync(unlock)


class Channel(Generic[_ChannelValue]):
    """Explicit FIFO channel wrapper backed by queue.SimpleQueue.

    FIFO order is for completed sends observed by this queue.  This wrapper
    does not model scheduler fairness, producer/consumer races, or cancellation.
    """

    def __init__(self) -> None:
        self._queue: queue.SimpleQueue[_ChannelValue] = queue.SimpleQueue()

    @classmethod
    def new(cls) -> IO[Channel[_ChannelValue]]:
        return IO.from_sync(cls)

    def send(self, value: _ChannelValue) -> IO[None]:
        def put() -> None:
            self._queue.put(value)

        return IO.from_sync(put)

    def receive(self) -> IO[_ChannelValue]:
        return IO.from_blocking(self._queue.get)


class Future(Generic[_FutureValue]):
    """Explicit future wrapper backed by concurrent.futures.Future.

    Completion follows Python Future semantics: result blocks until completed,
    double completion raises, and no Rocq-level thread interleaving is implied.
    """

    def __init__(self) -> None:
        self._future: _ConcurrentFuture[_FutureValue] = _ConcurrentFuture()

    @classmethod
    def new(cls) -> IO[Future[_FutureValue]]:
        return IO.from_sync(cls)

    def set_result(self, value: _FutureValue) -> IO[None]:
        def set_value() -> None:
            self._future.set_result(value)

        return IO.from_sync(set_value)

    def result(self) -> IO[_FutureValue]:
        return IO.from_blocking(self._future.result)

    def done(self) -> bool:
        return self._future.done()


def coforce(value: Callable[[], _CoForceT]) -> _CoForceT:
    return value()


def coprefix_eq(n: int, left: Iterable[object], right: Iterable[object]) -> bool:
    return tuple(islice(iter(left), n)) == tuple(islice(iter(right), n))


def coprefix_hash(n: int, value: Iterable[object]) -> int:
    return hash(tuple(islice(iter(value), n)))


class __ModuleNamespace:
    pass


def __apply_applicative(
    cache: dict[int, _ModuleRetT],
    build: Callable[[_ModuleArgT], _ModuleRetT],
    arg: _ModuleArgT,
) -> _ModuleRetT:
    key = id(arg)
    cached = cache.get(key)
    if cached is None:
        cached = build(arg)
        cache[key] = cached
    return cached


__ = None  # erased logical argument
