(** Rocq → Python extraction backend.
    Phase 2: expression printer — leaf nodes, [MLglob], [MLapp], [MLlam]. *)

open Pp
open Names
open Miniml
open Mlutil
open Table
open Common

(*s Keywords that may not be used as Python identifiers. *)

let keywords =
  let kws = [
    "False"; "None"; "True"; "and"; "as"; "assert"; "async"; "await";
    "break"; "class"; "continue"; "def"; "del"; "elif"; "else"; "except";
    "finally"; "for"; "from"; "global"; "if"; "import"; "in"; "is";
    "lambda"; "nonlocal"; "not"; "or"; "pass"; "raise"; "return"; "try";
    "while"; "with"; "yield";
    (* built-ins that clash in practice *)
    "type"; "list"; "dict"; "set"; "int"; "float"; "str"; "bool";
    "bytes"; "object"; "print"; "len"; "range"; "map"; "filter"; "zip";
  ] in
  List.fold_left (fun s w -> Id.Set.add (Id.of_string w) s) Id.Set.empty kws

(*s File naming: module path → base filename (no suffix). *)

let file_naming state mp =
  file_of_modfile (State.get_table state) mp

(*s Preamble emitted at the top of every extracted .py file. *)

let preamble _state _name _comment _used_modules _safe =
  str "# Generated by rocq-python-extraction" ++ fnl () ++
  str "__ = None  # erased logical argument" ++ fnl ()

(*s Helpers for Python literal emission. *)

(** Escape a string for use in Python double-quoted string literals. *)
let py_escape_str s =
  let buf = Buffer.create (String.length s + 2) in
  String.iter (function
    | '"'  -> Buffer.add_string buf "\\\""
    | '\\' -> Buffer.add_string buf "\\\\"
    | '\n' -> Buffer.add_string buf "\\n"
    | '\r' -> Buffer.add_string buf "\\r"
    | '\t' -> Buffer.add_string buf "\\t"
    | c    -> Buffer.add_char buf c) s;
  Buffer.contents buf

(** Escape bytes for Python [b"..."] literals.  Non-printable and non-ASCII
    bytes are emitted as [\\xHH] hex escapes. *)
let py_escape_bytes s =
  let buf = Buffer.create (String.length s + 2) in
  String.iter (fun c ->
    let code = Char.code c in
    if code >= 32 && code < 127 && c <> '"' && c <> '\\' then
      Buffer.add_char buf c
    else
      Buffer.add_string buf (Printf.sprintf "\\x%02x" code)) s;
  Buffer.contents buf

(** Emit a Python float literal.  [Float64.to_string] uses ["nan"],
    ["infinity"], and ["neg_infinity"]; map these to Python's forms. *)
let pp_float_lit f =
  match Float64.to_string f with
  | "nan"          -> str "float('nan')"
  | "infinity"     -> str "float('inf')"
  | "neg_infinity" -> str "float('-inf')"
  | s              -> str s

(*s Global reference printer.  Honours [Extract Constant ... => "..."]
    inline-custom declarations. *)

let pp_glob state r =
  if is_inline_custom r then str (find_custom r)
  else str (pp_global state Term r)

(*s Core expression printer.
    [env] carries de Bruijn binder names (innermost first).
    Compound nodes not yet implemented emit [# UNIMPL <Node>] stubs;
    they will be replaced in subsequent Phase 2 tasks. *)

let rec pp_expr state env = function
  | MLrel n ->
      (* De Bruijn variable: look up the binder name.  The dummy name [_]
         signals an erased binder; emit [__] (the module-level sentinel). *)
      let id = get_db_name n env in
      let id = if Id.equal id dummy_name then Id.of_string "__" else id in
      Id.print id
  | MLglob r ->
      pp_glob state r
  | MLdummy _ ->
      str "__"
  | MLexn s ->
      str "raise RuntimeError(\"" ++ str (py_escape_str s) ++ str "\")"
  | MLaxiom s ->
      str "raise NotImplementedError(\"AXIOM TO BE REALIZED: " ++
      str (py_escape_str s) ++ str "\")"
  | MLmagic a ->
      (* Identity coercion — Python is dynamically typed; emit inner expr. *)
      pp_expr state env a
  | MLuint i ->
      str (Uint63.to_string i)
  | MLfloat f ->
      pp_float_lit f
  | MLstring s ->
      str "b\"" ++ str (py_escape_bytes (Pstring.to_string s)) ++ str "\""
  | MLparray _ ->
      str "raise NotImplementedError(\"MLparray: persistent arrays not yet supported\")"
  | MLapp (f, args) ->
      (* Flatten left-associative curried application:
         MLapp(MLapp(f,[a]),[b]) → f(a, b) *)
      let rec collect acc = function
        | MLapp (g, more) -> collect (more @ acc) g
        | head            -> (head, acc)
      in
      let (head, all_args) = collect args f in
      (* Parenthesise the function if it is itself a lambda expression,
         since [lambda x: e] has very low precedence in Python. *)
      let pp_head =
        match head with
        | MLlam _ -> str "(" ++ pp_expr state env head ++ str ")"
        | _       -> pp_expr state env head
      in
      pp_head ++ str "(" ++
      prlist_with_sep (fun () -> str ", ") (pp_expr state env) all_args ++
      str ")"
  | MLlam _ as a ->
      (* Collect consecutive lambdas: MLlam(x, MLlam(y, body)) → lambda x, y: body.
         [collect_lams] returns ids innermost-first; reverse for Python source order. *)
      let ids, body = collect_lams a in
      let params = List.map id_of_mlid ids in
      let params, env' = push_vars params env in
      let pp_param id =
        (* Erased binders use [_] (Python's throwaway) in binder position. *)
        if Id.equal id dummy_name then str "_" else Id.print id
      in
      str "lambda " ++
      prlist_with_sep (fun () -> str ", ") pp_param (List.rev params) ++
      str ": " ++
      pp_expr state env' body
  (* Stubs — replaced in subsequent tasks *)
  | MLletin _ -> str "# UNIMPL MLletin"
  | MLcons  _ -> str "# UNIMPL MLcons"
  | MLtuple _ -> str "# UNIMPL MLtuple"
  | MLcase  _ -> str "# UNIMPL MLcase"
  | MLfix   _ -> str "# UNIMPL MLfix"

(*s Declaration printer.  [Dterm] now emits real Python for the RHS
    expression (simple [name = expr] form).  Full lambda-aware wiring
    comes in the "Wire Dterm and Dfix" task. *)

let pp_decl state = function
  | Dind  _     -> str "# UNIMPL Dind"  ++ fnl ()
  | Dtype _     -> str "# UNIMPL Dtype" ++ fnl ()
  | Dterm (r, a, _) ->
      let env = empty_env state () in
      str (pp_global state Term r) ++ str " = " ++
      pp_expr state env a ++ fnl ()
  | Dfix  _     -> str "# UNIMPL Dfix"  ++ fnl ()

(*s Module structure walker.
    [State.with_visibility] must be called around each module so that
    [pp_global] can resolve names relative to the current module path. *)

let pp_structure_elem state = function
  | (_, SEdecl d)    -> pp_decl state d
  | (_, SEmodule _)  -> str "# UNIMPL SEmodule"  ++ fnl ()
  | (_, SEmodtype _) -> str "# UNIMPL SEmodtype" ++ fnl ()

let pp_struct state struc =
  let pp_mod (mp, sel) =
    State.with_visibility state mp [] (fun state ->
      prlist (pp_structure_elem state) sel)
  in
  prlist pp_mod struc

(*s No interface file for Python. *)

let sig_preamble _state _name _comment _used_modules _safe = mt ()

let pp_sig _state _sig = mt ()

(*s The language descriptor record registered with the extraction framework. *)

let python_descr : Common.State.t language_descr = {
  keywords;
  file_suffix    = ".py";
  file_naming;
  preamble;
  pp_struct;
  sig_suffix     = None;
  sig_preamble;
  pp_sig;
  pp_decl;
}
