(** Rocq → Python extraction backend.
    Phase 2: expression printer — all [ml_ast] nodes.

    Target: Python 3.14t (free-threaded build, no GIL).
    Generated code uses [match]/[case] (3.10+), PEP 604 union syntax (3.10+),
    and relies on PEP 649 deferred annotation evaluation so that forward
    references in dataclass fields work without quoting.  No attempt is made
    at compatibility with older Python versions. *)

open Pp
open Names
open Miniml
open Mlutil
open Table
open Common

(*s Keywords that may not be used as Python identifiers. *)

let keywords =
  let kws = [
    "False"; "None"; "True"; "and"; "as"; "assert"; "async"; "await";
    "break"; "class"; "continue"; "def"; "del"; "elif"; "else"; "except";
    "finally"; "for"; "from"; "global"; "if"; "import"; "in"; "is";
    "lambda"; "nonlocal"; "not"; "or"; "pass"; "raise"; "return"; "try";
    "while"; "with"; "yield";
    (* built-ins that clash in practice *)
    "type"; "list"; "dict"; "set"; "int"; "float"; "str"; "bool";
    "bytes"; "object"; "print"; "len"; "range"; "map"; "filter"; "zip";
  ] in
  List.fold_left (fun s w -> Id.Set.add (Id.of_string w) s) Id.Set.empty kws

(*s File naming: module path → base filename (no suffix). *)

let file_naming state mp =
  file_of_modfile (State.get_table state) mp

(*s Preamble emitted at the top of every extracted .py file. *)

let preamble _state _name _comment _used_modules _safe =
  (* Target: Python 3.14t (free-threaded build, no GIL).
     PEP 649 deferred annotation evaluation is the default on 3.14, so forward
     references in dataclass field types (e.g. [class EvenS: arg0: Odd] before
     [Odd] is defined) work without any import.  We do not support older Python
     versions. *)
  str "# Generated by rocq-python-extraction (target: Python 3.14t)" ++ fnl () ++
  str "from dataclasses import dataclass" ++ fnl () ++
  str "from typing import Callable, Generic, TypeVar, assert_never" ++ fnl () ++
  str "__ = None  # erased logical argument" ++ fnl ()

(*s Helpers for Python literal emission. *)

(** Escape a string for use in Python double-quoted string literals. *)
let py_escape_str s =
  let buf = Buffer.create (String.length s + 2) in
  String.iter (function
    | '"'  -> Buffer.add_string buf "\\\""
    | '\\' -> Buffer.add_string buf "\\\\"
    | '\n' -> Buffer.add_string buf "\\n"
    | '\r' -> Buffer.add_string buf "\\r"
    | '\t' -> Buffer.add_string buf "\\t"
    | c    -> Buffer.add_char buf c) s;
  Buffer.contents buf

(** Escape bytes for Python [b"..."] literals.  Non-printable and non-ASCII
    bytes are emitted as [\\xHH] hex escapes. *)
let py_escape_bytes s =
  let buf = Buffer.create (String.length s + 2) in
  String.iter (fun c ->
    let code = Char.code c in
    if code >= 32 && code < 127 && c <> '"' && c <> '\\' then
      Buffer.add_char buf c
    else
      Buffer.add_string buf (Printf.sprintf "\\x%02x" code)) s;
  Buffer.contents buf

(** Emit a Python float literal.  [Float64.to_string] uses ["nan"],
    ["infinity"], and ["neg_infinity"]; map these to Python's forms. *)
let pp_float_lit f =
  match Float64.to_string f with
  | "nan"          -> str "float('nan')"
  | "infinity"     -> str "float('inf')"
  | "neg_infinity" -> str "float('-inf')"
  | s              -> str s

(*s Python-safe identifier printer.
    Rocq/OCaml allow primed identifiers ([n''], [f'']) that are illegal in
    Python.  Convert each apostrophe to an underscore so names like [n'] become
    [n_] and remain valid Python identifiers. *)

let pp_pyid id =
  str (String.map (function '\'' -> '_' | c -> c) (Id.to_string id))

let is_dummy_id id =
  Id.equal id dummy_name

let visible_params ids =
  List.filter (fun id -> not (is_dummy_id id)) ids

let pp_param id =
  pp_pyid id

let pp_param_list ids =
  prlist_with_sep (fun () -> str ", ") pp_param (visible_params ids)

let pp_lambda ids body =
  let params = visible_params ids in
  if List.is_empty params then str "lambda: " ++ body
  else
    str "lambda " ++
    prlist_with_sep (fun () -> str ", ") pp_param params ++
    str ": " ++ body

let is_erased_arg = function
  | MLdummy _ -> true
  | _         -> false

(** Capitalize the first character of [s] for Python class names.
    Rocq type names are lowercased by the extraction framework (OCaml
    convention); Python expects PascalCase for class names (PEP 8). *)
let capitalize_first s =
  if String.length s = 0 then s
  else
    let b = Bytes.of_string s in
    Bytes.set b 0 (Char.uppercase_ascii (Bytes.get b 0));
    Bytes.to_string b

(*s Global reference printer.  Honours [Extract Constant ... => "..."]
    inline-custom declarations. *)

let pp_glob state r =
  if is_inline_custom r then str (find_custom r)
  else str (pp_global state Term r)

(*s Helpers for [MLcons] emission. *)

(** Return the parent inductive reference for a constructor or inductive ref. *)
let get_ind r =
  let open GlobRef in
  match r.glob with
  | IndRef _              -> r
  | ConstructRef (ind, _) -> { glob = IndRef ind; inst = r.inst }
  | _                     -> assert false

(** KerName of an inductive reference (for record field key lookup). *)
let kn_of_ind r =
  let open GlobRef in
  match r.glob with
  | IndRef (kn, _) -> MutInd.user kn
  | _              -> assert false

(** Python keyword-argument name for record field at position [i].
    Uses [pp_global_with_key] for named fields, ["arg<i>"] for anonymous ones. *)
let pp_field_name state r fds i =
  match List.nth fds i with
  | Some r' -> str (pp_global_with_key state Term (kn_of_ind (get_ind r)) r')
  | None    -> str (Printf.sprintf "arg%d" i)

(** Raw constructor name for [r], accounting for inline-custom declarations. *)
let str_cons state r =
  if is_inline_custom r then find_custom r
  else pp_global state Cons r

(*s Pattern printer for Python [case] syntax. *)

(** True when the last branch in [branches] is a bare wildcard pattern.
    When it is, we skip the synthetic catch-all arm — the explicit wildcard
    already handles every remaining case and a second [case _:] would be
    unreachable. *)
let has_wildcard_last branches =
  let n = Array.length branches in
  n > 0 &&
  (let (_, pat, _) = branches.(n - 1) in
   match pat with
   | Pwild -> true
   | _     -> false)

(** Check whether pattern [p] has a custom extraction equal to string [s].
    Used to detect bool patterns mapped to ["True"] / ["False"]. *)
let is_bool_patt p s =
  try
    let r = match p with
      | Pusual r | Pcons (r, []) -> r
      | _ -> raise Not_found
    in
    String.equal (find_custom r) s
  with Not_found -> false

(** Expand a top-level [Pusual r] into [Pcons(r, [Prel n; …; Prel 1])]
    before the pattern reaches [pp_pattern].  [n] is the number of branch
    binders (i.e. [List.length ids] in the enclosing [pp_branch]).

    [Pusual r] is a shorthand emitted by Rocq's extraction only at the
    outermost level of a branch pattern — never nested inside another
    [Pcons] or [Ptuple].  Expanding it here into ordinary [Pcons]/[Prel]
    nodes means [pp_pattern] can work purely from the de Bruijn environment
    without a separate [ids] list, which in turn means nested sub-patterns
    (e.g. [Pcons(MCons, [Prel 2, Pcons(MCons, [Prel 1, Pwild])])]) render
    correctly: each [Prel n] resolves to the right binder name via [env']. *)
let expand_pusual n = function
  | Pusual r -> Pcons (r, List.init n (fun i -> Prel (n - i)))
  | pat      -> pat

(** Pretty-print an [ml_pattern] in Python [case] syntax.
    [env'] is the de Bruijn environment with all branch binders pushed.
    Call [expand_pusual] on the top-level pattern before entering here so
    that [Pusual] nodes never reach this function. *)
let rec pp_pattern state env' = function
  | Pcons (r, []) ->
      let cons = str_cons state r in
      (* Erased / empty-name constructor: emit wildcard so the arm still matches *)
      if String.equal "" cons then str "_"
      else str cons ++ str "()"
  | Pcons (r, pats) ->
      str (str_cons state r) ++ str "(" ++
      prlist_with_sep (fun () -> str ", ") (pp_pattern state env') pats ++
      str ")"
  | Pusual _ ->
      (* Should have been expanded by [expand_pusual] before this call. *)
      assert false
  | Ptuple pats ->
      str "(" ++
      prlist_with_sep (fun () -> str ", ") (pp_pattern state env') pats ++
      str ")"
  | Prel n ->
      pp_pyid (get_db_name n env')
  | Pwild ->
      str "_"

(*s Record-projection detection helper.

    Returns [Some (r, fds, sub_pats)] when [branches] describes a single-branch
    match that the optimiser can convert into lambda-lifted attribute accesses:

      (lambda param_0, param_1, …: body)(scrutinee.field_0, scrutinee.field_1, …)

    Three conditions must hold:
    1. Exactly one branch.
    2. The branch pattern is [Pusual r] or [Pcons(r,_)] for a constructor [r]
       whose parent inductive is a record ([get_record_fields] is non-empty).
    3. Every expanded sub-pattern is [Prel k] (bound) or [Pwild] (discarded),
       and the sub-pattern count matches the field count.

    Condition 3 rules out nested constructor patterns inside a field position,
    which require genuine case analysis rather than a plain attribute access.

    Used by both [pp_expr] (expression context) and [pp_return_body] (inside
    a [def] body), so the optimisation fires in both settings. *)
let record_proj_info state branches =
  if Array.length branches <> 1 then None
  else
    let (ids, pat, _) = branches.(0) in
    match pat with
    | Pusual r | Pcons (r, _) ->
        let fds = get_record_fields (State.get_table state) r in
        if List.is_empty fds then None
        else
          (* Expand [Pusual r] into [Pcons(r, pats)] for uniform treatment;
             [Pcons] is returned unchanged by [expand_pusual]. *)
          ( match expand_pusual (List.length ids) pat with
            | Pcons (_, sub_pats) ->
                if List.length sub_pats = List.length fds &&
                   List.for_all
                     (function Prel _ | Pwild -> true | _ -> false)
                     sub_pats
                then Some (r, fds, sub_pats)
                else None
            | _ -> None )
    | _ -> None

(*s Core expression printer.
    [env] carries de Bruijn binder names (innermost first). *)

let rec pp_expr state env = function
  | MLrel n ->
      (* De Bruijn variable: look up the binder name.  The dummy name [_]
         signals an erased binder; emit [__] (the module-level sentinel). *)
      let id = get_db_name n env in
      if Id.equal id dummy_name then str "__" else pp_pyid id
  | MLglob r ->
      pp_glob state r
  | MLdummy _ ->
      str "__"
  | MLexn s ->
      str "raise RuntimeError(\"" ++ str (py_escape_str s) ++ str "\")"
  | MLaxiom s ->
      str "raise NotImplementedError(\"AXIOM TO BE REALIZED: " ++
      str (py_escape_str s) ++ str "\")"
  | MLmagic a ->
      (* Identity coercion — Python is dynamically typed; emit inner expr. *)
      pp_expr state env a
  | MLuint i ->
      str (Uint63.to_string i)
  | MLfloat f ->
      pp_float_lit f
  | MLstring s ->
      str "b\"" ++ str (py_escape_bytes (Pstring.to_string s)) ++ str "\""
  | MLparray _ ->
      str "raise NotImplementedError(\"MLparray: persistent arrays not yet supported\")"
  | MLapp (f, args) ->
      (* Flatten left-associative curried application:
         MLapp(MLapp(f,[a]),[b]) → f(a, b) *)
      let rec collect acc = function
        | MLapp (g, more) -> collect (more @ acc) g
        | head            -> (head, acc)
      in
      let (head, all_args) = collect args f in
      let all_args = List.filter (fun a -> not (is_erased_arg a)) all_args in
      (* Parenthesise the function if it is itself a lambda expression,
         since [lambda x: e] has very low precedence in Python. *)
      let pp_head =
        match head with
        | MLlam _ -> str "(" ++ pp_expr state env head ++ str ")"
        | _       -> pp_expr state env head
      in
      if List.is_empty all_args then pp_head
      else
        pp_head ++ str "(" ++
        prlist_with_sep (fun () -> str ", ") (pp_expr state env) all_args ++
        str ")"
  | MLlam _ as a ->
      (* Collect consecutive lambdas: MLlam(x, MLlam(y, body)) → lambda x, y: body.
         [collect_lams] returns ids innermost-first; reverse for Python source order. *)
      let ids, body = collect_lams a in
      let params = List.map id_of_mlid ids in
      let params, env' = push_vars params env in
      let params = List.rev params in
      if List.is_empty (visible_params params) then pp_expr state env' body
      else pp_lambda params (pp_expr state env' body)
  | MLletin (id, a1, a2) ->
      (* Let binding in expression context: lambda-lift to [(lambda x: a2)(a1)].
         This is safe in pure functional code and avoids statement–expression
         impedance.  Statement-level [Dterm] will get a proper [def]/assignment
         form in the "Wire Dterm and Dfix" task. *)
      let params, env' = push_vars [id_of_mlid id] env in
      let bname = List.hd params in
      let pp_binder =
        if Id.equal bname dummy_name then str "_" else pp_pyid bname
      in
      str "(lambda " ++ pp_binder ++ str ": " ++
      pp_expr state env' a2 ++ str ")(" ++
      pp_expr state env a1 ++ str ")"
  | MLtuple l ->
      (* Tuple literal: (a, b, c) *)
      str "(" ++
      prlist_with_sep (fun () -> str ", ") (pp_expr state env) l ++
      str ")"
  | MLcons (_, r, args) ->
      let cons_name = str_cons state r in
      if is_coinductive (State.get_table state) r then
        (* Coinductive: wrap in a thunk so consumers can force lazily *)
        str "lambda: " ++
        ( if String.equal "" cons_name then
            (* erased coinductive constructor — unusual but valid *)
            (match args with [a] -> pp_expr state env a | _ -> assert false)
          else if List.is_empty args then str cons_name
          else
            str cons_name ++ str "(" ++
            prlist_with_sep (fun () -> str ", ") (pp_expr state env) args ++
            str ")" )
      else if String.equal "" cons_name then
        (* Singleton / newtype erasure — emit content directly *)
        ( match args with
          | []  -> str "None"
          | [a] -> pp_expr state env a
          | _   ->
              str "(" ++
              prlist_with_sep (fun () -> str ", ") (pp_expr state env) args ++
              str ")" )
      else
        let fds = get_record_fields (State.get_table state) r in
        if not (List.is_empty fds) then
          (* Record type: keyword arguments [T(field=a, field2=b)] *)
          str cons_name ++ str "(" ++
          prlist_with_sep (fun () -> str ", ")
            (fun (i, a) ->
               pp_field_name state r fds i ++ str "=" ++ pp_expr state env a)
            (List.mapi (fun i a -> (i, a)) args) ++
          str ")"
        else if List.is_empty args then
          (* Zero-argument constructor.  Inline-custom constructors are plain
             literals (["True"], ["None"], ["0"], etc.) that are emitted
             as-is.  Native dataclass constructors need ["()"] appended so
             they produce an instance rather than a class reference. *)
          if is_inline_custom r then str cons_name
          else str cons_name ++ str "()"
        else
          (* Standard type: positional arguments [ConstrName(a, b)] *)
          str cons_name ++ str "(" ++
          prlist_with_sep (fun () -> str ", ") (pp_expr state env) args ++
          str ")"
  | MLcase (_, scrutinee, branches) ->
      (* Boolean match: [if cond then e1 else e2] → Python ternary [e1 if cond else e2].
         Detect the bool pattern by checking if the two arms are mapped to
         ["True"] and ["False"] via [Extract Inductive bool]. *)
      let is_bool =
        Array.length branches = 2 &&
        ( let (_, p0, _) = branches.(0) in
          let (_, p1, _) = branches.(1) in
          is_bool_patt p0 "True" && is_bool_patt p1 "False" )
      in
      if is_bool then
        let (_, _, body_true)  = branches.(0) in
        let (_, _, body_false) = branches.(1) in
        pp_expr state env body_true  ++ str " if " ++
        pp_expr state env scrutinee  ++ str " else " ++
        pp_expr state env body_false
      else if is_custom_match branches then
        (* Custom match function: [Extract Inductive T => "t" [...] "fn"].
           Emit as [fn(branch_thunk_0, branch_thunk_1, …, scrutinee)] where
           each branch becomes a Python lambda.  This handles types like
           [nat → int] whose constructors do not exist as Python patterns. *)
        pp_custom_match_expr state env (find_custom_match branches) scrutinee branches
      else
        (* Record projection: single-branch match over a record inductive.
           Instead of [match scrutinee: case Ctor(f0,f1): body], emit the
           lambda-lifted attribute form:
             (lambda f0, f1, …: body)(scrutinee.f0, scrutinee.f1, …)
           This mirrors [MLletin]'s lambda-lift strategy and stays at
           expression level without a [match] statement.
           [record_proj_info] handles the full detection and edge-case guarding.

           Key subtlety: branch [ids] only contains BOUND binders.  Wildcard
           sub-patterns in Rocq source compile to real variable binders (with
           fresh generated names) rather than [Pwild] in MiniML — so in
           practice every sub-pattern is [Prel k] and every field has a bound
           name.  The [Pwild] arm is kept as a defence against future changes. *)
        (match record_proj_info state branches with
        | Some (r, fds, sub_pats) ->
            let (ids, _, body) = branches.(0) in
            let n_fds = List.length fds in
            (* Push all binders (innermost-first for push_vars). *)
            let _, env' = push_vars (List.rev_map id_of_mlid ids) env in
            (* Derive the lambda parameter name for field position [i]:
               [Prel k] → look up the name at depth [k] in [env']
               [Pwild]  → synthetic [_e<i>] (can't repeat [_] in a lambda) *)
            let pp_param_for_pos i =
              match List.nth sub_pats i with
              | Prel k -> pp_pyid (get_db_name k env')
              | _      -> str ("_e" ^ string_of_int i)
            in
            (* Scrutinee is pure; sharing the [pp] value avoids duplication. *)
            let pp_scr = pp_expr state env scrutinee in
            let pp_arg i = pp_scr ++ str "." ++ pp_field_name state r fds i in
            str "(lambda " ++
            prlist_with_sep (fun () -> str ", ") pp_param_for_pos
              (List.init n_fds (fun i -> i)) ++
            str ": " ++
            pp_expr state env' body ++
            str ")(" ++
            prlist_with_sep (fun () -> str ", ") pp_arg
              (List.init n_fds (fun i -> i)) ++
            str ")"
        | None ->
        (* General match: emit Python [match]/[case] statement.
           This is a statement in Python, so it only works correctly when the
           surrounding [Dterm] or [MLletin] emits it inside a function body.
           The "Wire Dterm and Dfix" task handles that lifting.  For now we
           emit the raw statement form so the structure is visible. *)
        let pp_branch (ids, pat, body) =
          (* [push_vars] wants ids innermost-first (de Bruijn order).
             [collect_lams]/branch ids come outermost-first, so reverse. *)
          let _ids', env' = push_vars (List.rev_map id_of_mlid ids) env in
          (* Expand any top-level [Pusual r] into [Pcons(r,[Prel n;…;Prel 1])]
             so that [pp_pattern] can resolve every binder via [env'] alone. *)
          let pp_pat  = pp_pattern state env' (expand_pusual (List.length ids) pat) in
          let pp_body = pp_expr state env' body in
          str "    case " ++ pp_pat ++ str ":" ++ fnl () ++
          str "        " ++ pp_body
        in
        (* Append a catch-all arm unless the last explicit branch is already
           a wildcard.  Python [match] silently falls through with no result
           when no arm matches; [assert_never] turns that into a loud type-
           checker-visible error so non-exhaustive patterns are never silent.
           [case _:] is the Pythonic wildcard; [_] is still a valid variable
           so we can pass it to [assert_never] for the type-checker benefit. *)
        let catch_all =
          if has_wildcard_last branches then mt ()
          else fnl () ++ str "    case _:" ++ fnl () ++
               str "        assert_never(_)"
        in
        str "match " ++ pp_expr state env scrutinee ++ str ":" ++ fnl () ++
        prlist_with_sep fnl pp_branch (Array.to_list branches) ++
        catch_all)
  | MLfix (i, ids, defs) ->
      (* Mutual fixpoint: push all n names into the env (reversed, per the
         extraction convention so [ids.(0)] becomes the outermost binder),
         emit one [def] per function, then reference [ids.(i)] as the value.
         Python [def] is a statement, not an expression, so this is
         well-formed only at statement level; the "Wire Dterm and Dfix" task
         handles hoisting it into a function body when needed. *)
      let n = Array.length ids in
      (* [ids] is already [Id.t array]; no [id_of_mlid] needed. *)
      let id_list = List.rev (Array.to_list ids) in
      let names_rev, env' = push_vars id_list env in
      (* [List.rev names_rev] restores original array order:
         [name_arr.(j)] is the (possibly renamed) identifier for [ids.(j)]. *)
      let name_arr = Array.of_list (List.rev names_rev) in
      let pp_one j =
        (* Unwrap the body's lambdas to emit:
             def fname(p1, p2, ...):
                 return body
           If the body has no lambdas, emit [def fname(): return body]. *)
        let lam_ids, body = collect_lams defs.(j) in
        let params = List.map id_of_mlid lam_ids in
        let params', env'' = push_vars params env' in
        str "def " ++ pp_pyid name_arr.(j) ++ str "(" ++
        pp_param_list (List.rev params') ++
        str "):" ++ fnl () ++
        str "    return " ++ pp_expr state env'' body
      in
      prlist_with_sep fnl pp_one (List.init n (fun j -> j)) ++ fnl () ++
      pp_pyid name_arr.(i)

(*s Custom-match expression emitter.
    When [Extract Inductive T => "t" [conA conB] "fn"] supplies a match
    function, case analysis on [T] cannot use Python [match]/[case] (the
    constructors don't exist as Python patterns).  Instead we emit a
    functional application:

      (fn)(lambda: arm0_body, lambda x: arm1_body, …, scrutinee)

    Each branch becomes a [lambda] thunk.  The convention — branch thunks
    first, scrutinee last — must match what the user wrote in ["fn"].
    For example, for [nat → int]:

      Extract Inductive nat => "int" ["0" "(lambda x: x+1)"]
        "(lambda fO, fS, n: fO() if n == 0 else fS(n-1))".

    yields  [(lambda fO, fS, n: fO() if n == 0 else fS(n-1))(lambda: 0,
              lambda m_: ..., n)].

    [pp_custom_match_expr] is mutually recursive with [pp_expr] because it
    calls [pp_expr] to emit each branch body. *)

and pp_custom_match_expr state env s scrutinee branches =
  let pp_arm (ids, _pat, body) =
    let ids', env' = push_vars (List.rev_map id_of_mlid ids) env in
    let params = List.rev ids' in
    match params with
    | [] ->
        (* No binders: unit thunk. *)
        str "lambda: " ++ pp_expr state env' body
    | _  ->
        pp_lambda params (pp_expr state env' body)
  in
  str "(" ++ str s ++ str ")(" ++
  prlist_with_sep (fun () -> str ", ") pp_arm (Array.to_list branches) ++
  str ", " ++
  pp_expr state env scrutinee ++
  str ")"

let rec unwrap_fix = function
  | MLfix (i, ids, defs) -> Some (i, ids, defs)
  | MLmagic a            -> unwrap_fix a
  | _                    -> None

let collect_app f args =
  let rec collect acc = function
    | MLapp (g, more) -> collect (more @ acc) g
    | head            -> (head, acc)
  in
  collect args f

(*s Statement-level body printer for Python [def] bodies.
    Inside a [def], [return <match-stmt>] is invalid Python because [match] is
    a statement, not an expression.  This printer recurses into [MLcase]
    branches so that each leaf arm gets its own [return], producing valid
    Python.  The boolean ternary (two-arm bool match) is still treated as an
    expression and wrapped in a single [return].  Custom-match expressions
    are pure expressions and likewise wrapped in a single [return].

    [indent] is the indentation level (in spaces) at which the [match] keyword
    itself will appear.  [case] arms are emitted at [indent + 4], and their
    bodies at [indent + 8].  The first line of the emitted text does NOT include
    leading whitespace — the caller is responsible for that. *)

let rec pp_return_body state env indent = function
  | MLmagic a ->
      pp_return_body state env indent a
  | MLcase (_, scrutinee, branches) as expr ->
      let is_bool =
        Array.length branches = 2 &&
        ( let (_, p0, _) = branches.(0) in
          let (_, p1, _) = branches.(1) in
          is_bool_patt p0 "True" && is_bool_patt p1 "False" )
      in
      if is_bool then
        (* Ternary — valid expression; a single [return] suffices. *)
        str "return " ++ pp_expr state env expr
      else if is_custom_match branches then
        (* Custom-match — also a pure expression. *)
        str "return " ++
        pp_custom_match_expr state env (find_custom_match branches) scrutinee branches
      else
        (* Record projection — [record_proj_info] detects the single-branch
           record match; [pp_expr] emits the lambda-lift form, which is a
           valid expression so a single [return] suffices. *)
        ( match record_proj_info state branches with
          | Some _ ->
              str "return " ++ pp_expr state env expr
          | None ->
              (* General match: put [return] inside each arm so the branch is
                 a valid statement.  [case] must be indented inside the [match]
                 block; [body] must be indented inside the [case] block. *)
              let case_pfx = String.make (indent + 4) ' ' in
              let body_pfx = String.make (indent + 8) ' ' in
              let pp_branch (ids, pat, body) =
                let _ids', env' = push_vars (List.rev_map id_of_mlid ids) env in
                let pp_pat  = pp_pattern state env' (expand_pusual (List.length ids) pat) in
                str case_pfx ++ str "case " ++ pp_pat ++ str ":" ++ fnl () ++
                str body_pfx ++ pp_return_body state env' (indent + 8) body
              in
              (* Same catch-all logic as the expression-context path: append
                 [case _: assert_never(_)] unless the last explicit arm is already
                 a wildcard.  [_] is a valid Python variable even in [case _:],
                 so passing it to [assert_never] satisfies type checkers. *)
              let catch_all =
                if has_wildcard_last branches then mt ()
                else fnl () ++ str case_pfx ++ str "case _:" ++ fnl () ++
                     str body_pfx ++ str "assert_never(_)"
              in
              str "match " ++ pp_expr state env scrutinee ++ str ":" ++ fnl () ++
              prlist_with_sep fnl pp_branch (Array.to_list branches) ++
              catch_all )
  | MLaxiom _ | MLexn _ | MLparray _ as expr ->
      (* These emit [raise …], which is a valid Python statement but NOT a
         valid expression.  Emit bare — no [return] prefix. *)
      pp_expr state env expr
  | MLletin (id, a1, a2) -> (
      (* Let-bound local fixpoint inside a function body:
           let f = fix ... in body
         becomes nested [def] statements followed by the returned body.  This
         is the shape produced by Program Fixpoint's [Fix_sub] helper. *)
      match unwrap_fix a1 with
      | None ->
          str "return " ++ pp_expr state env (MLletin (id, a1, a2))
      | Some (i, ids, defs) ->
      let params, env' = push_vars [id_of_mlid id] env in
      let bname = List.hd params in
      let def_pfx = String.make indent ' ' in
      let pp_defs, selected = pp_fix_statement state env indent i ids defs in
      let pp_alias =
        if Id.equal bname selected then mt ()
        else
          fnl () ++ str def_pfx ++ pp_pyid bname ++
          str " = " ++ pp_pyid selected
      in
      pp_defs ++ pp_alias ++ fnl () ++ str def_pfx ++
      pp_return_body state env' indent a2 )
  | MLapp (f, args) -> (
      match collect_app f args with
      | head, all_args -> (
          match unwrap_fix head with
          | None ->
              str "return " ++ pp_expr state env (MLapp (f, args))
          | Some (i, ids, defs) ->
              let def_pfx = String.make indent ' ' in
              let pp_defs, selected = pp_fix_statement state env indent i ids defs in
              let visible_args =
                List.filter (fun a -> not (is_erased_arg a)) all_args
              in
              pp_defs ++ fnl () ++ str def_pfx ++ str "return " ++
              pp_pyid selected ++ str "(" ++
              prlist_with_sep (fun () -> str ", ") (pp_expr state env) visible_args ++
              str ")" ) )
  | MLfix (i, ids, defs) ->
      (* Local fixpoint inside a function body.  Python [def] is a statement,
         so emit nested defs followed by [return selected_name] instead of
         trying to put [def] after [return]. *)
      let def_pfx = String.make indent ' ' in
      let pp_defs, selected = pp_fix_statement state env indent i ids defs in
      pp_defs ++ fnl () ++ str def_pfx ++ str "return " ++ pp_pyid selected
  | expr ->
      str "return " ++ pp_expr state env expr

and pp_fix_statement state env indent i ids defs =
  let n = Array.length ids in
  let id_list = List.rev (Array.to_list ids) in
  let names_rev, env' = push_vars id_list env in
  let name_arr = Array.of_list (List.rev names_rev) in
  let def_pfx = String.make indent ' ' in
  let body_pfx = String.make (indent + 4) ' ' in
  let pp_one j =
    let lam_ids, body = collect_lams defs.(j) in
    let params = List.map id_of_mlid lam_ids in
    let params', env'' = push_vars params env' in
    str "def " ++ pp_pyid name_arr.(j) ++ str "(" ++
    pp_param_list (List.rev params') ++
    str "):" ++ fnl () ++
    str body_pfx ++ pp_return_body state env'' (indent + 4) body
  in
  prlist_with_sep (fun () -> fnl () ++ str def_pfx) pp_one
    (List.init n (fun j -> j)),
  name_arr.(i)

(*s Python term declaration emitter.
    Detects a lambda-headed RHS and promotes it to a [def]; non-lambda
    RHS stays as a simple assignment. *)

(** Emit either [def name(p1,…): return body] or [name = expr], choosing
    based on whether [a] has leading lambdas. *)
let pp_function_wrapper state env name a typ =
  let args, _ret = type_decomp typ in
  let n = List.length args in
  if Int.equal n 0 then None
  else
    let arg_names =
      if Int.equal n 1 then ["x"]
      else List.init n (fun i -> "arg" ^ string_of_int i)
    in
    let pp_arg s = str s in
    let pp_call =
      match a with
      | MLapp (f, app_args) ->
          let head, all_args = collect_app f app_args in
          let visible_args =
            List.filter (fun a -> not (is_erased_arg a)) all_args
          in
          let pp_head =
            match head with
            | MLlam _ -> str "(" ++ pp_expr state env head ++ str ")"
            | _       -> pp_expr state env head
          in
          pp_head ++ str "(" ++
          prlist_with_sep (fun () -> str ", ") (pp_expr state env) visible_args ++
          (if List.is_empty visible_args then mt () else str ", ") ++
          prlist_with_sep (fun () -> str ", ") pp_arg arg_names ++
          str ")"
      | _ ->
          str "(" ++ pp_expr state env a ++ str ")(" ++
          prlist_with_sep (fun () -> str ", ") pp_arg arg_names ++
          str ")"
    in
    Some (
      str "def " ++ str name ++ str "(" ++
      prlist_with_sep (fun () -> str ", ") pp_arg arg_names ++
      str "):" ++ fnl () ++
      str "    return " ++ pp_call ++ fnl ()
    )

let pp_term_decl state env name a typ =
  let lam_ids, body = collect_lams a in
  if List.is_empty lam_ids then
    (* Non-function value: simple assignment — unless the body is a [raise]
       expression (MLaxiom / MLexn / MLparray), which cannot appear as the
       RHS of an assignment.  In that case emit the statement bare. *)
    ( match a with
      | MLaxiom _ | MLexn _ | MLparray _ ->
          pp_expr state env a ++ fnl ()
      | _ ->
          (match pp_function_wrapper state env name a typ with
          | Some pp -> pp
          | None -> str name ++ str " = " ++ pp_expr state env a ++ fnl ()) )
  else
    let params = List.map id_of_mlid lam_ids in
    let params', env' = push_vars params env in
    str "def " ++ str name ++ str "(" ++
    pp_param_list (List.rev params') ++
    str "):" ++ fnl () ++
    (* [indent=4]: the body is indented by 4 spaces inside the def; [case] arms
       at 8, case bodies at 12.  The "    " prefix handles the first line only;
       [pp_return_body] generates the rest with absolute column positions. *)
    str "    " ++ pp_return_body state env' 4 body ++ fnl ()

(*s TypeVar name helper. *)

(** Python [TypeVar] name for the [i]-th type parameter (0-based).
    Indices 0–25 map to [_A]–[_Z]; beyond that we use [_T<i>] so we
    never run out of names for exotic mutual inductives. *)
let typevar_name i =
  if i < 26 then Printf.sprintf "_%c" (Char.chr (65 + i))
  else Printf.sprintf "_T%d" i

(*s Type annotation emitter.
    Converts an [ml_type] to a Python annotation fragment.  The annotations
    are used only for documentation and optional static analysis —
    correctness of generated code never depends on them (Python is
    dynamically typed).

    PEP 649 deferred annotation evaluation (Python 3.14t default) means
    forward and recursive references work without explicit quoting. *)

let rec pp_type state = function
  | Tarr (t1, t2) ->
      (* Arrow type → [Callable[[arg], ret]].  Curried chains stay nested:
         [Tarr(a, Tarr(b, c))] → [Callable[[a], Callable[[b], c]]]. *)
      str "Callable[[" ++ pp_type state t1 ++ str "], " ++
      pp_type state t2 ++ str "]"
  | Tglob (r, args) ->
      (* Look up the Python name: prefer the custom string if present
         (e.g. [nat → "int"]), otherwise use the mangled global name.
         An empty custom string signals singleton/transparent erasure
         (e.g. [option → ""]); fall back to [object] in that case.
         Inductive type names are capitalized to match the class names
         emitted by [pp_ind_decl] (PEP 8 PascalCase convention). *)
      let name =
        if is_inline_custom r then find_custom r
        else
          let n = pp_global state Term r in
          let open GlobRef in
          match r.glob with
          | IndRef _ -> capitalize_first n
          | _        -> n
      in
      if String.equal "" name then str "object"
      else if List.is_empty args then str name
      else
        str name ++ str "[" ++
        prlist_with_sep (fun () -> str ", ") (pp_type state) args ++
        str "]"
  | Tvar i | Tvar' i ->
      (* Emit the TypeVar name corresponding to the [i]-th type parameter.
         The TypeVar declaration itself is emitted by [pp_ind_decl]. *)
      str (typevar_name i)
  | Tdummy _ | Tunknown | Taxiom | Tmeta _ ->
      str "object"

(*s Inductive type emission as Python dataclasses.
    Each live constructor becomes a frozen [@dataclass] class whose fields
    are the constructor arguments.  Record types use the declared field
    names; all others use positional names [arg0], [arg1], ….

    Standard and Coinductive inductives also get a shared base class so that
    Python's [match]/[case] discriminator can be written against the type
    name rather than enumerating every constructor:

      class Nat:
          pass

      @dataclass(frozen=True)
      class Nat_O(Nat):
          pass

      @dataclass(frozen=True)
      class Nat_S(Nat):
          arg0: nat          # typed via pp_type

    Records have a single constructor that *is* the type, so no separate
    base class is emitted there. *)

(** Emit one [@dataclass(frozen=True)] class for constructor [j] of [packet].
    If [base_opt] is [Some base], the class inherits from [base]. *)
let pp_one_cons state packet fields_opt base_opt j =
  let cname = pp_global state Cons packet.ip_consnames_ref.(j) in
  let nargs  = List.length packet.ip_types.(j) in
  let ind_kn = kn_of_ind packet.ip_typename_ref in
  let field_name i =
    match fields_opt with
    | Some fds ->
        ( match List.nth fds i with
          | Some r' -> pp_global_with_key state Term ind_kn r'
          | None    -> Printf.sprintf "arg%d" i )
    | None -> Printf.sprintf "arg%d" i
  in
  let pp_bases = match base_opt with
    | None      -> mt ()
    | Some base -> str "(" ++ str base ++ str ")"
  in
  str "@dataclass(frozen=True)" ++ fnl () ++
  str "class " ++ str cname ++ pp_bases ++ str ":" ++ fnl () ++
  ( if nargs = 0 then str "    pass" ++ fnl ()
    else
      prlist_with_sep mt
        (fun i ->
           str "    " ++ str (field_name i) ++ str ": " ++
           pp_type state (List.nth packet.ip_types.(j) i) ++ fnl ())
        (List.init nargs (fun i -> i)) )

let pp_ind_decl state (ind : ml_ind) =
  match ind.ind_kind with
  | Singleton ->
      (* Constructor is transparent at expression level; emit a comment. *)
      let p = ind.ind_packets.(0) in
      if p.ip_logical then
        str "# " ++ Id.print p.ip_typename ++ str ": logical inductive" ++ fnl ()
      else if is_custom p.ip_typename_ref then
        str "# " ++ Id.print p.ip_typename ++
        str ": remapped to Python primitive via Extract Inductive" ++ fnl ()
      else
        str "# " ++ Id.print p.ip_typename ++
        str ": singleton inductive, constructor was " ++
        Id.print p.ip_consnames.(0) ++ fnl ()
  | Record fields ->
      let p = ind.ind_packets.(0) in
      if p.ip_logical then
        str "# " ++ Id.print p.ip_typename ++ str ": logical record" ++ fnl ()
      else if is_custom p.ip_typename_ref then
        str "# " ++ Id.print p.ip_typename ++
        str ": remapped to Python primitive via Extract Inductive" ++ fnl ()
      else
        let tvars = List.init ind.ind_nparams typevar_name in
        (* Emit TypeVar declarations once, before the dataclass. *)
        let pp_typevars =
          if List.is_empty tvars then mt ()
          else
            prlist_with_sep mt
              (fun tv ->
                 str tv ++ str " = TypeVar(\"" ++ str tv ++ str "\")" ++ fnl ())
              tvars ++ fnl ()
        in
        (* For a parameterised record, inherit [Generic[_A, _B, …]] so that
           type-checkers can track type arguments.  Unparameterised records
           keep the plain dataclass (no base class). *)
        let base_opt =
          if List.is_empty tvars then None
          else
            Some ("Generic[" ^ String.concat ", " tvars ^ "]")
        in
        pp_typevars ++
        pp_one_cons state p (Some fields) base_opt 0
  | Standard | Coinductive ->
      let tvars = List.init ind.ind_nparams typevar_name in
      (* TypeVar declarations are emitted once, before all packets, because
         mutual inductives share the same type parameters.  For example,
         [tree A] and [forest A] in a mutual definition both use [_A]. *)
      let pp_typevars =
        if List.is_empty tvars then mt ()
        else
          prlist_with_sep mt
            (fun tv ->
               str tv ++ str " = TypeVar(\"" ++ str tv ++ str "\")" ++ fnl ())
            tvars ++ fnl ()
      in
      let pp_packet p =
        if p.ip_logical then
          str "# " ++ Id.print p.ip_typename ++ str ": logical inductive" ++ fnl ()
        else if is_custom p.ip_typename_ref then
          str "# " ++ Id.print p.ip_typename ++
          str ": remapped to Python primitive via Extract Inductive" ++ fnl ()
        else
          let tname = capitalize_first (pp_global state Term p.ip_typename_ref) in
          let n = Array.length p.ip_types in
          (* Shared base class.  For parameterised inductives it inherits
             [Generic[_A, …]] so that type-checkers can track type arguments. *)
          let pp_base =
            if List.is_empty tvars then
              str "class " ++ str tname ++ str ":" ++ fnl () ++
              str "    pass" ++ fnl ()
            else
              str "class " ++ str tname ++
              str "(Generic[" ++
              prlist_with_sep (fun () -> str ", ") str tvars ++
              str "]):" ++ fnl () ++
              str "    pass" ++ fnl ()
          in
          (* Constructor dataclasses, each inheriting from the base class. *)
          let pp_cons =
            prlist_with_sep (fun () -> fnl ())
              (fun j -> pp_one_cons state p None (Some tname) j)
              (List.init n (fun j -> j))
          in
          (* Union alias for type-checker use: [TypeNameT = Con1 | Con2 | …].
             PEP 604 union syntax (Python 3.10+, fine — we target 3.14t). *)
          let cons_names =
            List.init n (fun j -> pp_global state Cons p.ip_consnames_ref.(j))
          in
          let pp_union =
            str tname ++ str "T = " ++
            prlist_with_sep (fun () -> str " | ") str cons_names ++
            fnl ()
          in
          pp_base ++ fnl () ++
          pp_cons ++ fnl () ++
          fnl () ++ pp_union
      in
      pp_typevars ++
      prlist_with_sep (fun () -> fnl ())
        pp_packet
        (Array.to_list ind.ind_packets)

(*s Declaration printer. *)

let pp_decl state = function
  | Dind  ind   -> pp_ind_decl state ind ++ fnl ()
  | Dtype _     -> str "# UNIMPL Dtype" ++ fnl ()
  | Dterm (r, a, typ) ->
      if is_inline_custom r then mt ()
      else if is_custom r then
        str (pp_global state Term r) ++ str " = " ++
        str (find_custom r) ++ fnl ()
      else
        let env = empty_env state () in
        pp_term_decl state env (pp_global state Term r) a typ
  | Dfix (rv, defs, typs) ->
      (* Each function in the fix block is named globally; the bodies use
         [MLglob] references for mutual recursion, so [empty_env] suffices. *)
      let env = empty_env state () in
      let pp_one i =
        if is_inline_custom rv.(i) then mt ()
        else if is_custom rv.(i) then
          str (pp_global state Term rv.(i)) ++ str " = " ++
          str (find_custom rv.(i)) ++ fnl ()
        else
          pp_term_decl state env (pp_global state Term rv.(i)) defs.(i) typs.(i)
      in
      prlist_with_sep mt pp_one (List.init (Array.length rv) (fun i -> i))

(*s Module structure walker.
    [State.with_visibility] must be called around each module so that
    [pp_global] can resolve names relative to the current module path. *)

let pp_structure_elem state = function
  | (_, SEdecl d)    -> pp_decl state d
  | (_, SEmodule _)  -> str "# UNIMPL SEmodule"  ++ fnl ()
  | (_, SEmodtype _) -> str "# UNIMPL SEmodtype" ++ fnl ()

let pp_struct state struc =
  let pp_mod (mp, sel) =
    State.with_visibility state mp [] (fun state ->
      prlist (pp_structure_elem state) sel)
  in
  prlist pp_mod struc

(*s No interface file for Python. *)

let sig_preamble _state _name _comment _used_modules _safe = mt ()

let pp_sig _state _sig = mt ()

(*s The language descriptor record registered with the extraction framework. *)

let python_descr : Common.State.t language_descr = {
  keywords;
  file_suffix    = ".py";
  file_naming;
  preamble;
  pp_struct;
  sig_suffix     = None;
  sig_preamble;
  pp_sig;
  pp_decl;
}
