#!/usr/bin/env bash
# Generate _data/stats/<from>.yml from FidoCanCode's GitHub activity.
#
# Usage:
#   scripts/generate-stats.sh <date>             # single day
#   scripts/generate-stats.sh <from> <to>        # date range, inclusive
#
# Dates are ISO format (YYYY-MM-DD), interpreted as UTC.  The output file
# is keyed on <from> so each blog post has a stable companion data file.
# Both index and post layouts read this via site.data.stats[date].
#
# Sources — all from GitHub's GraphQL API (no local clones needed):
#  - Commits: contributionsCollection.commitContributionsByRepository
#  - PRs / issues / reviews: contributionsCollection totals
#
# Identity transition: before 2026-04-06 Fido's work was committed under
# "Robert Hencke" / rhencke.  For windows entirely before that date the
# script uses the pre-transition identity so April 5 (Fido's first day) is
# credited correctly.
#
# Requires: gh, python3.
set -euo pipefail

if [[ $# -lt 1 || $# -gt 2 ]]; then
  echo "usage: $0 <from> [to]" >&2
  exit 1
fi

from=$1
to=${2:-$1}

for d in "$from" "$to"; do
  if ! [[ $d =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
    echo "invalid date: $d (expected YYYY-MM-DD)" >&2
    exit 1
  fi
done

docs_root=$(cd "$(dirname "$0")/.." && pwd -P)
out="$docs_root/_data/stats/$from.yml"
mkdir -p "$(dirname "$out")"

# Repos we track.
MANAGED_REPOS=("rhencke/confusio" "FidoCanCode/home")

# Before 2026-04-06, work was committed under Robert Hencke / rhencke before
# Fido's identity was established.  We credit those contributions to Fido by
# using the pre-transition GitHub login for any window that falls entirely
# before the transition date.
fido_login="FidoCanCode"
pre_transition_login="rhencke"
transition_date="2026-04-06"

since="${from}T00:00:00Z"
until="${to}T23:59:59Z"

if [[ "$to" < "$transition_date" ]]; then
  login="$pre_transition_login"
else
  login="$fido_login"
fi

# Single GraphQL query: commits by repo + PR/issue/review totals.
query='query($login: String!, $from: DateTime!, $to: DateTime!) {
  user(login: $login) {
    contributionsCollection(from: $from, to: $to) {
      totalIssueContributions
      totalPullRequestContributions
      totalPullRequestReviewContributions
      commitContributionsByRepository {
        repository { nameWithOwner }
        contributions { totalCount }
      }
    }
  }
}'

response=$(gh api graphql \
  -F login="$login" \
  -F from="$since" \
  -F to="$until" \
  -f query="$query")

MANAGED_REPOS_LIST="${MANAGED_REPOS[*]}" \
RESPONSE_JSON="$response" \
python3 - "$from" "$to" "$out" <<'PY'
import json
import os
import sys

from_date, to_date, out_path = sys.argv[1:4]

managed = set(os.environ["MANAGED_REPOS_LIST"].split())
response = json.loads(os.environ["RESPONSE_JSON"])
collection = response["data"]["user"]["contributionsCollection"]

issues = collection["totalIssueContributions"]
prs = collection["totalPullRequestContributions"]
reviews = collection["totalPullRequestReviewContributions"]

total_commits = 0
touched_repos = []
for entry in collection["commitContributionsByRepository"]:
    repo = entry["repository"]["nameWithOwner"]
    count = entry["contributions"]["totalCount"]
    if repo in managed and count > 0:
        total_commits += count
        touched_repos.append(repo)

touched_repos.sort()

with open(out_path, "w") as f:
    f.write("# Auto-generated by scripts/generate-stats.sh. Do not edit by hand.\n")
    f.write(f"date: {from_date}\n")
    f.write("date_range:\n")
    f.write(f"  from: {from_date}\n")
    f.write(f"  to: {to_date}\n")
    f.write(f"commits: {total_commits}\n")
    f.write(f"prs: {prs}\n")
    f.write(f"issues: {issues}\n")
    f.write(f"reviews: {reviews}\n")
    f.write("repos:\n")
    for r in touched_repos:
        f.write(f"  - {r}\n")

print(
    f"wrote {out_path}: {total_commits} commits, {prs} PRs, "
    f"{issues} issues, {reviews} reviews across {len(touched_repos)} repos"
)
PY
