# Generated by rocq-python-extraction (target: Python 3.14t)
from dataclasses import dataclass
from typing import Callable, Generic, TypeVar

__ = None  # erased logical argument


def bool_not(b):
    return False if b else True
