# Generated by rocq-python-extraction (target: Python 3.14t)
from dataclasses import dataclass
from typing import Callable, Generic, TypeVar

__ = None  # erased logical argument
_A = TypeVar("_A")

# option: remapped to Python primitive via Extract Inductive


class state:
    pass


@dataclass(frozen=True)
class Free(state):
    pass


@dataclass(frozen=True)
class OwnedByWorker(state):
    pass


@dataclass(frozen=True)
class OwnedByHandler(state):
    pass


stateT = Free | OwnedByWorker | OwnedByHandler


class event:
    pass


@dataclass(frozen=True)
class WorkerAcquire(event):
    pass


@dataclass(frozen=True)
class HandlerAcquire(event):
    pass


@dataclass(frozen=True)
class WorkerRelease(event):
    pass


@dataclass(frozen=True)
class HandlerRelease(event):
    pass


@dataclass(frozen=True)
class Preempt(event):
    pass


eventT = WorkerAcquire | HandlerAcquire | WorkerRelease | HandlerRelease | Preempt


def transition(current, event0):
    match current:
        case Free():
            match event0:
                case WorkerAcquire():
                    return OwnedByWorker()
                case HandlerAcquire():
                    return OwnedByHandler()
                case WorkerRelease():
                    return None
                case HandlerRelease():
                    return None
                case Preempt():
                    return None
        case OwnedByWorker():
            match event0:
                case WorkerAcquire():
                    return None
                case HandlerAcquire():
                    return None
                case WorkerRelease():
                    return Free()
                case HandlerRelease():
                    return None
                case Preempt():
                    return OwnedByHandler()
        case OwnedByHandler():
            match event0:
                case WorkerAcquire():
                    return None
                case HandlerAcquire():
                    return None
                case WorkerRelease():
                    return None
                case HandlerRelease():
                    return Free()
                case Preempt():
                    return None
