#!/usr/bin/env python3
"""Generate the CI workflow from the buildx bake target graph."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
WORKFLOW = ROOT / ".github" / "workflows" / "ci.yml"

EXTRA_CACHES = {
    "rocq-model-image": ".cache/rocq-models/image",
    "rocq-model-buildx": ".cache/rocq-models/buildx",
    "rocq-model-context": ".cache/rocq-models/context",
}


def bake_plan() -> dict[str, object]:
    output = subprocess.check_output(
        ["docker", "buildx", "bake", "--print", "warm"],
        cwd=ROOT,
        text=True,
        stderr=subprocess.STDOUT,
    )
    start = output.find("{")
    end = output.rfind("}")
    if start == -1 or end == -1:
        raise SystemExit(f"docker buildx bake --print did not emit JSON:\n{output}")
    return json.loads(output[start : end + 1])


def cache_entries(plan: dict[str, object]) -> list[tuple[str, str]]:
    _ = cache_scopes(plan)
    return list(EXTRA_CACHES.items())


def cache_scopes(plan: dict[str, object]) -> list[str]:
    targets = plan.get("target")
    if not isinstance(targets, dict):
        raise SystemExit("buildx bake plan did not include target map")
    return sorted(targets)


def restore_step(name: str, path: str) -> str:
    return f"""\
      - name: Restore {name} build cache
        uses: actions/cache/restore@v4
        with:
          path: {path}
          key: buildx-{name}-${{{{ runner.os }}}}-${{{{ steps.build-cache.outputs.bucket }}}}-${{{{ github.run_id }}}}-${{{{ github.run_attempt }}}}
          restore-keys: |
            buildx-{name}-${{{{ runner.os }}}}-${{{{ steps.build-cache.outputs.bucket }}}}-
            buildx-{name}-${{{{ runner.os }}}}-
"""


def save_step(name: str, path: str) -> str:
    return f"""\
      - name: Save {name} build cache
        if: success()
        uses: actions/cache/save@v4
        with:
          path: {path}
          key: buildx-{name}-${{{{ runner.os }}}}-${{{{ steps.build-cache.outputs.bucket }}}}-${{{{ github.run_id }}}}-${{{{ github.run_attempt }}}}
"""


def render(plan: dict[str, object]) -> str:
    restores = "".join(restore_step(name, path) for name, path in cache_entries(plan))
    saves = "".join(save_step(name, path) for name, path in cache_entries(plan))
    scopes = ", ".join(cache_scopes(plan))
    return f"""\
# Generated by .github/workflows/generate_ci.py; do not edit by hand.
# Buildx gha cache scopes discovered from bake: {scopes}
name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '17 3 */6 * *'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      FIDO_BUILDX_CACHE_BACKEND: gha
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        id: setup-buildx
      - name: Compute build cache bucket
        id: build-cache
        run: echo "bucket=$(( $(date +%s) / 518400 ))" >> "$GITHUB_OUTPUT"
{restores}      - name: Restore buildkit cache mounts
        uses: actions/cache@v4
        with:
          path: .cache/buildkit-mounts
          key: buildkit-mounts-${{{{ runner.os }}}}-${{{{ steps.build-cache.outputs.bucket }}}}-${{{{ github.run_id }}}}-${{{{ github.run_attempt }}}}
          restore-keys: |
            buildkit-mounts-${{{{ runner.os }}}}-${{{{ steps.build-cache.outputs.bucket }}}}-
            buildkit-mounts-${{{{ runner.os }}}}-
      - name: Inject buildkit cache mounts
        uses: reproducible-containers/buildkit-cache-dance@v3.3.2
        with:
          builder: ${{{{ steps.setup-buildx.outputs.name }}}}
          cache-dir: .cache/buildkit-mounts
          dockerfile: models/Dockerfile
      - run: ./.githooks/pre-commit
      - name: Check committed model mirrors
        run: |
          ./fido make-rocq
          git diff --exit-code -- src/fido/rocq/
{saves}"""


def main() -> None:
    WORKFLOW.write_text(render(bake_plan()))


if __name__ == "__main__":
    main()
